/*
  This file is automatically generated by MectConfigurator x.xx
  
INT       <-> int16_t
UINT      <-> u_int16_t
DINT      <-> int32_t
UDINT     <-> u_int32_t
REAL      <-> float
BIT       <-> int
BYTE_BIT  <-> int
WORD_BIT  <-> int
DWORD_BIT <-> int

*/
#ifndef CROSSTABLE_H
#define CROSSTABLE_H

#include <stdint.h>

int update_all(void);

#endif

