/* File automatically generated by the Crosstable compiler */
/* from the Crosstable file config/Crosstable.csv. */

/* BIT        ->  int       */
/* BYTE_BIT   ->  int       */
/* WORD_BIT   ->  int       */
/* DWORD_BIT  ->  int       */
/* BYTE       ->  u_int8_t  */
/* UINT       ->  u_int16_t */
/* UINTBA     ->  UINTBA    */
/* INT        ->  int16_t   */
/* INTBA      ->  INTBA     */
/* UDINT      ->  u_int32_t */
/* UDINTBADC  ->  UDINTBADC */
/* UDINTCDAB  ->  UDINTCDAB */
/* UDINTDCBA  ->  UDINTDCBA */
/* DINT       ->  int32_t   */
/* DINTBADC   ->  DINTBADC  */
/* DINTCDAB   ->  DINTCDAB  */
/* DINTDCBA   ->  DINTDCBA  */
/* REAL       ->  float     */
/* REALBADC   ->  REALBADC  */
/* REALCDAB   ->  REALCDAB  */
/* REALDCBA   ->  REALDCBA  */

#ifndef CROSSTABLE_H__
#define CROSSTABLE_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <sys/types.h>
#include "cross_table_utility.h"


#define ID_STATUS 193
extern u_int16_t STATUS;
int doWrite_STATUS(u_int16_t value);
int addWrite_STATUS(u_int16_t value);
int getStatus_STATUS(void);

#define ID_RTU_HEARTBEAT 194
extern u_int16_t RTU_HEARTBEAT;
int doWrite_RTU_HEARTBEAT(u_int16_t value);
int addWrite_RTU_HEARTBEAT(u_int16_t value);
int getStatus_RTU_HEARTBEAT(void);

#define ID_RTU_RTU_WR 195
extern int RTU_RTU_WR;
int doWrite_RTU_RTU_WR(int value);
int addWrite_RTU_RTU_WR(int value);
int getStatus_RTU_RTU_WR(void);

#define ID_RTU_RTU_RD 196
extern int RTU_RTU_RD;
int doWrite_RTU_RTU_RD(int value);
int addWrite_RTU_RTU_RD(int value);
int getStatus_RTU_RTU_RD(void);

#define ID_MPNC005_BAUDRATE 198
extern u_int16_t MPNC005_BAUDRATE;
int doWrite_MPNC005_BAUDRATE(u_int16_t value);
int addWrite_MPNC005_BAUDRATE(u_int16_t value);
int getStatus_MPNC005_BAUDRATE(void);

#define ID_MPNC005_ADDRESS 199
extern u_int16_t MPNC005_ADDRESS;
int doWrite_MPNC005_ADDRESS(u_int16_t value);
int addWrite_MPNC005_ADDRESS(u_int16_t value);
int getStatus_MPNC005_ADDRESS(void);

#define ID_MPNC005_LIFETIME 200
extern u_int16_t MPNC005_LIFETIME;
int doWrite_MPNC005_LIFETIME(u_int16_t value);
int addWrite_MPNC005_LIFETIME(u_int16_t value);
int getStatus_MPNC005_LIFETIME(void);

#define ID_MPNC005_AnInCf_1 202
extern u_int16_t MPNC005_AnInCf_1;
int doWrite_MPNC005_AnInCf_1(u_int16_t value);
int addWrite_MPNC005_AnInCf_1(u_int16_t value);
int getStatus_MPNC005_AnInCf_1(void);

#define ID_MPNC005_AnInCf_2 203
extern u_int16_t MPNC005_AnInCf_2;
int doWrite_MPNC005_AnInCf_2(u_int16_t value);
int addWrite_MPNC005_AnInCf_2(u_int16_t value);
int getStatus_MPNC005_AnInCf_2(void);

#define ID_MPNC005_AnIn_1 204
extern int16_t MPNC005_AnIn_1;
int doWrite_MPNC005_AnIn_1(int16_t value);
int addWrite_MPNC005_AnIn_1(int16_t value);
int getStatus_MPNC005_AnIn_1(void);

#define ID_MPNC005_AnIn_2 205
extern int16_t MPNC005_AnIn_2;
int doWrite_MPNC005_AnIn_2(int16_t value);
int addWrite_MPNC005_AnIn_2(int16_t value);
int getStatus_MPNC005_AnIn_2(void);

#define ID_MPNC005_DigDir_1 206
extern int MPNC005_DigDir_1;
int doWrite_MPNC005_DigDir_1(int value);
int addWrite_MPNC005_DigDir_1(int value);
int getStatus_MPNC005_DigDir_1(void);

#define ID_MPNC005_DigDir_2 207
extern int MPNC005_DigDir_2;
int doWrite_MPNC005_DigDir_2(int value);
int addWrite_MPNC005_DigDir_2(int value);
int getStatus_MPNC005_DigDir_2(void);

#define ID_MPNC005_DigDir_3 208
extern int MPNC005_DigDir_3;
int doWrite_MPNC005_DigDir_3(int value);
int addWrite_MPNC005_DigDir_3(int value);
int getStatus_MPNC005_DigDir_3(void);

#define ID_MPNC005_DigDir_4 209
extern int MPNC005_DigDir_4;
int doWrite_MPNC005_DigDir_4(int value);
int addWrite_MPNC005_DigDir_4(int value);
int getStatus_MPNC005_DigDir_4(void);

#define ID_MPNC005_DigDir_5 210
extern int MPNC005_DigDir_5;
int doWrite_MPNC005_DigDir_5(int value);
int addWrite_MPNC005_DigDir_5(int value);
int getStatus_MPNC005_DigDir_5(void);

#define ID_MPNC005_DigDir_6 211
extern int MPNC005_DigDir_6;
int doWrite_MPNC005_DigDir_6(int value);
int addWrite_MPNC005_DigDir_6(int value);
int getStatus_MPNC005_DigDir_6(void);

#define ID_MPNC005_DigDir_7 212
extern int MPNC005_DigDir_7;
int doWrite_MPNC005_DigDir_7(int value);
int addWrite_MPNC005_DigDir_7(int value);
int getStatus_MPNC005_DigDir_7(void);

#define ID_MPNC005_DigDir_8 213
extern int MPNC005_DigDir_8;
int doWrite_MPNC005_DigDir_8(int value);
int addWrite_MPNC005_DigDir_8(int value);
int getStatus_MPNC005_DigDir_8(void);

#define ID_MPNC005_DigIn_1 214
extern int MPNC005_DigIn_1;
int doWrite_MPNC005_DigIn_1(int value);
int addWrite_MPNC005_DigIn_1(int value);
int getStatus_MPNC005_DigIn_1(void);

#define ID_MPNC005_DigIn_2 215
extern int MPNC005_DigIn_2;
int doWrite_MPNC005_DigIn_2(int value);
int addWrite_MPNC005_DigIn_2(int value);
int getStatus_MPNC005_DigIn_2(void);

#define ID_MPNC005_DigIn_3 216
extern int MPNC005_DigIn_3;
int doWrite_MPNC005_DigIn_3(int value);
int addWrite_MPNC005_DigIn_3(int value);
int getStatus_MPNC005_DigIn_3(void);

#define ID_MPNC005_DigIn_4 217
extern int MPNC005_DigIn_4;
int doWrite_MPNC005_DigIn_4(int value);
int addWrite_MPNC005_DigIn_4(int value);
int getStatus_MPNC005_DigIn_4(void);

#define ID_MPNC005_DigIn_5 218
extern int MPNC005_DigIn_5;
int doWrite_MPNC005_DigIn_5(int value);
int addWrite_MPNC005_DigIn_5(int value);
int getStatus_MPNC005_DigIn_5(void);

#define ID_MPNC005_DigIn_6 219
extern int MPNC005_DigIn_6;
int doWrite_MPNC005_DigIn_6(int value);
int addWrite_MPNC005_DigIn_6(int value);
int getStatus_MPNC005_DigIn_6(void);

#define ID_MPNC005_DigIn_7 220
extern int MPNC005_DigIn_7;
int doWrite_MPNC005_DigIn_7(int value);
int addWrite_MPNC005_DigIn_7(int value);
int getStatus_MPNC005_DigIn_7(void);

#define ID_MPNC005_DigIn_8 221
extern int MPNC005_DigIn_8;
int doWrite_MPNC005_DigIn_8(int value);
int addWrite_MPNC005_DigIn_8(int value);
int getStatus_MPNC005_DigIn_8(void);

#define ID_MPNC005_DigOut_1 222
extern int MPNC005_DigOut_1;
int doWrite_MPNC005_DigOut_1(int value);
int addWrite_MPNC005_DigOut_1(int value);
int getStatus_MPNC005_DigOut_1(void);

#define ID_MPNC005_DigOut_2 223
extern int MPNC005_DigOut_2;
int doWrite_MPNC005_DigOut_2(int value);
int addWrite_MPNC005_DigOut_2(int value);
int getStatus_MPNC005_DigOut_2(void);

#define ID_MPNC005_DigOut_3 224
extern int MPNC005_DigOut_3;
int doWrite_MPNC005_DigOut_3(int value);
int addWrite_MPNC005_DigOut_3(int value);
int getStatus_MPNC005_DigOut_3(void);

#define ID_MPNC005_DigOut_4 225
extern int MPNC005_DigOut_4;
int doWrite_MPNC005_DigOut_4(int value);
int addWrite_MPNC005_DigOut_4(int value);
int getStatus_MPNC005_DigOut_4(void);

#define ID_MPNC005_DigOut_5 226
extern int MPNC005_DigOut_5;
int doWrite_MPNC005_DigOut_5(int value);
int addWrite_MPNC005_DigOut_5(int value);
int getStatus_MPNC005_DigOut_5(void);

#define ID_MPNC005_DigOut_6 227
extern int MPNC005_DigOut_6;
int doWrite_MPNC005_DigOut_6(int value);
int addWrite_MPNC005_DigOut_6(int value);
int getStatus_MPNC005_DigOut_6(void);

#define ID_MPNC005_DigOut_7 228
extern int MPNC005_DigOut_7;
int doWrite_MPNC005_DigOut_7(int value);
int addWrite_MPNC005_DigOut_7(int value);
int getStatus_MPNC005_DigOut_7(void);

#define ID_MPNC005_DigOut_8 229
extern int MPNC005_DigOut_8;
int doWrite_MPNC005_DigOut_8(int value);
int addWrite_MPNC005_DigOut_8(int value);
int getStatus_MPNC005_DigOut_8(void);

#define ID_MPNE05_AnInConf_1 300
extern u_int16_t MPNE05_AnInConf_1;
int doWrite_MPNE05_AnInConf_1(u_int16_t value);
int addWrite_MPNE05_AnInConf_1(u_int16_t value);
int getStatus_MPNE05_AnInConf_1(void);

#define ID_MPNE05_AnInConf_2 301
extern u_int16_t MPNE05_AnInConf_2;
int doWrite_MPNE05_AnInConf_2(u_int16_t value);
int addWrite_MPNE05_AnInConf_2(u_int16_t value);
int getStatus_MPNE05_AnInConf_2(void);

#define ID_MPNE05_AnOutConf_1 302
extern u_int16_t MPNE05_AnOutConf_1;
int doWrite_MPNE05_AnOutConf_1(u_int16_t value);
int addWrite_MPNE05_AnOutConf_1(u_int16_t value);
int getStatus_MPNE05_AnOutConf_1(void);

#define ID_MPNE05_AnOut_1 303
extern int16_t MPNE05_AnOut_1;
int doWrite_MPNE05_AnOut_1(int16_t value);
int addWrite_MPNE05_AnOut_1(int16_t value);
int getStatus_MPNE05_AnOut_1(void);

#define ID_MPNE05_AnInFilter_1 304
extern u_int16_t MPNE05_AnInFilter_1;
int doWrite_MPNE05_AnInFilter_1(u_int16_t value);
int addWrite_MPNE05_AnInFilter_1(u_int16_t value);
int getStatus_MPNE05_AnInFilter_1(void);

#define ID_MPNE05_AnInFilter_2 305
extern u_int16_t MPNE05_AnInFilter_2;
int doWrite_MPNE05_AnInFilter_2(u_int16_t value);
int addWrite_MPNE05_AnInFilter_2(u_int16_t value);
int getStatus_MPNE05_AnInFilter_2(void);

#define ID_MPNE05_AnIn_1 306
extern int16_t MPNE05_AnIn_1;
int doWrite_MPNE05_AnIn_1(int16_t value);
int addWrite_MPNE05_AnIn_1(int16_t value);
int getStatus_MPNE05_AnIn_1(void);

#define ID_MPNE05_AnIn_2 307
extern int16_t MPNE05_AnIn_2;
int doWrite_MPNE05_AnIn_2(int16_t value);
int addWrite_MPNE05_AnIn_2(int16_t value);
int getStatus_MPNE05_AnIn_2(void);

#define ID_MPNE05_AnInOverflow_1 308
extern int MPNE05_AnInOverflow_1;
int doWrite_MPNE05_AnInOverflow_1(int value);
int addWrite_MPNE05_AnInOverflow_1(int value);
int getStatus_MPNE05_AnInOverflow_1(void);

#define ID_MPNE05_AnInOverflow_2 309
extern int MPNE05_AnInOverflow_2;
int doWrite_MPNE05_AnInOverflow_2(int value);
int addWrite_MPNE05_AnInOverflow_2(int value);
int getStatus_MPNE05_AnInOverflow_2(void);

#define ID_MPNE05_AnOutOverflow_1 310
extern int MPNE05_AnOutOverflow_1;
int doWrite_MPNE05_AnOutOverflow_1(int value);
int addWrite_MPNE05_AnOutOverflow_1(int value);
int getStatus_MPNE05_AnOutOverflow_1(void);

#define ID_MPNE05_Tamb 311
extern int16_t MPNE05_Tamb;	/*  Cold Junction Temp. */
int doWrite_MPNE05_Tamb(int16_t value);
int addWrite_MPNE05_Tamb(int16_t value);
int getStatus_MPNE05_Tamb(void);

#define ID_MPNE05_Reserved_1 312
extern u_int16_t MPNE05_Reserved_1;
int doWrite_MPNE05_Reserved_1(u_int16_t value);
int addWrite_MPNE05_Reserved_1(u_int16_t value);
int getStatus_MPNE05_Reserved_1(void);

#define ID_MPNE05_Reserved_2 313
extern u_int16_t MPNE05_Reserved_2;
int doWrite_MPNE05_Reserved_2(u_int16_t value);
int addWrite_MPNE05_Reserved_2(u_int16_t value);
int getStatus_MPNE05_Reserved_2(void);

#define ID_MPNE05_Reserved_3 314
extern u_int16_t MPNE05_Reserved_3;
int doWrite_MPNE05_Reserved_3(u_int16_t value);
int addWrite_MPNE05_Reserved_3(u_int16_t value);
int getStatus_MPNE05_Reserved_3(void);

#define ID_MPNE05_Reserved_4 315
extern u_int16_t MPNE05_Reserved_4;
int doWrite_MPNE05_Reserved_4(u_int16_t value);
int addWrite_MPNE05_Reserved_4(u_int16_t value);
int getStatus_MPNE05_Reserved_4(void);

#define ID_MPNE05_Revision 316
extern u_int16_t MPNE05_Revision;
int doWrite_MPNE05_Revision(u_int16_t value);
int addWrite_MPNE05_Revision(u_int16_t value);
int getStatus_MPNE05_Revision(void);

#define ID_MPNE05_Heartbeat 317
extern u_int16_t MPNE05_Heartbeat;
int doWrite_MPNE05_Heartbeat(u_int16_t value);
int addWrite_MPNE05_Heartbeat(u_int16_t value);
int getStatus_MPNE05_Heartbeat(void);

#define ID_TEST_COMMAND 4013
extern u_int16_t TEST_COMMAND;
int doWrite_TEST_COMMAND(u_int16_t value);
int addWrite_TEST_COMMAND(u_int16_t value);
int getStatus_TEST_COMMAND(void);

#define ID_TST_DigIn_1 4014
extern int TST_DigIn_1;
int doWrite_TST_DigIn_1(int value);
int addWrite_TST_DigIn_1(int value);
int getStatus_TST_DigIn_1(void);

#define ID_TST_DigIn_2 4015
extern int TST_DigIn_2;
int doWrite_TST_DigIn_2(int value);
int addWrite_TST_DigIn_2(int value);
int getStatus_TST_DigIn_2(void);

#define ID_TST_DigIn_3 4016
extern int TST_DigIn_3;
int doWrite_TST_DigIn_3(int value);
int addWrite_TST_DigIn_3(int value);
int getStatus_TST_DigIn_3(void);

#define ID_TST_DigIn_4 4017
extern int TST_DigIn_4;
int doWrite_TST_DigIn_4(int value);
int addWrite_TST_DigIn_4(int value);
int getStatus_TST_DigIn_4(void);

#define ID_TST_DigIn_5 4018
extern int TST_DigIn_5;
int doWrite_TST_DigIn_5(int value);
int addWrite_TST_DigIn_5(int value);
int getStatus_TST_DigIn_5(void);

#define ID_TST_DigIn_6 4019
extern int TST_DigIn_6;
int doWrite_TST_DigIn_6(int value);
int addWrite_TST_DigIn_6(int value);
int getStatus_TST_DigIn_6(void);

#define ID_TST_DigIn_7 4020
extern int TST_DigIn_7;
int doWrite_TST_DigIn_7(int value);
int addWrite_TST_DigIn_7(int value);
int getStatus_TST_DigIn_7(void);

#define ID_TST_DigIn_8 4021
extern int TST_DigIn_8;
int doWrite_TST_DigIn_8(int value);
int addWrite_TST_DigIn_8(int value);
int getStatus_TST_DigIn_8(void);

#define ID_TST_DigIn_9 4022
extern int TST_DigIn_9;
int doWrite_TST_DigIn_9(int value);
int addWrite_TST_DigIn_9(int value);
int getStatus_TST_DigIn_9(void);

#define ID_TST_DigIn_10 4023
extern int TST_DigIn_10;
int doWrite_TST_DigIn_10(int value);
int addWrite_TST_DigIn_10(int value);
int getStatus_TST_DigIn_10(void);

#define ID_TST_DigIn_11 4024
extern int TST_DigIn_11;
int doWrite_TST_DigIn_11(int value);
int addWrite_TST_DigIn_11(int value);
int getStatus_TST_DigIn_11(void);

#define ID_TST_DigIn_12 4025
extern int TST_DigIn_12;
int doWrite_TST_DigIn_12(int value);
int addWrite_TST_DigIn_12(int value);
int getStatus_TST_DigIn_12(void);

#define ID_TST_DigIn_13 4026
extern int TST_DigIn_13;
int doWrite_TST_DigIn_13(int value);
int addWrite_TST_DigIn_13(int value);
int getStatus_TST_DigIn_13(void);

#define ID_TST_DigIn_14 4027
extern int TST_DigIn_14;
int doWrite_TST_DigIn_14(int value);
int addWrite_TST_DigIn_14(int value);
int getStatus_TST_DigIn_14(void);

#define ID_TST_DigIn_15 4028
extern int TST_DigIn_15;
int doWrite_TST_DigIn_15(int value);
int addWrite_TST_DigIn_15(int value);
int getStatus_TST_DigIn_15(void);

#define ID_TST_DigIn_16 4029
extern int TST_DigIn_16;
int doWrite_TST_DigIn_16(int value);
int addWrite_TST_DigIn_16(int value);
int getStatus_TST_DigIn_16(void);

#define ID_VAL_DigIn_1 4030
extern int VAL_DigIn_1;
int doWrite_VAL_DigIn_1(int value);
int addWrite_VAL_DigIn_1(int value);
int getStatus_VAL_DigIn_1(void);

#define ID_VAL_DigIn_2 4031
extern int VAL_DigIn_2;
int doWrite_VAL_DigIn_2(int value);
int addWrite_VAL_DigIn_2(int value);
int getStatus_VAL_DigIn_2(void);

#define ID_VAL_DigIn_3 4032
extern int VAL_DigIn_3;
int doWrite_VAL_DigIn_3(int value);
int addWrite_VAL_DigIn_3(int value);
int getStatus_VAL_DigIn_3(void);

#define ID_VAL_DigIn_4 4033
extern int VAL_DigIn_4;
int doWrite_VAL_DigIn_4(int value);
int addWrite_VAL_DigIn_4(int value);
int getStatus_VAL_DigIn_4(void);

#define ID_VAL_DigIn_5 4034
extern int VAL_DigIn_5;
int doWrite_VAL_DigIn_5(int value);
int addWrite_VAL_DigIn_5(int value);
int getStatus_VAL_DigIn_5(void);

#define ID_VAL_DigIn_6 4035
extern int VAL_DigIn_6;
int doWrite_VAL_DigIn_6(int value);
int addWrite_VAL_DigIn_6(int value);
int getStatus_VAL_DigIn_6(void);

#define ID_VAL_DigIn_7 4036
extern int VAL_DigIn_7;
int doWrite_VAL_DigIn_7(int value);
int addWrite_VAL_DigIn_7(int value);
int getStatus_VAL_DigIn_7(void);

#define ID_VAL_DigIn_8 4037
extern int VAL_DigIn_8;
int doWrite_VAL_DigIn_8(int value);
int addWrite_VAL_DigIn_8(int value);
int getStatus_VAL_DigIn_8(void);

#define ID_VAL_DigIn_9 4038
extern int VAL_DigIn_9;
int doWrite_VAL_DigIn_9(int value);
int addWrite_VAL_DigIn_9(int value);
int getStatus_VAL_DigIn_9(void);

#define ID_VAL_DigIn_10 4039
extern int VAL_DigIn_10;
int doWrite_VAL_DigIn_10(int value);
int addWrite_VAL_DigIn_10(int value);
int getStatus_VAL_DigIn_10(void);

#define ID_VAL_DigIn_11 4040
extern int VAL_DigIn_11;
int doWrite_VAL_DigIn_11(int value);
int addWrite_VAL_DigIn_11(int value);
int getStatus_VAL_DigIn_11(void);

#define ID_VAL_DigIn_12 4041
extern int VAL_DigIn_12;
int doWrite_VAL_DigIn_12(int value);
int addWrite_VAL_DigIn_12(int value);
int getStatus_VAL_DigIn_12(void);

#define ID_VAL_DigIn_13 4042
extern int VAL_DigIn_13;
int doWrite_VAL_DigIn_13(int value);
int addWrite_VAL_DigIn_13(int value);
int getStatus_VAL_DigIn_13(void);

#define ID_VAL_DigIn_14 4043
extern int VAL_DigIn_14;
int doWrite_VAL_DigIn_14(int value);
int addWrite_VAL_DigIn_14(int value);
int getStatus_VAL_DigIn_14(void);

#define ID_VAL_DigIn_15 4044
extern int VAL_DigIn_15;
int doWrite_VAL_DigIn_15(int value);
int addWrite_VAL_DigIn_15(int value);
int getStatus_VAL_DigIn_15(void);

#define ID_VAL_DigIn_16 4045
extern int VAL_DigIn_16;
int doWrite_VAL_DigIn_16(int value);
int addWrite_VAL_DigIn_16(int value);
int getStatus_VAL_DigIn_16(void);

#define ID_RES_DigIn_1 4046
extern int RES_DigIn_1;
int doWrite_RES_DigIn_1(int value);
int addWrite_RES_DigIn_1(int value);
int getStatus_RES_DigIn_1(void);

#define ID_RES_DigIn_2 4047
extern int RES_DigIn_2;
int doWrite_RES_DigIn_2(int value);
int addWrite_RES_DigIn_2(int value);
int getStatus_RES_DigIn_2(void);

#define ID_RES_DigIn_3 4048
extern int RES_DigIn_3;
int doWrite_RES_DigIn_3(int value);
int addWrite_RES_DigIn_3(int value);
int getStatus_RES_DigIn_3(void);

#define ID_RES_DigIn_4 4049
extern int RES_DigIn_4;
int doWrite_RES_DigIn_4(int value);
int addWrite_RES_DigIn_4(int value);
int getStatus_RES_DigIn_4(void);

#define ID_RES_DigIn_5 4050
extern int RES_DigIn_5;
int doWrite_RES_DigIn_5(int value);
int addWrite_RES_DigIn_5(int value);
int getStatus_RES_DigIn_5(void);

#define ID_RES_DigIn_6 4051
extern int RES_DigIn_6;
int doWrite_RES_DigIn_6(int value);
int addWrite_RES_DigIn_6(int value);
int getStatus_RES_DigIn_6(void);

#define ID_RES_DigIn_7 4052
extern int RES_DigIn_7;
int doWrite_RES_DigIn_7(int value);
int addWrite_RES_DigIn_7(int value);
int getStatus_RES_DigIn_7(void);

#define ID_RES_DigIn_8 4053
extern int RES_DigIn_8;
int doWrite_RES_DigIn_8(int value);
int addWrite_RES_DigIn_8(int value);
int getStatus_RES_DigIn_8(void);

#define ID_RES_DigIn_9 4054
extern int RES_DigIn_9;
int doWrite_RES_DigIn_9(int value);
int addWrite_RES_DigIn_9(int value);
int getStatus_RES_DigIn_9(void);

#define ID_RES_DigIn_10 4055
extern int RES_DigIn_10;
int doWrite_RES_DigIn_10(int value);
int addWrite_RES_DigIn_10(int value);
int getStatus_RES_DigIn_10(void);

#define ID_RES_DigIn_11 4056
extern int RES_DigIn_11;
int doWrite_RES_DigIn_11(int value);
int addWrite_RES_DigIn_11(int value);
int getStatus_RES_DigIn_11(void);

#define ID_RES_DigIn_12 4057
extern int RES_DigIn_12;
int doWrite_RES_DigIn_12(int value);
int addWrite_RES_DigIn_12(int value);
int getStatus_RES_DigIn_12(void);

#define ID_RES_DigIn_13 4058
extern int RES_DigIn_13;
int doWrite_RES_DigIn_13(int value);
int addWrite_RES_DigIn_13(int value);
int getStatus_RES_DigIn_13(void);

#define ID_RES_DigIn_14 4059
extern int RES_DigIn_14;
int doWrite_RES_DigIn_14(int value);
int addWrite_RES_DigIn_14(int value);
int getStatus_RES_DigIn_14(void);

#define ID_RES_DigIn_15 4060
extern int RES_DigIn_15;
int doWrite_RES_DigIn_15(int value);
int addWrite_RES_DigIn_15(int value);
int getStatus_RES_DigIn_15(void);

#define ID_RES_DigIn_16 4061
extern int RES_DigIn_16;
int doWrite_RES_DigIn_16(int value);
int addWrite_RES_DigIn_16(int value);
int getStatus_RES_DigIn_16(void);

#define ID_TST_DigOut_1 4062
extern int TST_DigOut_1;
int doWrite_TST_DigOut_1(int value);
int addWrite_TST_DigOut_1(int value);
int getStatus_TST_DigOut_1(void);

#define ID_TST_DigOut_2 4063
extern int TST_DigOut_2;
int doWrite_TST_DigOut_2(int value);
int addWrite_TST_DigOut_2(int value);
int getStatus_TST_DigOut_2(void);

#define ID_TST_DigOut_3 4064
extern int TST_DigOut_3;
int doWrite_TST_DigOut_3(int value);
int addWrite_TST_DigOut_3(int value);
int getStatus_TST_DigOut_3(void);

#define ID_TST_DigOut_4 4065
extern int TST_DigOut_4;
int doWrite_TST_DigOut_4(int value);
int addWrite_TST_DigOut_4(int value);
int getStatus_TST_DigOut_4(void);

#define ID_TST_DigOut_5 4066
extern int TST_DigOut_5;
int doWrite_TST_DigOut_5(int value);
int addWrite_TST_DigOut_5(int value);
int getStatus_TST_DigOut_5(void);

#define ID_TST_DigOut_6 4067
extern int TST_DigOut_6;
int doWrite_TST_DigOut_6(int value);
int addWrite_TST_DigOut_6(int value);
int getStatus_TST_DigOut_6(void);

#define ID_TST_DigOut_7 4068
extern int TST_DigOut_7;
int doWrite_TST_DigOut_7(int value);
int addWrite_TST_DigOut_7(int value);
int getStatus_TST_DigOut_7(void);

#define ID_TST_DigOut_8 4069
extern int TST_DigOut_8;
int doWrite_TST_DigOut_8(int value);
int addWrite_TST_DigOut_8(int value);
int getStatus_TST_DigOut_8(void);

#define ID_TST_DigOut_9 4070
extern int TST_DigOut_9;
int doWrite_TST_DigOut_9(int value);
int addWrite_TST_DigOut_9(int value);
int getStatus_TST_DigOut_9(void);

#define ID_TST_DigOut_10 4071
extern int TST_DigOut_10;
int doWrite_TST_DigOut_10(int value);
int addWrite_TST_DigOut_10(int value);
int getStatus_TST_DigOut_10(void);

#define ID_TST_DigOut_11 4072
extern int TST_DigOut_11;
int doWrite_TST_DigOut_11(int value);
int addWrite_TST_DigOut_11(int value);
int getStatus_TST_DigOut_11(void);

#define ID_TST_DigOut_12 4073
extern int TST_DigOut_12;
int doWrite_TST_DigOut_12(int value);
int addWrite_TST_DigOut_12(int value);
int getStatus_TST_DigOut_12(void);

#define ID_TST_DigOut_13 4074
extern int TST_DigOut_13;
int doWrite_TST_DigOut_13(int value);
int addWrite_TST_DigOut_13(int value);
int getStatus_TST_DigOut_13(void);

#define ID_TST_DigOut_14 4075
extern int TST_DigOut_14;
int doWrite_TST_DigOut_14(int value);
int addWrite_TST_DigOut_14(int value);
int getStatus_TST_DigOut_14(void);

#define ID_TST_DigOut_15 4076
extern int TST_DigOut_15;
int doWrite_TST_DigOut_15(int value);
int addWrite_TST_DigOut_15(int value);
int getStatus_TST_DigOut_15(void);

#define ID_TST_DigOut_16 4077
extern int TST_DigOut_16;
int doWrite_TST_DigOut_16(int value);
int addWrite_TST_DigOut_16(int value);
int getStatus_TST_DigOut_16(void);

#define ID_VAL_DigOut_1 4078
extern int VAL_DigOut_1;
int doWrite_VAL_DigOut_1(int value);
int addWrite_VAL_DigOut_1(int value);
int getStatus_VAL_DigOut_1(void);

#define ID_VAL_DigOut_2 4079
extern int VAL_DigOut_2;
int doWrite_VAL_DigOut_2(int value);
int addWrite_VAL_DigOut_2(int value);
int getStatus_VAL_DigOut_2(void);

#define ID_VAL_DigOut_3 4080
extern int VAL_DigOut_3;
int doWrite_VAL_DigOut_3(int value);
int addWrite_VAL_DigOut_3(int value);
int getStatus_VAL_DigOut_3(void);

#define ID_VAL_DigOut_4 4081
extern int VAL_DigOut_4;
int doWrite_VAL_DigOut_4(int value);
int addWrite_VAL_DigOut_4(int value);
int getStatus_VAL_DigOut_4(void);

#define ID_VAL_DigOut_5 4082
extern int VAL_DigOut_5;
int doWrite_VAL_DigOut_5(int value);
int addWrite_VAL_DigOut_5(int value);
int getStatus_VAL_DigOut_5(void);

#define ID_VAL_DigOut_6 4083
extern int VAL_DigOut_6;
int doWrite_VAL_DigOut_6(int value);
int addWrite_VAL_DigOut_6(int value);
int getStatus_VAL_DigOut_6(void);

#define ID_VAL_DigOut_7 4084
extern int VAL_DigOut_7;
int doWrite_VAL_DigOut_7(int value);
int addWrite_VAL_DigOut_7(int value);
int getStatus_VAL_DigOut_7(void);

#define ID_VAL_DigOut_8 4085
extern int VAL_DigOut_8;
int doWrite_VAL_DigOut_8(int value);
int addWrite_VAL_DigOut_8(int value);
int getStatus_VAL_DigOut_8(void);

#define ID_VAL_DigOut_9 4086
extern int VAL_DigOut_9;
int doWrite_VAL_DigOut_9(int value);
int addWrite_VAL_DigOut_9(int value);
int getStatus_VAL_DigOut_9(void);

#define ID_VAL_DigOut_10 4087
extern int VAL_DigOut_10;
int doWrite_VAL_DigOut_10(int value);
int addWrite_VAL_DigOut_10(int value);
int getStatus_VAL_DigOut_10(void);

#define ID_VAL_DigOut_11 4088
extern int VAL_DigOut_11;
int doWrite_VAL_DigOut_11(int value);
int addWrite_VAL_DigOut_11(int value);
int getStatus_VAL_DigOut_11(void);

#define ID_VAL_DigOut_12 4089
extern int VAL_DigOut_12;
int doWrite_VAL_DigOut_12(int value);
int addWrite_VAL_DigOut_12(int value);
int getStatus_VAL_DigOut_12(void);

#define ID_VAL_DigOut_13 4090
extern int VAL_DigOut_13;
int doWrite_VAL_DigOut_13(int value);
int addWrite_VAL_DigOut_13(int value);
int getStatus_VAL_DigOut_13(void);

#define ID_VAL_DigOut_14 4091
extern int VAL_DigOut_14;
int doWrite_VAL_DigOut_14(int value);
int addWrite_VAL_DigOut_14(int value);
int getStatus_VAL_DigOut_14(void);

#define ID_VAL_DigOut_15 4092
extern int VAL_DigOut_15;
int doWrite_VAL_DigOut_15(int value);
int addWrite_VAL_DigOut_15(int value);
int getStatus_VAL_DigOut_15(void);

#define ID_VAL_DigOut_16 4093
extern int VAL_DigOut_16;
int doWrite_VAL_DigOut_16(int value);
int addWrite_VAL_DigOut_16(int value);
int getStatus_VAL_DigOut_16(void);

#define ID_TST_AnIn_1 4094
extern int TST_AnIn_1;
int doWrite_TST_AnIn_1(int value);
int addWrite_TST_AnIn_1(int value);
int getStatus_TST_AnIn_1(void);

#define ID_TST_AnIn_2 4095
extern int TST_AnIn_2;
int doWrite_TST_AnIn_2(int value);
int addWrite_TST_AnIn_2(int value);
int getStatus_TST_AnIn_2(void);

#define ID_TST_AnIn_3 4096
extern int TST_AnIn_3;
int doWrite_TST_AnIn_3(int value);
int addWrite_TST_AnIn_3(int value);
int getStatus_TST_AnIn_3(void);

#define ID_TST_AnIn_4 4097
extern int TST_AnIn_4;
int doWrite_TST_AnIn_4(int value);
int addWrite_TST_AnIn_4(int value);
int getStatus_TST_AnIn_4(void);

#define ID_TST_AnIn_5 4098
extern int TST_AnIn_5;
int doWrite_TST_AnIn_5(int value);
int addWrite_TST_AnIn_5(int value);
int getStatus_TST_AnIn_5(void);

#define ID_TST_AnIn_6 4099
extern int TST_AnIn_6;
int doWrite_TST_AnIn_6(int value);
int addWrite_TST_AnIn_6(int value);
int getStatus_TST_AnIn_6(void);

#define ID_TST_AnIn_7 4100
extern int TST_AnIn_7;
int doWrite_TST_AnIn_7(int value);
int addWrite_TST_AnIn_7(int value);
int getStatus_TST_AnIn_7(void);

#define ID_TST_AnIn_8 4101
extern int TST_AnIn_8;
int doWrite_TST_AnIn_8(int value);
int addWrite_TST_AnIn_8(int value);
int getStatus_TST_AnIn_8(void);

#define ID_TST_AnIn_9 4102
extern int TST_AnIn_9;
int doWrite_TST_AnIn_9(int value);
int addWrite_TST_AnIn_9(int value);
int getStatus_TST_AnIn_9(void);

#define ID_TST_AnIn_10 4103
extern int TST_AnIn_10;
int doWrite_TST_AnIn_10(int value);
int addWrite_TST_AnIn_10(int value);
int getStatus_TST_AnIn_10(void);

#define ID_TST_AnIn_11 4104
extern int TST_AnIn_11;
int doWrite_TST_AnIn_11(int value);
int addWrite_TST_AnIn_11(int value);
int getStatus_TST_AnIn_11(void);

#define ID_TST_AnIn_12 4105
extern int TST_AnIn_12;
int doWrite_TST_AnIn_12(int value);
int addWrite_TST_AnIn_12(int value);
int getStatus_TST_AnIn_12(void);

#define ID_VAL_AnIn_1 4106
extern int16_t VAL_AnIn_1;
int doWrite_VAL_AnIn_1(int16_t value);
int addWrite_VAL_AnIn_1(int16_t value);
int getStatus_VAL_AnIn_1(void);

#define ID_VAL_AnIn_2 4107
extern int16_t VAL_AnIn_2;
int doWrite_VAL_AnIn_2(int16_t value);
int addWrite_VAL_AnIn_2(int16_t value);
int getStatus_VAL_AnIn_2(void);

#define ID_VAL_AnIn_3 4108
extern int16_t VAL_AnIn_3;
int doWrite_VAL_AnIn_3(int16_t value);
int addWrite_VAL_AnIn_3(int16_t value);
int getStatus_VAL_AnIn_3(void);

#define ID_VAL_AnIn_4 4109
extern int16_t VAL_AnIn_4;
int doWrite_VAL_AnIn_4(int16_t value);
int addWrite_VAL_AnIn_4(int16_t value);
int getStatus_VAL_AnIn_4(void);

#define ID_VAL_AnIn_5 4110
extern int16_t VAL_AnIn_5;
int doWrite_VAL_AnIn_5(int16_t value);
int addWrite_VAL_AnIn_5(int16_t value);
int getStatus_VAL_AnIn_5(void);

#define ID_VAL_AnIn_6 4111
extern int16_t VAL_AnIn_6;
int doWrite_VAL_AnIn_6(int16_t value);
int addWrite_VAL_AnIn_6(int16_t value);
int getStatus_VAL_AnIn_6(void);

#define ID_VAL_AnIn_7 4112
extern int16_t VAL_AnIn_7;
int doWrite_VAL_AnIn_7(int16_t value);
int addWrite_VAL_AnIn_7(int16_t value);
int getStatus_VAL_AnIn_7(void);

#define ID_VAL_AnIn_8 4113
extern int16_t VAL_AnIn_8;
int doWrite_VAL_AnIn_8(int16_t value);
int addWrite_VAL_AnIn_8(int16_t value);
int getStatus_VAL_AnIn_8(void);

#define ID_VAL_AnIn_9 4114
extern int16_t VAL_AnIn_9;
int doWrite_VAL_AnIn_9(int16_t value);
int addWrite_VAL_AnIn_9(int16_t value);
int getStatus_VAL_AnIn_9(void);

#define ID_VAL_AnIn_10 4115
extern int16_t VAL_AnIn_10;
int doWrite_VAL_AnIn_10(int16_t value);
int addWrite_VAL_AnIn_10(int16_t value);
int getStatus_VAL_AnIn_10(void);

#define ID_VAL_AnIn_11 4116
extern int16_t VAL_AnIn_11;
int doWrite_VAL_AnIn_11(int16_t value);
int addWrite_VAL_AnIn_11(int16_t value);
int getStatus_VAL_AnIn_11(void);

#define ID_VAL_AnIn_12 4117
extern int16_t VAL_AnIn_12;
int doWrite_VAL_AnIn_12(int16_t value);
int addWrite_VAL_AnIn_12(int16_t value);
int getStatus_VAL_AnIn_12(void);

#define ID_VAL_AnInConf_1 4118
extern u_int16_t VAL_AnInConf_1;
int doWrite_VAL_AnInConf_1(u_int16_t value);
int addWrite_VAL_AnInConf_1(u_int16_t value);
int getStatus_VAL_AnInConf_1(void);

#define ID_VAL_AnInConf_2 4119
extern u_int16_t VAL_AnInConf_2;
int doWrite_VAL_AnInConf_2(u_int16_t value);
int addWrite_VAL_AnInConf_2(u_int16_t value);
int getStatus_VAL_AnInConf_2(void);

#define ID_VAL_AnInConf_3 4120
extern u_int16_t VAL_AnInConf_3;
int doWrite_VAL_AnInConf_3(u_int16_t value);
int addWrite_VAL_AnInConf_3(u_int16_t value);
int getStatus_VAL_AnInConf_3(void);

#define ID_VAL_AnInConf_4 4121
extern u_int16_t VAL_AnInConf_4;
int doWrite_VAL_AnInConf_4(u_int16_t value);
int addWrite_VAL_AnInConf_4(u_int16_t value);
int getStatus_VAL_AnInConf_4(void);

#define ID_VAL_AnInConf_5 4122
extern u_int16_t VAL_AnInConf_5;
int doWrite_VAL_AnInConf_5(u_int16_t value);
int addWrite_VAL_AnInConf_5(u_int16_t value);
int getStatus_VAL_AnInConf_5(void);

#define ID_VAL_AnInConf_6 4123
extern u_int16_t VAL_AnInConf_6;
int doWrite_VAL_AnInConf_6(u_int16_t value);
int addWrite_VAL_AnInConf_6(u_int16_t value);
int getStatus_VAL_AnInConf_6(void);

#define ID_VAL_AnInConf_7 4124
extern u_int16_t VAL_AnInConf_7;
int doWrite_VAL_AnInConf_7(u_int16_t value);
int addWrite_VAL_AnInConf_7(u_int16_t value);
int getStatus_VAL_AnInConf_7(void);

#define ID_VAL_AnInConf_8 4125
extern u_int16_t VAL_AnInConf_8;
int doWrite_VAL_AnInConf_8(u_int16_t value);
int addWrite_VAL_AnInConf_8(u_int16_t value);
int getStatus_VAL_AnInConf_8(void);

#define ID_VAL_AnInConf_9 4126
extern u_int16_t VAL_AnInConf_9;
int doWrite_VAL_AnInConf_9(u_int16_t value);
int addWrite_VAL_AnInConf_9(u_int16_t value);
int getStatus_VAL_AnInConf_9(void);

#define ID_VAL_AnInConf_10 4127
extern u_int16_t VAL_AnInConf_10;
int doWrite_VAL_AnInConf_10(u_int16_t value);
int addWrite_VAL_AnInConf_10(u_int16_t value);
int getStatus_VAL_AnInConf_10(void);

#define ID_VAL_AnInConf_11 4128
extern u_int16_t VAL_AnInConf_11;
int doWrite_VAL_AnInConf_11(u_int16_t value);
int addWrite_VAL_AnInConf_11(u_int16_t value);
int getStatus_VAL_AnInConf_11(void);

#define ID_VAL_AnInConf_12 4129
extern u_int16_t VAL_AnInConf_12;
int doWrite_VAL_AnInConf_12(u_int16_t value);
int addWrite_VAL_AnInConf_12(u_int16_t value);
int getStatus_VAL_AnInConf_12(void);

#define ID_VAL_AnInFltr_1 4130
extern u_int16_t VAL_AnInFltr_1;
int doWrite_VAL_AnInFltr_1(u_int16_t value);
int addWrite_VAL_AnInFltr_1(u_int16_t value);
int getStatus_VAL_AnInFltr_1(void);

#define ID_VAL_AnInFltr_2 4131
extern u_int16_t VAL_AnInFltr_2;
int doWrite_VAL_AnInFltr_2(u_int16_t value);
int addWrite_VAL_AnInFltr_2(u_int16_t value);
int getStatus_VAL_AnInFltr_2(void);

#define ID_VAL_AnInFltr_3 4132
extern u_int16_t VAL_AnInFltr_3;
int doWrite_VAL_AnInFltr_3(u_int16_t value);
int addWrite_VAL_AnInFltr_3(u_int16_t value);
int getStatus_VAL_AnInFltr_3(void);

#define ID_VAL_AnInFltr_4 4133
extern u_int16_t VAL_AnInFltr_4;
int doWrite_VAL_AnInFltr_4(u_int16_t value);
int addWrite_VAL_AnInFltr_4(u_int16_t value);
int getStatus_VAL_AnInFltr_4(void);

#define ID_VAL_AnInFltr_5 4134
extern u_int16_t VAL_AnInFltr_5;
int doWrite_VAL_AnInFltr_5(u_int16_t value);
int addWrite_VAL_AnInFltr_5(u_int16_t value);
int getStatus_VAL_AnInFltr_5(void);

#define ID_VAL_AnInFltr_6 4135
extern u_int16_t VAL_AnInFltr_6;
int doWrite_VAL_AnInFltr_6(u_int16_t value);
int addWrite_VAL_AnInFltr_6(u_int16_t value);
int getStatus_VAL_AnInFltr_6(void);

#define ID_VAL_AnInFltr_7 4136
extern u_int16_t VAL_AnInFltr_7;
int doWrite_VAL_AnInFltr_7(u_int16_t value);
int addWrite_VAL_AnInFltr_7(u_int16_t value);
int getStatus_VAL_AnInFltr_7(void);

#define ID_VAL_AnInFltr_8 4137
extern u_int16_t VAL_AnInFltr_8;
int doWrite_VAL_AnInFltr_8(u_int16_t value);
int addWrite_VAL_AnInFltr_8(u_int16_t value);
int getStatus_VAL_AnInFltr_8(void);

#define ID_VAL_AnInFltr_9 4138
extern u_int16_t VAL_AnInFltr_9;
int doWrite_VAL_AnInFltr_9(u_int16_t value);
int addWrite_VAL_AnInFltr_9(u_int16_t value);
int getStatus_VAL_AnInFltr_9(void);

#define ID_VAL_AnInFltr_10 4139
extern u_int16_t VAL_AnInFltr_10;
int doWrite_VAL_AnInFltr_10(u_int16_t value);
int addWrite_VAL_AnInFltr_10(u_int16_t value);
int getStatus_VAL_AnInFltr_10(void);

#define ID_VAL_AnInFltr_11 4140
extern u_int16_t VAL_AnInFltr_11;
int doWrite_VAL_AnInFltr_11(u_int16_t value);
int addWrite_VAL_AnInFltr_11(u_int16_t value);
int getStatus_VAL_AnInFltr_11(void);

#define ID_VAL_AnInFltr_12 4141
extern u_int16_t VAL_AnInFltr_12;
int doWrite_VAL_AnInFltr_12(u_int16_t value);
int addWrite_VAL_AnInFltr_12(u_int16_t value);
int getStatus_VAL_AnInFltr_12(void);

#define ID_RES_AnIn_1 4142
extern int16_t RES_AnIn_1;
int doWrite_RES_AnIn_1(int16_t value);
int addWrite_RES_AnIn_1(int16_t value);
int getStatus_RES_AnIn_1(void);

#define ID_RES_AnIn_2 4143
extern int16_t RES_AnIn_2;
int doWrite_RES_AnIn_2(int16_t value);
int addWrite_RES_AnIn_2(int16_t value);
int getStatus_RES_AnIn_2(void);

#define ID_RES_AnIn_3 4144
extern int16_t RES_AnIn_3;
int doWrite_RES_AnIn_3(int16_t value);
int addWrite_RES_AnIn_3(int16_t value);
int getStatus_RES_AnIn_3(void);

#define ID_RES_AnIn_4 4145
extern int16_t RES_AnIn_4;
int doWrite_RES_AnIn_4(int16_t value);
int addWrite_RES_AnIn_4(int16_t value);
int getStatus_RES_AnIn_4(void);

#define ID_RES_AnIn_5 4146
extern int16_t RES_AnIn_5;
int doWrite_RES_AnIn_5(int16_t value);
int addWrite_RES_AnIn_5(int16_t value);
int getStatus_RES_AnIn_5(void);

#define ID_RES_AnIn_6 4147
extern int16_t RES_AnIn_6;
int doWrite_RES_AnIn_6(int16_t value);
int addWrite_RES_AnIn_6(int16_t value);
int getStatus_RES_AnIn_6(void);

#define ID_RES_AnIn_7 4148
extern int16_t RES_AnIn_7;
int doWrite_RES_AnIn_7(int16_t value);
int addWrite_RES_AnIn_7(int16_t value);
int getStatus_RES_AnIn_7(void);

#define ID_RES_AnIn_8 4149
extern int16_t RES_AnIn_8;
int doWrite_RES_AnIn_8(int16_t value);
int addWrite_RES_AnIn_8(int16_t value);
int getStatus_RES_AnIn_8(void);

#define ID_RES_AnIn_9 4150
extern int16_t RES_AnIn_9;
int doWrite_RES_AnIn_9(int16_t value);
int addWrite_RES_AnIn_9(int16_t value);
int getStatus_RES_AnIn_9(void);

#define ID_RES_AnIn_10 4151
extern int16_t RES_AnIn_10;
int doWrite_RES_AnIn_10(int16_t value);
int addWrite_RES_AnIn_10(int16_t value);
int getStatus_RES_AnIn_10(void);

#define ID_RES_AnIn_11 4152
extern int16_t RES_AnIn_11;
int doWrite_RES_AnIn_11(int16_t value);
int addWrite_RES_AnIn_11(int16_t value);
int getStatus_RES_AnIn_11(void);

#define ID_RES_AnIn_12 4153
extern int16_t RES_AnIn_12;
int doWrite_RES_AnIn_12(int16_t value);
int addWrite_RES_AnIn_12(int16_t value);
int getStatus_RES_AnIn_12(void);

#define ID_RES_AnInStts_1 4154
extern int16_t RES_AnInStts_1;
int doWrite_RES_AnInStts_1(int16_t value);
int addWrite_RES_AnInStts_1(int16_t value);
int getStatus_RES_AnInStts_1(void);

#define ID_RES_AnInStts_2 4155
extern int16_t RES_AnInStts_2;
int doWrite_RES_AnInStts_2(int16_t value);
int addWrite_RES_AnInStts_2(int16_t value);
int getStatus_RES_AnInStts_2(void);

#define ID_RES_AnInStts_3 4156
extern int16_t RES_AnInStts_3;
int doWrite_RES_AnInStts_3(int16_t value);
int addWrite_RES_AnInStts_3(int16_t value);
int getStatus_RES_AnInStts_3(void);

#define ID_RES_AnInStts_4 4157
extern int16_t RES_AnInStts_4;
int doWrite_RES_AnInStts_4(int16_t value);
int addWrite_RES_AnInStts_4(int16_t value);
int getStatus_RES_AnInStts_4(void);

#define ID_RES_AnInStts_5 4158
extern int16_t RES_AnInStts_5;
int doWrite_RES_AnInStts_5(int16_t value);
int addWrite_RES_AnInStts_5(int16_t value);
int getStatus_RES_AnInStts_5(void);

#define ID_RES_AnInStts_6 4159
extern int16_t RES_AnInStts_6;
int doWrite_RES_AnInStts_6(int16_t value);
int addWrite_RES_AnInStts_6(int16_t value);
int getStatus_RES_AnInStts_6(void);

#define ID_RES_AnInStts_7 4160
extern int16_t RES_AnInStts_7;
int doWrite_RES_AnInStts_7(int16_t value);
int addWrite_RES_AnInStts_7(int16_t value);
int getStatus_RES_AnInStts_7(void);

#define ID_RES_AnInStts_8 4161
extern int16_t RES_AnInStts_8;
int doWrite_RES_AnInStts_8(int16_t value);
int addWrite_RES_AnInStts_8(int16_t value);
int getStatus_RES_AnInStts_8(void);

#define ID_RES_AnInStts_9 4162
extern int16_t RES_AnInStts_9;
int doWrite_RES_AnInStts_9(int16_t value);
int addWrite_RES_AnInStts_9(int16_t value);
int getStatus_RES_AnInStts_9(void);

#define ID_RES_AnInStts_10 4163
extern int16_t RES_AnInStts_10;
int doWrite_RES_AnInStts_10(int16_t value);
int addWrite_RES_AnInStts_10(int16_t value);
int getStatus_RES_AnInStts_10(void);

#define ID_RES_AnInStts_11 4164
extern int16_t RES_AnInStts_11;
int doWrite_RES_AnInStts_11(int16_t value);
int addWrite_RES_AnInStts_11(int16_t value);
int getStatus_RES_AnInStts_11(void);

#define ID_RES_AnInStts_12 4165
extern int16_t RES_AnInStts_12;
int doWrite_RES_AnInStts_12(int16_t value);
int addWrite_RES_AnInStts_12(int16_t value);
int getStatus_RES_AnInStts_12(void);

#define ID_TST_AnOut_1 4166
extern int TST_AnOut_1;
int doWrite_TST_AnOut_1(int value);
int addWrite_TST_AnOut_1(int value);
int getStatus_TST_AnOut_1(void);

#define ID_TST_AnOut_2 4167
extern int TST_AnOut_2;
int doWrite_TST_AnOut_2(int value);
int addWrite_TST_AnOut_2(int value);
int getStatus_TST_AnOut_2(void);

#define ID_TST_AnOut_3 4168
extern int TST_AnOut_3;
int doWrite_TST_AnOut_3(int value);
int addWrite_TST_AnOut_3(int value);
int getStatus_TST_AnOut_3(void);

#define ID_TST_AnOut_4 4169
extern int TST_AnOut_4;
int doWrite_TST_AnOut_4(int value);
int addWrite_TST_AnOut_4(int value);
int getStatus_TST_AnOut_4(void);

#define ID_VAL_AnOut_1 4170
extern int16_t VAL_AnOut_1;
int doWrite_VAL_AnOut_1(int16_t value);
int addWrite_VAL_AnOut_1(int16_t value);
int getStatus_VAL_AnOut_1(void);

#define ID_VAL_AnOut_2 4171
extern int16_t VAL_AnOut_2;
int doWrite_VAL_AnOut_2(int16_t value);
int addWrite_VAL_AnOut_2(int16_t value);
int getStatus_VAL_AnOut_2(void);

#define ID_VAL_AnOut_3 4172
extern int16_t VAL_AnOut_3;
int doWrite_VAL_AnOut_3(int16_t value);
int addWrite_VAL_AnOut_3(int16_t value);
int getStatus_VAL_AnOut_3(void);

#define ID_VAL_AnOut_4 4173
extern int16_t VAL_AnOut_4;
int doWrite_VAL_AnOut_4(int16_t value);
int addWrite_VAL_AnOut_4(int16_t value);
int getStatus_VAL_AnOut_4(void);

#define ID_VAL_AnOutConf_1 4174
extern u_int16_t VAL_AnOutConf_1;
int doWrite_VAL_AnOutConf_1(u_int16_t value);
int addWrite_VAL_AnOutConf_1(u_int16_t value);
int getStatus_VAL_AnOutConf_1(void);

#define ID_VAL_AnOutConf_2 4175
extern u_int16_t VAL_AnOutConf_2;
int doWrite_VAL_AnOutConf_2(u_int16_t value);
int addWrite_VAL_AnOutConf_2(u_int16_t value);
int getStatus_VAL_AnOutConf_2(void);

#define ID_VAL_AnOutConf_3 4176
extern u_int16_t VAL_AnOutConf_3;
int doWrite_VAL_AnOutConf_3(u_int16_t value);
int addWrite_VAL_AnOutConf_3(u_int16_t value);
int getStatus_VAL_AnOutConf_3(void);

#define ID_VAL_AnOutConf_4 4177
extern u_int16_t VAL_AnOutConf_4;
int doWrite_VAL_AnOutConf_4(u_int16_t value);
int addWrite_VAL_AnOutConf_4(u_int16_t value);
int getStatus_VAL_AnOutConf_4(void);

#define ID_RES_AnOutStts_1 4178
extern int16_t RES_AnOutStts_1;
int doWrite_RES_AnOutStts_1(int16_t value);
int addWrite_RES_AnOutStts_1(int16_t value);
int getStatus_RES_AnOutStts_1(void);

#define ID_RES_AnOutStts_2 4179
extern int16_t RES_AnOutStts_2;
int doWrite_RES_AnOutStts_2(int16_t value);
int addWrite_RES_AnOutStts_2(int16_t value);
int getStatus_RES_AnOutStts_2(void);

#define ID_RES_AnOutStts_3 4180
extern int16_t RES_AnOutStts_3;
int doWrite_RES_AnOutStts_3(int16_t value);
int addWrite_RES_AnOutStts_3(int16_t value);
int getStatus_RES_AnOutStts_3(void);

#define ID_RES_AnOutStts_4 4181
extern int16_t RES_AnOutStts_4;
int doWrite_RES_AnOutStts_4(int16_t value);
int addWrite_RES_AnOutStts_4(int16_t value);
int getStatus_RES_AnOutStts_4(void);

#define ID_TST_Tamb 4182
extern int TST_Tamb;
int doWrite_TST_Tamb(int value);
int addWrite_TST_Tamb(int value);
int getStatus_TST_Tamb(void);

#define ID_TST_RPM 4183
extern int TST_RPM;
int doWrite_TST_RPM(int value);
int addWrite_TST_RPM(int value);
int getStatus_TST_RPM(void);

#define ID_TST_FWrevision 4184
extern int TST_FWrevision;
int doWrite_TST_FWrevision(int value);
int addWrite_TST_FWrevision(int value);
int getStatus_TST_FWrevision(void);

#define ID_TST_HWconfig 4185
extern int TST_HWconfig;
int doWrite_TST_HWconfig(int value);
int addWrite_TST_HWconfig(int value);
int getStatus_TST_HWconfig(void);

#define ID_VAL_Tamb 4186
extern int16_t VAL_Tamb;
int doWrite_VAL_Tamb(int16_t value);
int addWrite_VAL_Tamb(int16_t value);
int getStatus_VAL_Tamb(void);

#define ID_VAL_RPM 4187
extern u_int16_t VAL_RPM;
int doWrite_VAL_RPM(u_int16_t value);
int addWrite_VAL_RPM(u_int16_t value);
int getStatus_VAL_RPM(void);

#define ID_VAL_FWrevision 4188
extern u_int16_t VAL_FWrevision;
int doWrite_VAL_FWrevision(u_int16_t value);
int addWrite_VAL_FWrevision(u_int16_t value);
int getStatus_VAL_FWrevision(void);

#define ID_VAL_HWconfig 4189
extern u_int16_t VAL_HWconfig;
int doWrite_VAL_HWconfig(u_int16_t value);
int addWrite_VAL_HWconfig(u_int16_t value);
int getStatus_VAL_HWconfig(void);

#define ID_RES_Tamb 4190
extern int16_t RES_Tamb;
int doWrite_RES_Tamb(int16_t value);
int addWrite_RES_Tamb(int16_t value);
int getStatus_RES_Tamb(void);

#define ID_RES_RPM 4191
extern u_int16_t RES_RPM;
int doWrite_RES_RPM(u_int16_t value);
int addWrite_RES_RPM(u_int16_t value);
int getStatus_RES_RPM(void);

#define ID_RES_FWrevision 4192
extern u_int16_t RES_FWrevision;
int doWrite_RES_FWrevision(u_int16_t value);
int addWrite_RES_FWrevision(u_int16_t value);
int getStatus_RES_FWrevision(void);

#define ID_RES_HWconfig 4193
extern u_int16_t RES_HWconfig;
int doWrite_RES_HWconfig(u_int16_t value);
int addWrite_RES_HWconfig(u_int16_t value);
int getStatus_RES_HWconfig(void);

#define ID_TST_RTUS_WR 4194
extern int TST_RTUS_WR;
int doWrite_TST_RTUS_WR(int value);
int addWrite_TST_RTUS_WR(int value);
int getStatus_TST_RTUS_WR(void);

#define ID_TST_RTUS_RD 4195
extern int TST_RTUS_RD;
int doWrite_TST_RTUS_RD(int value);
int addWrite_TST_RTUS_RD(int value);
int getStatus_TST_RTUS_RD(void);

#define ID_TST_RTU1_WR 4196
extern int TST_RTU1_WR;
int doWrite_TST_RTU1_WR(int value);
int addWrite_TST_RTU1_WR(int value);
int getStatus_TST_RTU1_WR(void);

#define ID_TST_RTU1_RD 4197
extern int TST_RTU1_RD;
int doWrite_TST_RTU1_RD(int value);
int addWrite_TST_RTU1_RD(int value);
int getStatus_TST_RTU1_RD(void);

#define ID_TST_RTU3_WR 4198
extern int TST_RTU3_WR;
int doWrite_TST_RTU3_WR(int value);
int addWrite_TST_RTU3_WR(int value);
int getStatus_TST_RTU3_WR(void);

#define ID_TST_RTU3_RD 4199
extern int TST_RTU3_RD;
int doWrite_TST_RTU3_RD(int value);
int addWrite_TST_RTU3_RD(int value);
int getStatus_TST_RTU3_RD(void);

#define ID_TST_CAN1_WR 4200
extern int TST_CAN1_WR;
int doWrite_TST_CAN1_WR(int value);
int addWrite_TST_CAN1_WR(int value);
int getStatus_TST_CAN1_WR(void);

#define ID_TST_CAN1_RD 4201
extern int TST_CAN1_RD;
int doWrite_TST_CAN1_RD(int value);
int addWrite_TST_CAN1_RD(int value);
int getStatus_TST_CAN1_RD(void);

#define ID_VAL_RTUS_WR 4202
extern int VAL_RTUS_WR;
int doWrite_VAL_RTUS_WR(int value);
int addWrite_VAL_RTUS_WR(int value);
int getStatus_VAL_RTUS_WR(void);

#define ID_VAL_RTUS_RD 4203
extern int VAL_RTUS_RD;
int doWrite_VAL_RTUS_RD(int value);
int addWrite_VAL_RTUS_RD(int value);
int getStatus_VAL_RTUS_RD(void);

#define ID_VAL_RTU1_WR 4204
extern int VAL_RTU1_WR;
int doWrite_VAL_RTU1_WR(int value);
int addWrite_VAL_RTU1_WR(int value);
int getStatus_VAL_RTU1_WR(void);

#define ID_VAL_RTU1_RD 4205
extern int VAL_RTU1_RD;
int doWrite_VAL_RTU1_RD(int value);
int addWrite_VAL_RTU1_RD(int value);
int getStatus_VAL_RTU1_RD(void);

#define ID_VAL_RTU3_WR 4206
extern int VAL_RTU3_WR;
int doWrite_VAL_RTU3_WR(int value);
int addWrite_VAL_RTU3_WR(int value);
int getStatus_VAL_RTU3_WR(void);

#define ID_VAL_RTU3_RD 4207
extern int VAL_RTU3_RD;
int doWrite_VAL_RTU3_RD(int value);
int addWrite_VAL_RTU3_RD(int value);
int getStatus_VAL_RTU3_RD(void);

#define ID_VAL_CAN1_WR 4208
extern int VAL_CAN1_WR;
int doWrite_VAL_CAN1_WR(int value);
int addWrite_VAL_CAN1_WR(int value);
int getStatus_VAL_CAN1_WR(void);

#define ID_VAL_CAN1_RD 4209
extern int VAL_CAN1_RD;
int doWrite_VAL_CAN1_RD(int value);
int addWrite_VAL_CAN1_RD(int value);
int getStatus_VAL_CAN1_RD(void);

#define ID_RES_RTUS_WR 4210
extern int RES_RTUS_WR;
int doWrite_RES_RTUS_WR(int value);
int addWrite_RES_RTUS_WR(int value);
int getStatus_RES_RTUS_WR(void);

#define ID_RES_RTUS_RD 4211
extern int RES_RTUS_RD;
int doWrite_RES_RTUS_RD(int value);
int addWrite_RES_RTUS_RD(int value);
int getStatus_RES_RTUS_RD(void);

#define ID_RES_RTU1_WR 4212
extern int RES_RTU1_WR;
int doWrite_RES_RTU1_WR(int value);
int addWrite_RES_RTU1_WR(int value);
int getStatus_RES_RTU1_WR(void);

#define ID_RES_RTU1_RD 4213
extern int RES_RTU1_RD;
int doWrite_RES_RTU1_RD(int value);
int addWrite_RES_RTU1_RD(int value);
int getStatus_RES_RTU1_RD(void);

#define ID_RES_RTU3_WR 4214
extern int RES_RTU3_WR;
int doWrite_RES_RTU3_WR(int value);
int addWrite_RES_RTU3_WR(int value);
int getStatus_RES_RTU3_WR(void);

#define ID_RES_RTU3_RD 4215
extern int RES_RTU3_RD;
int doWrite_RES_RTU3_RD(int value);
int addWrite_RES_RTU3_RD(int value);
int getStatus_RES_RTU3_RD(void);

#define ID_RES_CAN1_WR 4216
extern int RES_CAN1_WR;
int doWrite_RES_CAN1_WR(int value);
int addWrite_RES_CAN1_WR(int value);
int getStatus_RES_CAN1_WR(void);

#define ID_RES_CAN1_RD 4217
extern int RES_CAN1_RD;
int doWrite_RES_CAN1_RD(int value);
int addWrite_RES_CAN1_RD(int value);
int getStatus_RES_CAN1_RD(void);

#define ID_TEST_STATUS 4218
extern u_int16_t TEST_STATUS;
int doWrite_TEST_STATUS(u_int16_t value);
int addWrite_TEST_STATUS(u_int16_t value);
int getStatus_TEST_STATUS(void);

#define ID_RTU0_TYPE_PORT 5000
extern u_int32_t RTU0_TYPE_PORT;
int doWrite_RTU0_TYPE_PORT(u_int32_t value);
int addWrite_RTU0_TYPE_PORT(u_int32_t value);
int getStatus_RTU0_TYPE_PORT(void);

#define ID_RTU0_BAUDRATE 5001
extern u_int32_t RTU0_BAUDRATE;
int doWrite_RTU0_BAUDRATE(u_int32_t value);
int addWrite_RTU0_BAUDRATE(u_int32_t value);
int getStatus_RTU0_BAUDRATE(void);

#define ID_RTU0_STATUS 5002
extern u_int32_t RTU0_STATUS;
int doWrite_RTU0_STATUS(u_int32_t value);
int addWrite_RTU0_STATUS(u_int32_t value);
int getStatus_RTU0_STATUS(void);

#define ID_RTU0_READS 5003
extern u_int32_t RTU0_READS;
int doWrite_RTU0_READS(u_int32_t value);
int addWrite_RTU0_READS(u_int32_t value);
int getStatus_RTU0_READS(void);

#define ID_RTU0_WRITES 5004
extern u_int32_t RTU0_WRITES;
int doWrite_RTU0_WRITES(u_int32_t value);
int addWrite_RTU0_WRITES(u_int32_t value);
int getStatus_RTU0_WRITES(void);

#define ID_RTU0_TIMEOUTS 5005
extern u_int32_t RTU0_TIMEOUTS;
int doWrite_RTU0_TIMEOUTS(u_int32_t value);
int addWrite_RTU0_TIMEOUTS(u_int32_t value);
int getStatus_RTU0_TIMEOUTS(void);

#define ID_RTU0_COMM_ERRORS 5006
extern u_int32_t RTU0_COMM_ERRORS;
int doWrite_RTU0_COMM_ERRORS(u_int32_t value);
int addWrite_RTU0_COMM_ERRORS(u_int32_t value);
int getStatus_RTU0_COMM_ERRORS(void);

#define ID_RTU0_LAST_ERROR 5007
extern u_int32_t RTU0_LAST_ERROR;
int doWrite_RTU0_LAST_ERROR(u_int32_t value);
int addWrite_RTU0_LAST_ERROR(u_int32_t value);
int getStatus_RTU0_LAST_ERROR(void);

#define ID_RTU0_WRITE_QUEUE 5008
extern u_int32_t RTU0_WRITE_QUEUE;
int doWrite_RTU0_WRITE_QUEUE(u_int32_t value);
int addWrite_RTU0_WRITE_QUEUE(u_int32_t value);
int getStatus_RTU0_WRITE_QUEUE(void);

#define ID_RTU0_BUS_LOAD 5009
extern u_int32_t RTU0_BUS_LOAD;
int doWrite_RTU0_BUS_LOAD(u_int32_t value);
int addWrite_RTU0_BUS_LOAD(u_int32_t value);
int getStatus_RTU0_BUS_LOAD(void);

#define ID_RTU2_TYPE_PORT 5010
extern u_int32_t RTU2_TYPE_PORT;
int doWrite_RTU2_TYPE_PORT(u_int32_t value);
int addWrite_RTU2_TYPE_PORT(u_int32_t value);
int getStatus_RTU2_TYPE_PORT(void);

#define ID_RTU2_BAUDRATE 5011
extern u_int32_t RTU2_BAUDRATE;
int doWrite_RTU2_BAUDRATE(u_int32_t value);
int addWrite_RTU2_BAUDRATE(u_int32_t value);
int getStatus_RTU2_BAUDRATE(void);

#define ID_RTU2_STATUS 5012
extern u_int32_t RTU2_STATUS;
int doWrite_RTU2_STATUS(u_int32_t value);
int addWrite_RTU2_STATUS(u_int32_t value);
int getStatus_RTU2_STATUS(void);

#define ID_RTU2_READS 5013
extern u_int32_t RTU2_READS;
int doWrite_RTU2_READS(u_int32_t value);
int addWrite_RTU2_READS(u_int32_t value);
int getStatus_RTU2_READS(void);

#define ID_RTU2_WRITES 5014
extern u_int32_t RTU2_WRITES;
int doWrite_RTU2_WRITES(u_int32_t value);
int addWrite_RTU2_WRITES(u_int32_t value);
int getStatus_RTU2_WRITES(void);

#define ID_RTU2_TIMEOUTS 5015
extern u_int32_t RTU2_TIMEOUTS;
int doWrite_RTU2_TIMEOUTS(u_int32_t value);
int addWrite_RTU2_TIMEOUTS(u_int32_t value);
int getStatus_RTU2_TIMEOUTS(void);

#define ID_RTU2_COMM_ERRORS 5016
extern u_int32_t RTU2_COMM_ERRORS;
int doWrite_RTU2_COMM_ERRORS(u_int32_t value);
int addWrite_RTU2_COMM_ERRORS(u_int32_t value);
int getStatus_RTU2_COMM_ERRORS(void);

#define ID_RTU2_LAST_ERROR 5017
extern u_int32_t RTU2_LAST_ERROR;
int doWrite_RTU2_LAST_ERROR(u_int32_t value);
int addWrite_RTU2_LAST_ERROR(u_int32_t value);
int getStatus_RTU2_LAST_ERROR(void);

#define ID_RTU2_WRITE_QUEUE 5018
extern u_int32_t RTU2_WRITE_QUEUE;
int doWrite_RTU2_WRITE_QUEUE(u_int32_t value);
int addWrite_RTU2_WRITE_QUEUE(u_int32_t value);
int getStatus_RTU2_WRITE_QUEUE(void);

#define ID_RTU2_BUS_LOAD 5019
extern u_int32_t RTU2_BUS_LOAD;
int doWrite_RTU2_BUS_LOAD(u_int32_t value);
int addWrite_RTU2_BUS_LOAD(u_int32_t value);
int getStatus_RTU2_BUS_LOAD(void);

#define ID_RTU3_TYPE_PORT 5020
extern u_int32_t RTU3_TYPE_PORT;
int doWrite_RTU3_TYPE_PORT(u_int32_t value);
int addWrite_RTU3_TYPE_PORT(u_int32_t value);
int getStatus_RTU3_TYPE_PORT(void);

#define ID_RTU3_BAUDRATE 5021
extern u_int32_t RTU3_BAUDRATE;
int doWrite_RTU3_BAUDRATE(u_int32_t value);
int addWrite_RTU3_BAUDRATE(u_int32_t value);
int getStatus_RTU3_BAUDRATE(void);

#define ID_RTU3_STATUS 5022
extern u_int32_t RTU3_STATUS;
int doWrite_RTU3_STATUS(u_int32_t value);
int addWrite_RTU3_STATUS(u_int32_t value);
int getStatus_RTU3_STATUS(void);

#define ID_RTU3_READS 5023
extern u_int32_t RTU3_READS;
int doWrite_RTU3_READS(u_int32_t value);
int addWrite_RTU3_READS(u_int32_t value);
int getStatus_RTU3_READS(void);

#define ID_RTU3_WRITES 5024
extern u_int32_t RTU3_WRITES;
int doWrite_RTU3_WRITES(u_int32_t value);
int addWrite_RTU3_WRITES(u_int32_t value);
int getStatus_RTU3_WRITES(void);

#define ID_RTU3_TIMEOUTS 5025
extern u_int32_t RTU3_TIMEOUTS;
int doWrite_RTU3_TIMEOUTS(u_int32_t value);
int addWrite_RTU3_TIMEOUTS(u_int32_t value);
int getStatus_RTU3_TIMEOUTS(void);

#define ID_RTU3_COMM_ERRORS 5026
extern u_int32_t RTU3_COMM_ERRORS;
int doWrite_RTU3_COMM_ERRORS(u_int32_t value);
int addWrite_RTU3_COMM_ERRORS(u_int32_t value);
int getStatus_RTU3_COMM_ERRORS(void);

#define ID_RTU3_LAST_ERROR 5027
extern u_int32_t RTU3_LAST_ERROR;
int doWrite_RTU3_LAST_ERROR(u_int32_t value);
int addWrite_RTU3_LAST_ERROR(u_int32_t value);
int getStatus_RTU3_LAST_ERROR(void);

#define ID_RTU3_WRITE_QUEUE 5028
extern u_int32_t RTU3_WRITE_QUEUE;
int doWrite_RTU3_WRITE_QUEUE(u_int32_t value);
int addWrite_RTU3_WRITE_QUEUE(u_int32_t value);
int getStatus_RTU3_WRITE_QUEUE(void);

#define ID_RTU3_BUS_LOAD 5029
extern u_int32_t RTU3_BUS_LOAD;
int doWrite_RTU3_BUS_LOAD(u_int32_t value);
int addWrite_RTU3_BUS_LOAD(u_int32_t value);
int getStatus_RTU3_BUS_LOAD(void);

#define ID_CAN0_TYPE_PORT 5030
extern u_int32_t CAN0_TYPE_PORT;
int doWrite_CAN0_TYPE_PORT(u_int32_t value);
int addWrite_CAN0_TYPE_PORT(u_int32_t value);
int getStatus_CAN0_TYPE_PORT(void);

#define ID_CAN0_BAUDRATE 5031
extern u_int32_t CAN0_BAUDRATE;
int doWrite_CAN0_BAUDRATE(u_int32_t value);
int addWrite_CAN0_BAUDRATE(u_int32_t value);
int getStatus_CAN0_BAUDRATE(void);

#define ID_CAN0_STATUS 5032
extern u_int32_t CAN0_STATUS;
int doWrite_CAN0_STATUS(u_int32_t value);
int addWrite_CAN0_STATUS(u_int32_t value);
int getStatus_CAN0_STATUS(void);

#define ID_CAN0_READS 5033
extern u_int32_t CAN0_READS;
int doWrite_CAN0_READS(u_int32_t value);
int addWrite_CAN0_READS(u_int32_t value);
int getStatus_CAN0_READS(void);

#define ID_CAN0_WRITES 5034
extern u_int32_t CAN0_WRITES;
int doWrite_CAN0_WRITES(u_int32_t value);
int addWrite_CAN0_WRITES(u_int32_t value);
int getStatus_CAN0_WRITES(void);

#define ID_CAN0_TIMEOUTS 5035
extern u_int32_t CAN0_TIMEOUTS;
int doWrite_CAN0_TIMEOUTS(u_int32_t value);
int addWrite_CAN0_TIMEOUTS(u_int32_t value);
int getStatus_CAN0_TIMEOUTS(void);

#define ID_CAN0_COMM_ERRORS 5036
extern u_int32_t CAN0_COMM_ERRORS;
int doWrite_CAN0_COMM_ERRORS(u_int32_t value);
int addWrite_CAN0_COMM_ERRORS(u_int32_t value);
int getStatus_CAN0_COMM_ERRORS(void);

#define ID_CAN0_LAST_ERROR 5037
extern u_int32_t CAN0_LAST_ERROR;
int doWrite_CAN0_LAST_ERROR(u_int32_t value);
int addWrite_CAN0_LAST_ERROR(u_int32_t value);
int getStatus_CAN0_LAST_ERROR(void);

#define ID_CAN0_WRITE_QUEUE 5038
extern u_int32_t CAN0_WRITE_QUEUE;
int doWrite_CAN0_WRITE_QUEUE(u_int32_t value);
int addWrite_CAN0_WRITE_QUEUE(u_int32_t value);
int getStatus_CAN0_WRITE_QUEUE(void);

#define ID_CAN0_BUS_LOAD 5039
extern u_int32_t CAN0_BUS_LOAD;
int doWrite_CAN0_BUS_LOAD(u_int32_t value);
int addWrite_CAN0_BUS_LOAD(u_int32_t value);
int getStatus_CAN0_BUS_LOAD(void);

#define ID_CAN1_TYPE_PORT 5040
extern u_int32_t CAN1_TYPE_PORT;
int doWrite_CAN1_TYPE_PORT(u_int32_t value);
int addWrite_CAN1_TYPE_PORT(u_int32_t value);
int getStatus_CAN1_TYPE_PORT(void);

#define ID_CAN1_BAUDRATE 5041
extern u_int32_t CAN1_BAUDRATE;
int doWrite_CAN1_BAUDRATE(u_int32_t value);
int addWrite_CAN1_BAUDRATE(u_int32_t value);
int getStatus_CAN1_BAUDRATE(void);

#define ID_CAN1_STATUS 5042
extern u_int32_t CAN1_STATUS;
int doWrite_CAN1_STATUS(u_int32_t value);
int addWrite_CAN1_STATUS(u_int32_t value);
int getStatus_CAN1_STATUS(void);

#define ID_CAN1_READS 5043
extern u_int32_t CAN1_READS;
int doWrite_CAN1_READS(u_int32_t value);
int addWrite_CAN1_READS(u_int32_t value);
int getStatus_CAN1_READS(void);

#define ID_CAN1_WRITES 5044
extern u_int32_t CAN1_WRITES;
int doWrite_CAN1_WRITES(u_int32_t value);
int addWrite_CAN1_WRITES(u_int32_t value);
int getStatus_CAN1_WRITES(void);

#define ID_CAN1_TIMEOUTS 5045
extern u_int32_t CAN1_TIMEOUTS;
int doWrite_CAN1_TIMEOUTS(u_int32_t value);
int addWrite_CAN1_TIMEOUTS(u_int32_t value);
int getStatus_CAN1_TIMEOUTS(void);

#define ID_CAN1_COMM_ERRORS 5046
extern u_int32_t CAN1_COMM_ERRORS;
int doWrite_CAN1_COMM_ERRORS(u_int32_t value);
int addWrite_CAN1_COMM_ERRORS(u_int32_t value);
int getStatus_CAN1_COMM_ERRORS(void);

#define ID_CAN1_LAST_ERROR 5047
extern u_int32_t CAN1_LAST_ERROR;
int doWrite_CAN1_LAST_ERROR(u_int32_t value);
int addWrite_CAN1_LAST_ERROR(u_int32_t value);
int getStatus_CAN1_LAST_ERROR(void);

#define ID_CAN1_WRITE_QUEUE 5048
extern u_int32_t CAN1_WRITE_QUEUE;
int doWrite_CAN1_WRITE_QUEUE(u_int32_t value);
int addWrite_CAN1_WRITE_QUEUE(u_int32_t value);
int getStatus_CAN1_WRITE_QUEUE(void);

#define ID_CAN1_BUS_LOAD 5049
extern u_int32_t CAN1_BUS_LOAD;
int doWrite_CAN1_BUS_LOAD(u_int32_t value);
int addWrite_CAN1_BUS_LOAD(u_int32_t value);
int getStatus_CAN1_BUS_LOAD(void);

#define ID_TCPS_TYPE_PORT 5050
extern u_int32_t TCPS_TYPE_PORT;
int doWrite_TCPS_TYPE_PORT(u_int32_t value);
int addWrite_TCPS_TYPE_PORT(u_int32_t value);
int getStatus_TCPS_TYPE_PORT(void);

#define ID_TCPS_IP_ADDRESS 5051
extern u_int32_t TCPS_IP_ADDRESS;
int doWrite_TCPS_IP_ADDRESS(u_int32_t value);
int addWrite_TCPS_IP_ADDRESS(u_int32_t value);
int getStatus_TCPS_IP_ADDRESS(void);

#define ID_TCPS_STATUS 5052
extern u_int32_t TCPS_STATUS;
int doWrite_TCPS_STATUS(u_int32_t value);
int addWrite_TCPS_STATUS(u_int32_t value);
int getStatus_TCPS_STATUS(void);

#define ID_TCPS_READS 5053
extern u_int32_t TCPS_READS;
int doWrite_TCPS_READS(u_int32_t value);
int addWrite_TCPS_READS(u_int32_t value);
int getStatus_TCPS_READS(void);

#define ID_TCPS_WRITES 5054
extern u_int32_t TCPS_WRITES;
int doWrite_TCPS_WRITES(u_int32_t value);
int addWrite_TCPS_WRITES(u_int32_t value);
int getStatus_TCPS_WRITES(void);

#define ID_TCPS_TIMEOUTS 5055
extern u_int32_t TCPS_TIMEOUTS;
int doWrite_TCPS_TIMEOUTS(u_int32_t value);
int addWrite_TCPS_TIMEOUTS(u_int32_t value);
int getStatus_TCPS_TIMEOUTS(void);

#define ID_TCPS_COMM_ERRORS 5056
extern u_int32_t TCPS_COMM_ERRORS;
int doWrite_TCPS_COMM_ERRORS(u_int32_t value);
int addWrite_TCPS_COMM_ERRORS(u_int32_t value);
int getStatus_TCPS_COMM_ERRORS(void);

#define ID_TCPS_LAST_ERROR 5057
extern u_int32_t TCPS_LAST_ERROR;
int doWrite_TCPS_LAST_ERROR(u_int32_t value);
int addWrite_TCPS_LAST_ERROR(u_int32_t value);
int getStatus_TCPS_LAST_ERROR(void);

#define ID_TCPS_WRITE_QUEUE 5058
extern u_int32_t TCPS_WRITE_QUEUE;
int doWrite_TCPS_WRITE_QUEUE(u_int32_t value);
int addWrite_TCPS_WRITE_QUEUE(u_int32_t value);
int getStatus_TCPS_WRITE_QUEUE(void);

#define ID_TCPS_BUS_LOAD 5059
extern u_int32_t TCPS_BUS_LOAD;
int doWrite_TCPS_BUS_LOAD(u_int32_t value);
int addWrite_TCPS_BUS_LOAD(u_int32_t value);
int getStatus_TCPS_BUS_LOAD(void);

#define ID_TCP0_TYPE_PORT 5060
extern u_int32_t TCP0_TYPE_PORT;
int doWrite_TCP0_TYPE_PORT(u_int32_t value);
int addWrite_TCP0_TYPE_PORT(u_int32_t value);
int getStatus_TCP0_TYPE_PORT(void);

#define ID_TCP0_IP_ADDRESS 5061
extern u_int32_t TCP0_IP_ADDRESS;
int doWrite_TCP0_IP_ADDRESS(u_int32_t value);
int addWrite_TCP0_IP_ADDRESS(u_int32_t value);
int getStatus_TCP0_IP_ADDRESS(void);

#define ID_TCP0_STATUS 5062
extern u_int32_t TCP0_STATUS;
int doWrite_TCP0_STATUS(u_int32_t value);
int addWrite_TCP0_STATUS(u_int32_t value);
int getStatus_TCP0_STATUS(void);

#define ID_TCP0_READS 5063
extern u_int32_t TCP0_READS;
int doWrite_TCP0_READS(u_int32_t value);
int addWrite_TCP0_READS(u_int32_t value);
int getStatus_TCP0_READS(void);

#define ID_TCP0_WRITES 5064
extern u_int32_t TCP0_WRITES;
int doWrite_TCP0_WRITES(u_int32_t value);
int addWrite_TCP0_WRITES(u_int32_t value);
int getStatus_TCP0_WRITES(void);

#define ID_TCP0_TIMEOUTS 5065
extern u_int32_t TCP0_TIMEOUTS;
int doWrite_TCP0_TIMEOUTS(u_int32_t value);
int addWrite_TCP0_TIMEOUTS(u_int32_t value);
int getStatus_TCP0_TIMEOUTS(void);

#define ID_TCP0_COMM_ERRORS 5066
extern u_int32_t TCP0_COMM_ERRORS;
int doWrite_TCP0_COMM_ERRORS(u_int32_t value);
int addWrite_TCP0_COMM_ERRORS(u_int32_t value);
int getStatus_TCP0_COMM_ERRORS(void);

#define ID_TCP0_LAST_ERROR 5067
extern u_int32_t TCP0_LAST_ERROR;
int doWrite_TCP0_LAST_ERROR(u_int32_t value);
int addWrite_TCP0_LAST_ERROR(u_int32_t value);
int getStatus_TCP0_LAST_ERROR(void);

#define ID_TCP0_WRITE_QUEUE 5068
extern u_int32_t TCP0_WRITE_QUEUE;
int doWrite_TCP0_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP0_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP0_WRITE_QUEUE(void);

#define ID_TCP0_BUS_LOAD 5069
extern u_int32_t TCP0_BUS_LOAD;
int doWrite_TCP0_BUS_LOAD(u_int32_t value);
int addWrite_TCP0_BUS_LOAD(u_int32_t value);
int getStatus_TCP0_BUS_LOAD(void);

#define ID_TCP1_TYPE_PORT 5070
extern u_int32_t TCP1_TYPE_PORT;
int doWrite_TCP1_TYPE_PORT(u_int32_t value);
int addWrite_TCP1_TYPE_PORT(u_int32_t value);
int getStatus_TCP1_TYPE_PORT(void);

#define ID_TCP1_IP_ADDRESS 5071
extern u_int32_t TCP1_IP_ADDRESS;
int doWrite_TCP1_IP_ADDRESS(u_int32_t value);
int addWrite_TCP1_IP_ADDRESS(u_int32_t value);
int getStatus_TCP1_IP_ADDRESS(void);

#define ID_TCP1_STATUS 5072
extern u_int32_t TCP1_STATUS;
int doWrite_TCP1_STATUS(u_int32_t value);
int addWrite_TCP1_STATUS(u_int32_t value);
int getStatus_TCP1_STATUS(void);

#define ID_TCP1_READS 5073
extern u_int32_t TCP1_READS;
int doWrite_TCP1_READS(u_int32_t value);
int addWrite_TCP1_READS(u_int32_t value);
int getStatus_TCP1_READS(void);

#define ID_TCP1_WRITES 5074
extern u_int32_t TCP1_WRITES;
int doWrite_TCP1_WRITES(u_int32_t value);
int addWrite_TCP1_WRITES(u_int32_t value);
int getStatus_TCP1_WRITES(void);

#define ID_TCP1_TIMEOUTS 5075
extern u_int32_t TCP1_TIMEOUTS;
int doWrite_TCP1_TIMEOUTS(u_int32_t value);
int addWrite_TCP1_TIMEOUTS(u_int32_t value);
int getStatus_TCP1_TIMEOUTS(void);

#define ID_TCP1_COMM_ERRORS 5076
extern u_int32_t TCP1_COMM_ERRORS;
int doWrite_TCP1_COMM_ERRORS(u_int32_t value);
int addWrite_TCP1_COMM_ERRORS(u_int32_t value);
int getStatus_TCP1_COMM_ERRORS(void);

#define ID_TCP1_LAST_ERROR 5077
extern u_int32_t TCP1_LAST_ERROR;
int doWrite_TCP1_LAST_ERROR(u_int32_t value);
int addWrite_TCP1_LAST_ERROR(u_int32_t value);
int getStatus_TCP1_LAST_ERROR(void);

#define ID_TCP1_WRITE_QUEUE 5078
extern u_int32_t TCP1_WRITE_QUEUE;
int doWrite_TCP1_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP1_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP1_WRITE_QUEUE(void);

#define ID_TCP1_BUS_LOAD 5079
extern u_int32_t TCP1_BUS_LOAD;
int doWrite_TCP1_BUS_LOAD(u_int32_t value);
int addWrite_TCP1_BUS_LOAD(u_int32_t value);
int getStatus_TCP1_BUS_LOAD(void);

#define ID_TCP2_TYPE_PORT 5080
extern u_int32_t TCP2_TYPE_PORT;
int doWrite_TCP2_TYPE_PORT(u_int32_t value);
int addWrite_TCP2_TYPE_PORT(u_int32_t value);
int getStatus_TCP2_TYPE_PORT(void);

#define ID_TCP2_IP_ADDRESS 5081
extern u_int32_t TCP2_IP_ADDRESS;
int doWrite_TCP2_IP_ADDRESS(u_int32_t value);
int addWrite_TCP2_IP_ADDRESS(u_int32_t value);
int getStatus_TCP2_IP_ADDRESS(void);

#define ID_TCP2_STATUS 5082
extern u_int32_t TCP2_STATUS;
int doWrite_TCP2_STATUS(u_int32_t value);
int addWrite_TCP2_STATUS(u_int32_t value);
int getStatus_TCP2_STATUS(void);

#define ID_TCP2_READS 5083
extern u_int32_t TCP2_READS;
int doWrite_TCP2_READS(u_int32_t value);
int addWrite_TCP2_READS(u_int32_t value);
int getStatus_TCP2_READS(void);

#define ID_TCP2_WRITES 5084
extern u_int32_t TCP2_WRITES;
int doWrite_TCP2_WRITES(u_int32_t value);
int addWrite_TCP2_WRITES(u_int32_t value);
int getStatus_TCP2_WRITES(void);

#define ID_TCP2_TIMEOUTS 5085
extern u_int32_t TCP2_TIMEOUTS;
int doWrite_TCP2_TIMEOUTS(u_int32_t value);
int addWrite_TCP2_TIMEOUTS(u_int32_t value);
int getStatus_TCP2_TIMEOUTS(void);

#define ID_TCP2_COMM_ERRORS 5086
extern u_int32_t TCP2_COMM_ERRORS;
int doWrite_TCP2_COMM_ERRORS(u_int32_t value);
int addWrite_TCP2_COMM_ERRORS(u_int32_t value);
int getStatus_TCP2_COMM_ERRORS(void);

#define ID_TCP2_LAST_ERROR 5087
extern u_int32_t TCP2_LAST_ERROR;
int doWrite_TCP2_LAST_ERROR(u_int32_t value);
int addWrite_TCP2_LAST_ERROR(u_int32_t value);
int getStatus_TCP2_LAST_ERROR(void);

#define ID_TCP2_WRITE_QUEUE 5088
extern u_int32_t TCP2_WRITE_QUEUE;
int doWrite_TCP2_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP2_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP2_WRITE_QUEUE(void);

#define ID_TCP2_BUS_LOAD 5089
extern u_int32_t TCP2_BUS_LOAD;
int doWrite_TCP2_BUS_LOAD(u_int32_t value);
int addWrite_TCP2_BUS_LOAD(u_int32_t value);
int getStatus_TCP2_BUS_LOAD(void);

#define ID_TCP3_TYPE_PORT 5090
extern u_int32_t TCP3_TYPE_PORT;
int doWrite_TCP3_TYPE_PORT(u_int32_t value);
int addWrite_TCP3_TYPE_PORT(u_int32_t value);
int getStatus_TCP3_TYPE_PORT(void);

#define ID_TCP3_IP_ADDRESS 5091
extern u_int32_t TCP3_IP_ADDRESS;
int doWrite_TCP3_IP_ADDRESS(u_int32_t value);
int addWrite_TCP3_IP_ADDRESS(u_int32_t value);
int getStatus_TCP3_IP_ADDRESS(void);

#define ID_TCP3_STATUS 5092
extern u_int32_t TCP3_STATUS;
int doWrite_TCP3_STATUS(u_int32_t value);
int addWrite_TCP3_STATUS(u_int32_t value);
int getStatus_TCP3_STATUS(void);

#define ID_TCP3_READS 5093
extern u_int32_t TCP3_READS;
int doWrite_TCP3_READS(u_int32_t value);
int addWrite_TCP3_READS(u_int32_t value);
int getStatus_TCP3_READS(void);

#define ID_TCP3_WRITES 5094
extern u_int32_t TCP3_WRITES;
int doWrite_TCP3_WRITES(u_int32_t value);
int addWrite_TCP3_WRITES(u_int32_t value);
int getStatus_TCP3_WRITES(void);

#define ID_TCP3_TIMEOUTS 5095
extern u_int32_t TCP3_TIMEOUTS;
int doWrite_TCP3_TIMEOUTS(u_int32_t value);
int addWrite_TCP3_TIMEOUTS(u_int32_t value);
int getStatus_TCP3_TIMEOUTS(void);

#define ID_TCP3_COMM_ERRORS 5096
extern u_int32_t TCP3_COMM_ERRORS;
int doWrite_TCP3_COMM_ERRORS(u_int32_t value);
int addWrite_TCP3_COMM_ERRORS(u_int32_t value);
int getStatus_TCP3_COMM_ERRORS(void);

#define ID_TCP3_LAST_ERROR 5097
extern u_int32_t TCP3_LAST_ERROR;
int doWrite_TCP3_LAST_ERROR(u_int32_t value);
int addWrite_TCP3_LAST_ERROR(u_int32_t value);
int getStatus_TCP3_LAST_ERROR(void);

#define ID_TCP3_WRITE_QUEUE 5098
extern u_int32_t TCP3_WRITE_QUEUE;
int doWrite_TCP3_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP3_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP3_WRITE_QUEUE(void);

#define ID_TCP3_BUS_LOAD 5099
extern u_int32_t TCP3_BUS_LOAD;
int doWrite_TCP3_BUS_LOAD(u_int32_t value);
int addWrite_TCP3_BUS_LOAD(u_int32_t value);
int getStatus_TCP3_BUS_LOAD(void);

#define ID_TCP4_TYPE_PORT 5100
extern u_int32_t TCP4_TYPE_PORT;
int doWrite_TCP4_TYPE_PORT(u_int32_t value);
int addWrite_TCP4_TYPE_PORT(u_int32_t value);
int getStatus_TCP4_TYPE_PORT(void);

#define ID_TCP4_IP_ADDRESS 5101
extern u_int32_t TCP4_IP_ADDRESS;
int doWrite_TCP4_IP_ADDRESS(u_int32_t value);
int addWrite_TCP4_IP_ADDRESS(u_int32_t value);
int getStatus_TCP4_IP_ADDRESS(void);

#define ID_TCP4_STATUS 5102
extern u_int32_t TCP4_STATUS;
int doWrite_TCP4_STATUS(u_int32_t value);
int addWrite_TCP4_STATUS(u_int32_t value);
int getStatus_TCP4_STATUS(void);

#define ID_TCP4_READS 5103
extern u_int32_t TCP4_READS;
int doWrite_TCP4_READS(u_int32_t value);
int addWrite_TCP4_READS(u_int32_t value);
int getStatus_TCP4_READS(void);

#define ID_TCP4_WRITES 5104
extern u_int32_t TCP4_WRITES;
int doWrite_TCP4_WRITES(u_int32_t value);
int addWrite_TCP4_WRITES(u_int32_t value);
int getStatus_TCP4_WRITES(void);

#define ID_TCP4_TIMEOUTS 5105
extern u_int32_t TCP4_TIMEOUTS;
int doWrite_TCP4_TIMEOUTS(u_int32_t value);
int addWrite_TCP4_TIMEOUTS(u_int32_t value);
int getStatus_TCP4_TIMEOUTS(void);

#define ID_TCP4_COMM_ERRORS 5106
extern u_int32_t TCP4_COMM_ERRORS;
int doWrite_TCP4_COMM_ERRORS(u_int32_t value);
int addWrite_TCP4_COMM_ERRORS(u_int32_t value);
int getStatus_TCP4_COMM_ERRORS(void);

#define ID_TCP4_LAST_ERROR 5107
extern u_int32_t TCP4_LAST_ERROR;
int doWrite_TCP4_LAST_ERROR(u_int32_t value);
int addWrite_TCP4_LAST_ERROR(u_int32_t value);
int getStatus_TCP4_LAST_ERROR(void);

#define ID_TCP4_WRITE_QUEUE 5108
extern u_int32_t TCP4_WRITE_QUEUE;
int doWrite_TCP4_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP4_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP4_WRITE_QUEUE(void);

#define ID_TCP4_BUS_LOAD 5109
extern u_int32_t TCP4_BUS_LOAD;
int doWrite_TCP4_BUS_LOAD(u_int32_t value);
int addWrite_TCP4_BUS_LOAD(u_int32_t value);
int getStatus_TCP4_BUS_LOAD(void);

#define ID_TCP5_TYPE_PORT 5110
extern u_int32_t TCP5_TYPE_PORT;
int doWrite_TCP5_TYPE_PORT(u_int32_t value);
int addWrite_TCP5_TYPE_PORT(u_int32_t value);
int getStatus_TCP5_TYPE_PORT(void);

#define ID_TCP5_IP_ADDRESS 5111
extern u_int32_t TCP5_IP_ADDRESS;
int doWrite_TCP5_IP_ADDRESS(u_int32_t value);
int addWrite_TCP5_IP_ADDRESS(u_int32_t value);
int getStatus_TCP5_IP_ADDRESS(void);

#define ID_TCP5_STATUS 5112
extern u_int32_t TCP5_STATUS;
int doWrite_TCP5_STATUS(u_int32_t value);
int addWrite_TCP5_STATUS(u_int32_t value);
int getStatus_TCP5_STATUS(void);

#define ID_TCP5_READS 5113
extern u_int32_t TCP5_READS;
int doWrite_TCP5_READS(u_int32_t value);
int addWrite_TCP5_READS(u_int32_t value);
int getStatus_TCP5_READS(void);

#define ID_TCP5_WRITES 5114
extern u_int32_t TCP5_WRITES;
int doWrite_TCP5_WRITES(u_int32_t value);
int addWrite_TCP5_WRITES(u_int32_t value);
int getStatus_TCP5_WRITES(void);

#define ID_TCP5_TIMEOUTS 5115
extern u_int32_t TCP5_TIMEOUTS;
int doWrite_TCP5_TIMEOUTS(u_int32_t value);
int addWrite_TCP5_TIMEOUTS(u_int32_t value);
int getStatus_TCP5_TIMEOUTS(void);

#define ID_TCP5_COMM_ERRORS 5116
extern u_int32_t TCP5_COMM_ERRORS;
int doWrite_TCP5_COMM_ERRORS(u_int32_t value);
int addWrite_TCP5_COMM_ERRORS(u_int32_t value);
int getStatus_TCP5_COMM_ERRORS(void);

#define ID_TCP5_LAST_ERROR 5117
extern u_int32_t TCP5_LAST_ERROR;
int doWrite_TCP5_LAST_ERROR(u_int32_t value);
int addWrite_TCP5_LAST_ERROR(u_int32_t value);
int getStatus_TCP5_LAST_ERROR(void);

#define ID_TCP5_WRITE_QUEUE 5118
extern u_int32_t TCP5_WRITE_QUEUE;
int doWrite_TCP5_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP5_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP5_WRITE_QUEUE(void);

#define ID_TCP5_BUS_LOAD 5119
extern u_int32_t TCP5_BUS_LOAD;
int doWrite_TCP5_BUS_LOAD(u_int32_t value);
int addWrite_TCP5_BUS_LOAD(u_int32_t value);
int getStatus_TCP5_BUS_LOAD(void);

#define ID_TCP6_TYPE_PORT 5120
extern u_int32_t TCP6_TYPE_PORT;
int doWrite_TCP6_TYPE_PORT(u_int32_t value);
int addWrite_TCP6_TYPE_PORT(u_int32_t value);
int getStatus_TCP6_TYPE_PORT(void);

#define ID_TCP6_IP_ADDRESS 5121
extern u_int32_t TCP6_IP_ADDRESS;
int doWrite_TCP6_IP_ADDRESS(u_int32_t value);
int addWrite_TCP6_IP_ADDRESS(u_int32_t value);
int getStatus_TCP6_IP_ADDRESS(void);

#define ID_TCP6_STATUS 5122
extern u_int32_t TCP6_STATUS;
int doWrite_TCP6_STATUS(u_int32_t value);
int addWrite_TCP6_STATUS(u_int32_t value);
int getStatus_TCP6_STATUS(void);

#define ID_TCP6_READS 5123
extern u_int32_t TCP6_READS;
int doWrite_TCP6_READS(u_int32_t value);
int addWrite_TCP6_READS(u_int32_t value);
int getStatus_TCP6_READS(void);

#define ID_TCP6_WRITES 5124
extern u_int32_t TCP6_WRITES;
int doWrite_TCP6_WRITES(u_int32_t value);
int addWrite_TCP6_WRITES(u_int32_t value);
int getStatus_TCP6_WRITES(void);

#define ID_TCP6_TIMEOUTS 5125
extern u_int32_t TCP6_TIMEOUTS;
int doWrite_TCP6_TIMEOUTS(u_int32_t value);
int addWrite_TCP6_TIMEOUTS(u_int32_t value);
int getStatus_TCP6_TIMEOUTS(void);

#define ID_TCP6_COMM_ERRORS 5126
extern u_int32_t TCP6_COMM_ERRORS;
int doWrite_TCP6_COMM_ERRORS(u_int32_t value);
int addWrite_TCP6_COMM_ERRORS(u_int32_t value);
int getStatus_TCP6_COMM_ERRORS(void);

#define ID_TCP6_LAST_ERROR 5127
extern u_int32_t TCP6_LAST_ERROR;
int doWrite_TCP6_LAST_ERROR(u_int32_t value);
int addWrite_TCP6_LAST_ERROR(u_int32_t value);
int getStatus_TCP6_LAST_ERROR(void);

#define ID_TCP6_WRITE_QUEUE 5128
extern u_int32_t TCP6_WRITE_QUEUE;
int doWrite_TCP6_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP6_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP6_WRITE_QUEUE(void);

#define ID_TCP6_BUS_LOAD 5129
extern u_int32_t TCP6_BUS_LOAD;
int doWrite_TCP6_BUS_LOAD(u_int32_t value);
int addWrite_TCP6_BUS_LOAD(u_int32_t value);
int getStatus_TCP6_BUS_LOAD(void);

#define ID_TCP7_TYPE_PORT 5130
extern u_int32_t TCP7_TYPE_PORT;
int doWrite_TCP7_TYPE_PORT(u_int32_t value);
int addWrite_TCP7_TYPE_PORT(u_int32_t value);
int getStatus_TCP7_TYPE_PORT(void);

#define ID_TCP7_IP_ADDRESS 5131
extern u_int32_t TCP7_IP_ADDRESS;
int doWrite_TCP7_IP_ADDRESS(u_int32_t value);
int addWrite_TCP7_IP_ADDRESS(u_int32_t value);
int getStatus_TCP7_IP_ADDRESS(void);

#define ID_TCP7_STATUS 5132
extern u_int32_t TCP7_STATUS;
int doWrite_TCP7_STATUS(u_int32_t value);
int addWrite_TCP7_STATUS(u_int32_t value);
int getStatus_TCP7_STATUS(void);

#define ID_TCP7_READS 5133
extern u_int32_t TCP7_READS;
int doWrite_TCP7_READS(u_int32_t value);
int addWrite_TCP7_READS(u_int32_t value);
int getStatus_TCP7_READS(void);

#define ID_TCP7_WRITES 5134
extern u_int32_t TCP7_WRITES;
int doWrite_TCP7_WRITES(u_int32_t value);
int addWrite_TCP7_WRITES(u_int32_t value);
int getStatus_TCP7_WRITES(void);

#define ID_TCP7_TIMEOUTS 5135
extern u_int32_t TCP7_TIMEOUTS;
int doWrite_TCP7_TIMEOUTS(u_int32_t value);
int addWrite_TCP7_TIMEOUTS(u_int32_t value);
int getStatus_TCP7_TIMEOUTS(void);

#define ID_TCP7_COMM_ERRORS 5136
extern u_int32_t TCP7_COMM_ERRORS;
int doWrite_TCP7_COMM_ERRORS(u_int32_t value);
int addWrite_TCP7_COMM_ERRORS(u_int32_t value);
int getStatus_TCP7_COMM_ERRORS(void);

#define ID_TCP7_LAST_ERROR 5137
extern u_int32_t TCP7_LAST_ERROR;
int doWrite_TCP7_LAST_ERROR(u_int32_t value);
int addWrite_TCP7_LAST_ERROR(u_int32_t value);
int getStatus_TCP7_LAST_ERROR(void);

#define ID_TCP7_WRITE_QUEUE 5138
extern u_int32_t TCP7_WRITE_QUEUE;
int doWrite_TCP7_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP7_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP7_WRITE_QUEUE(void);

#define ID_TCP7_BUS_LOAD 5139
extern u_int32_t TCP7_BUS_LOAD;
int doWrite_TCP7_BUS_LOAD(u_int32_t value);
int addWrite_TCP7_BUS_LOAD(u_int32_t value);
int getStatus_TCP7_BUS_LOAD(void);

#define ID_TCP8_TYPE_PORT 5140
extern u_int32_t TCP8_TYPE_PORT;
int doWrite_TCP8_TYPE_PORT(u_int32_t value);
int addWrite_TCP8_TYPE_PORT(u_int32_t value);
int getStatus_TCP8_TYPE_PORT(void);

#define ID_TCP8_IP_ADDRESS 5141
extern u_int32_t TCP8_IP_ADDRESS;
int doWrite_TCP8_IP_ADDRESS(u_int32_t value);
int addWrite_TCP8_IP_ADDRESS(u_int32_t value);
int getStatus_TCP8_IP_ADDRESS(void);

#define ID_TCP8_STATUS 5142
extern u_int32_t TCP8_STATUS;
int doWrite_TCP8_STATUS(u_int32_t value);
int addWrite_TCP8_STATUS(u_int32_t value);
int getStatus_TCP8_STATUS(void);

#define ID_TCP8_READS 5143
extern u_int32_t TCP8_READS;
int doWrite_TCP8_READS(u_int32_t value);
int addWrite_TCP8_READS(u_int32_t value);
int getStatus_TCP8_READS(void);

#define ID_TCP8_WRITES 5144
extern u_int32_t TCP8_WRITES;
int doWrite_TCP8_WRITES(u_int32_t value);
int addWrite_TCP8_WRITES(u_int32_t value);
int getStatus_TCP8_WRITES(void);

#define ID_TCP8_TIMEOUTS 5145
extern u_int32_t TCP8_TIMEOUTS;
int doWrite_TCP8_TIMEOUTS(u_int32_t value);
int addWrite_TCP8_TIMEOUTS(u_int32_t value);
int getStatus_TCP8_TIMEOUTS(void);

#define ID_TCP8_COMM_ERRORS 5146
extern u_int32_t TCP8_COMM_ERRORS;
int doWrite_TCP8_COMM_ERRORS(u_int32_t value);
int addWrite_TCP8_COMM_ERRORS(u_int32_t value);
int getStatus_TCP8_COMM_ERRORS(void);

#define ID_TCP8_LAST_ERROR 5147
extern u_int32_t TCP8_LAST_ERROR;
int doWrite_TCP8_LAST_ERROR(u_int32_t value);
int addWrite_TCP8_LAST_ERROR(u_int32_t value);
int getStatus_TCP8_LAST_ERROR(void);

#define ID_TCP8_WRITE_QUEUE 5148
extern u_int32_t TCP8_WRITE_QUEUE;
int doWrite_TCP8_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP8_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP8_WRITE_QUEUE(void);

#define ID_TCP8_BUS_LOAD 5149
extern u_int32_t TCP8_BUS_LOAD;
int doWrite_TCP8_BUS_LOAD(u_int32_t value);
int addWrite_TCP8_BUS_LOAD(u_int32_t value);
int getStatus_TCP8_BUS_LOAD(void);

#define ID_TCP9_TYPE_PORT 5150
extern u_int32_t TCP9_TYPE_PORT;
int doWrite_TCP9_TYPE_PORT(u_int32_t value);
int addWrite_TCP9_TYPE_PORT(u_int32_t value);
int getStatus_TCP9_TYPE_PORT(void);

#define ID_TCP9_IP_ADDRESS 5151
extern u_int32_t TCP9_IP_ADDRESS;
int doWrite_TCP9_IP_ADDRESS(u_int32_t value);
int addWrite_TCP9_IP_ADDRESS(u_int32_t value);
int getStatus_TCP9_IP_ADDRESS(void);

#define ID_TCP9_STATUS 5152
extern u_int32_t TCP9_STATUS;
int doWrite_TCP9_STATUS(u_int32_t value);
int addWrite_TCP9_STATUS(u_int32_t value);
int getStatus_TCP9_STATUS(void);

#define ID_TCP9_READS 5153
extern u_int32_t TCP9_READS;
int doWrite_TCP9_READS(u_int32_t value);
int addWrite_TCP9_READS(u_int32_t value);
int getStatus_TCP9_READS(void);

#define ID_TCP9_WRITES 5154
extern u_int32_t TCP9_WRITES;
int doWrite_TCP9_WRITES(u_int32_t value);
int addWrite_TCP9_WRITES(u_int32_t value);
int getStatus_TCP9_WRITES(void);

#define ID_TCP9_TIMEOUTS 5155
extern u_int32_t TCP9_TIMEOUTS;
int doWrite_TCP9_TIMEOUTS(u_int32_t value);
int addWrite_TCP9_TIMEOUTS(u_int32_t value);
int getStatus_TCP9_TIMEOUTS(void);

#define ID_TCP9_COMM_ERRORS 5156
extern u_int32_t TCP9_COMM_ERRORS;
int doWrite_TCP9_COMM_ERRORS(u_int32_t value);
int addWrite_TCP9_COMM_ERRORS(u_int32_t value);
int getStatus_TCP9_COMM_ERRORS(void);

#define ID_TCP9_LAST_ERROR 5157
extern u_int32_t TCP9_LAST_ERROR;
int doWrite_TCP9_LAST_ERROR(u_int32_t value);
int addWrite_TCP9_LAST_ERROR(u_int32_t value);
int getStatus_TCP9_LAST_ERROR(void);

#define ID_TCP9_WRITE_QUEUE 5158
extern u_int32_t TCP9_WRITE_QUEUE;
int doWrite_TCP9_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP9_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP9_WRITE_QUEUE(void);

#define ID_TCP9_BUS_LOAD 5159
extern u_int32_t TCP9_BUS_LOAD;
int doWrite_TCP9_BUS_LOAD(u_int32_t value);
int addWrite_TCP9_BUS_LOAD(u_int32_t value);
int getStatus_TCP9_BUS_LOAD(void);

#define ID_NODE_01_DEV_NODE 5172
extern u_int32_t NODE_01_DEV_NODE;
int doWrite_NODE_01_DEV_NODE(u_int32_t value);
int addWrite_NODE_01_DEV_NODE(u_int32_t value);
int getStatus_NODE_01_DEV_NODE(void);

#define ID_NODE_01_STATUS 5173
extern u_int32_t NODE_01_STATUS;
int doWrite_NODE_01_STATUS(u_int32_t value);
int addWrite_NODE_01_STATUS(u_int32_t value);
int getStatus_NODE_01_STATUS(void);

#define ID_NODE_02_DEV_NODE 5174
extern u_int32_t NODE_02_DEV_NODE;
int doWrite_NODE_02_DEV_NODE(u_int32_t value);
int addWrite_NODE_02_DEV_NODE(u_int32_t value);
int getStatus_NODE_02_DEV_NODE(void);

#define ID_NODE_02_STATUS 5175
extern u_int32_t NODE_02_STATUS;
int doWrite_NODE_02_STATUS(u_int32_t value);
int addWrite_NODE_02_STATUS(u_int32_t value);
int getStatus_NODE_02_STATUS(void);

#define ID_NODE_03_DEV_NODE 5176
extern u_int32_t NODE_03_DEV_NODE;
int doWrite_NODE_03_DEV_NODE(u_int32_t value);
int addWrite_NODE_03_DEV_NODE(u_int32_t value);
int getStatus_NODE_03_DEV_NODE(void);

#define ID_NODE_03_STATUS 5177
extern u_int32_t NODE_03_STATUS;
int doWrite_NODE_03_STATUS(u_int32_t value);
int addWrite_NODE_03_STATUS(u_int32_t value);
int getStatus_NODE_03_STATUS(void);

#define ID_NODE_04_DEV_NODE 5178
extern u_int32_t NODE_04_DEV_NODE;
int doWrite_NODE_04_DEV_NODE(u_int32_t value);
int addWrite_NODE_04_DEV_NODE(u_int32_t value);
int getStatus_NODE_04_DEV_NODE(void);

#define ID_NODE_04_STATUS 5179
extern u_int32_t NODE_04_STATUS;
int doWrite_NODE_04_STATUS(u_int32_t value);
int addWrite_NODE_04_STATUS(u_int32_t value);
int getStatus_NODE_04_STATUS(void);

#define ID_NODE_05_DEV_NODE 5180
extern u_int32_t NODE_05_DEV_NODE;
int doWrite_NODE_05_DEV_NODE(u_int32_t value);
int addWrite_NODE_05_DEV_NODE(u_int32_t value);
int getStatus_NODE_05_DEV_NODE(void);

#define ID_NODE_05_STATUS 5181
extern u_int32_t NODE_05_STATUS;
int doWrite_NODE_05_STATUS(u_int32_t value);
int addWrite_NODE_05_STATUS(u_int32_t value);
int getStatus_NODE_05_STATUS(void);

#define ID_NODE_06_DEV_NODE 5182
extern u_int32_t NODE_06_DEV_NODE;
int doWrite_NODE_06_DEV_NODE(u_int32_t value);
int addWrite_NODE_06_DEV_NODE(u_int32_t value);
int getStatus_NODE_06_DEV_NODE(void);

#define ID_NODE_06_STATUS 5183
extern u_int32_t NODE_06_STATUS;
int doWrite_NODE_06_STATUS(u_int32_t value);
int addWrite_NODE_06_STATUS(u_int32_t value);
int getStatus_NODE_06_STATUS(void);

#define ID_NODE_07_DEV_NODE 5184
extern u_int32_t NODE_07_DEV_NODE;
int doWrite_NODE_07_DEV_NODE(u_int32_t value);
int addWrite_NODE_07_DEV_NODE(u_int32_t value);
int getStatus_NODE_07_DEV_NODE(void);

#define ID_NODE_07_STATUS 5185
extern u_int32_t NODE_07_STATUS;
int doWrite_NODE_07_STATUS(u_int32_t value);
int addWrite_NODE_07_STATUS(u_int32_t value);
int getStatus_NODE_07_STATUS(void);

#define ID_NODE_08_DEV_NODE 5186
extern u_int32_t NODE_08_DEV_NODE;
int doWrite_NODE_08_DEV_NODE(u_int32_t value);
int addWrite_NODE_08_DEV_NODE(u_int32_t value);
int getStatus_NODE_08_DEV_NODE(void);

#define ID_NODE_08_STATUS 5187
extern u_int32_t NODE_08_STATUS;
int doWrite_NODE_08_STATUS(u_int32_t value);
int addWrite_NODE_08_STATUS(u_int32_t value);
int getStatus_NODE_08_STATUS(void);

#define ID_NODE_09_DEV_NODE 5188
extern u_int32_t NODE_09_DEV_NODE;
int doWrite_NODE_09_DEV_NODE(u_int32_t value);
int addWrite_NODE_09_DEV_NODE(u_int32_t value);
int getStatus_NODE_09_DEV_NODE(void);

#define ID_NODE_09_STATUS 5189
extern u_int32_t NODE_09_STATUS;
int doWrite_NODE_09_STATUS(u_int32_t value);
int addWrite_NODE_09_STATUS(u_int32_t value);
int getStatus_NODE_09_STATUS(void);

#define ID_NODE_10_DEV_NODE 5190
extern u_int32_t NODE_10_DEV_NODE;
int doWrite_NODE_10_DEV_NODE(u_int32_t value);
int addWrite_NODE_10_DEV_NODE(u_int32_t value);
int getStatus_NODE_10_DEV_NODE(void);

#define ID_NODE_10_STATUS 5191
extern u_int32_t NODE_10_STATUS;
int doWrite_NODE_10_STATUS(u_int32_t value);
int addWrite_NODE_10_STATUS(u_int32_t value);
int getStatus_NODE_10_STATUS(void);

#define ID_NODE_11_DEV_NODE 5192
extern u_int32_t NODE_11_DEV_NODE;
int doWrite_NODE_11_DEV_NODE(u_int32_t value);
int addWrite_NODE_11_DEV_NODE(u_int32_t value);
int getStatus_NODE_11_DEV_NODE(void);

#define ID_NODE_11_STATUS 5193
extern u_int32_t NODE_11_STATUS;
int doWrite_NODE_11_STATUS(u_int32_t value);
int addWrite_NODE_11_STATUS(u_int32_t value);
int getStatus_NODE_11_STATUS(void);

#define ID_NODE_12_DEV_NODE 5194
extern u_int32_t NODE_12_DEV_NODE;
int doWrite_NODE_12_DEV_NODE(u_int32_t value);
int addWrite_NODE_12_DEV_NODE(u_int32_t value);
int getStatus_NODE_12_DEV_NODE(void);

#define ID_NODE_12_STATUS 5195
extern u_int32_t NODE_12_STATUS;
int doWrite_NODE_12_STATUS(u_int32_t value);
int addWrite_NODE_12_STATUS(u_int32_t value);
int getStatus_NODE_12_STATUS(void);

#define ID_NODE_13_DEV_NODE 5196
extern u_int32_t NODE_13_DEV_NODE;
int doWrite_NODE_13_DEV_NODE(u_int32_t value);
int addWrite_NODE_13_DEV_NODE(u_int32_t value);
int getStatus_NODE_13_DEV_NODE(void);

#define ID_NODE_13_STATUS 5197
extern u_int32_t NODE_13_STATUS;
int doWrite_NODE_13_STATUS(u_int32_t value);
int addWrite_NODE_13_STATUS(u_int32_t value);
int getStatus_NODE_13_STATUS(void);

#define ID_NODE_14_DEV_NODE 5198
extern u_int32_t NODE_14_DEV_NODE;
int doWrite_NODE_14_DEV_NODE(u_int32_t value);
int addWrite_NODE_14_DEV_NODE(u_int32_t value);
int getStatus_NODE_14_DEV_NODE(void);

#define ID_NODE_14_STATUS 5199
extern u_int32_t NODE_14_STATUS;
int doWrite_NODE_14_STATUS(u_int32_t value);
int addWrite_NODE_14_STATUS(u_int32_t value);
int getStatus_NODE_14_STATUS(void);

#define ID_NODE_15_DEV_NODE 5200
extern u_int32_t NODE_15_DEV_NODE;
int doWrite_NODE_15_DEV_NODE(u_int32_t value);
int addWrite_NODE_15_DEV_NODE(u_int32_t value);
int getStatus_NODE_15_DEV_NODE(void);

#define ID_NODE_15_STATUS 5201
extern u_int32_t NODE_15_STATUS;
int doWrite_NODE_15_STATUS(u_int32_t value);
int addWrite_NODE_15_STATUS(u_int32_t value);
int getStatus_NODE_15_STATUS(void);

#define ID_NODE_16_DEV_NODE 5202
extern u_int32_t NODE_16_DEV_NODE;
int doWrite_NODE_16_DEV_NODE(u_int32_t value);
int addWrite_NODE_16_DEV_NODE(u_int32_t value);
int getStatus_NODE_16_DEV_NODE(void);

#define ID_NODE_16_STATUS 5203
extern u_int32_t NODE_16_STATUS;
int doWrite_NODE_16_STATUS(u_int32_t value);
int addWrite_NODE_16_STATUS(u_int32_t value);
int getStatus_NODE_16_STATUS(void);

#define ID_PLC_time 5390
extern float PLC_time;	/* Seconds since boot (reset each 24h) */
int doWrite_PLC_time(float value);
int addWrite_PLC_time(float value);
int getStatus_PLC_time(void);

#define ID_PLC_timeMin 5391
extern float PLC_timeMin;	/* 10 seconds window start */
int doWrite_PLC_timeMin(float value);
int addWrite_PLC_timeMin(float value);
int getStatus_PLC_timeMin(void);

#define ID_PLC_timeMax 5392
extern float PLC_timeMax;	/* 10 seconds window stop */
int doWrite_PLC_timeMax(float value);
int addWrite_PLC_timeMax(float value);
int getStatus_PLC_timeMax(void);

#define ID_PLC_timeWin 5393
extern float PLC_timeWin;	/* Graph display window */
int doWrite_PLC_timeWin(float value);
int addWrite_PLC_timeWin(float value);
int getStatus_PLC_timeWin(void);

#define ID_PLC_Version 5394
extern u_int16_t PLC_Version;	/* Run Time version */
int doWrite_PLC_Version(u_int16_t value);
int addWrite_PLC_Version(u_int16_t value);
int getStatus_PLC_Version(void);

#define ID_PLC_EngineStatus 5395
extern u_int16_t PLC_EngineStatus;	/* PLC status */
int doWrite_PLC_EngineStatus(u_int16_t value);
int addWrite_PLC_EngineStatus(u_int16_t value);
int getStatus_PLC_EngineStatus(void);

#define ID_PLC_ResetValues 5396
extern int PLC_ResetValues;	/* Diagnostic variables reset */
int doWrite_PLC_ResetValues(int value);
int addWrite_PLC_ResetValues(int value);
int getStatus_PLC_ResetValues(void);

#define ID_PLC_buzzerOn 5397
extern int PLC_buzzerOn;	/* Buzzer sound (enable = 1 disable = 0) */
int doWrite_PLC_buzzerOn(int value);
int addWrite_PLC_buzzerOn(int value);
int getStatus_PLC_buzzerOn(void);

#define ID_PLC_PLC_Version 5398
extern u_int16_t PLC_PLC_Version;	/* PLC application version */
int doWrite_PLC_PLC_Version(u_int16_t value);
int addWrite_PLC_PLC_Version(u_int16_t value);
int getStatus_PLC_PLC_Version(void);

#define ID_PLC_HMI_Version 5399
extern u_int16_t PLC_HMI_Version;	/* HMI application version */
int doWrite_PLC_HMI_Version(u_int16_t value);
int addWrite_PLC_HMI_Version(u_int16_t value);
int getStatus_PLC_HMI_Version(void);

#define ID_PLC_Year 5410
extern u_int16_t PLC_Year;	/* Currently year */
int doWrite_PLC_Year(u_int16_t value);
int addWrite_PLC_Year(u_int16_t value);
int getStatus_PLC_Year(void);

#define ID_PLC_Month 5411
extern u_int16_t PLC_Month;	/* Currently month */
int doWrite_PLC_Month(u_int16_t value);
int addWrite_PLC_Month(u_int16_t value);
int getStatus_PLC_Month(void);

#define ID_PLC_Day 5412
extern u_int16_t PLC_Day;	/* Currently day */
int doWrite_PLC_Day(u_int16_t value);
int addWrite_PLC_Day(u_int16_t value);
int getStatus_PLC_Day(void);

#define ID_PLC_Hours 5413
extern u_int16_t PLC_Hours;	/* Currently hour */
int doWrite_PLC_Hours(u_int16_t value);
int addWrite_PLC_Hours(u_int16_t value);
int getStatus_PLC_Hours(void);

#define ID_PLC_Minutes 5414
extern u_int16_t PLC_Minutes;	/* Currently minutes */
int doWrite_PLC_Minutes(u_int16_t value);
int addWrite_PLC_Minutes(u_int16_t value);
int getStatus_PLC_Minutes(void);

#define ID_PLC_Seconds 5415
extern u_int16_t PLC_Seconds;	/* Currently seconds */
int doWrite_PLC_Seconds(u_int16_t value);
int addWrite_PLC_Seconds(u_int16_t value);
int getStatus_PLC_Seconds(void);

#define ID_PLC_UPTIME_s 5416
extern u_int32_t PLC_UPTIME_s;	/* Uptime in seconds (wraps in 136 years) */
int doWrite_PLC_UPTIME_s(u_int32_t value);
int addWrite_PLC_UPTIME_s(u_int32_t value);
int getStatus_PLC_UPTIME_s(void);

#define ID_PLC_UPTIME_cs 5417
extern u_int32_t PLC_UPTIME_cs;	/* Uptime in centiseconds = 10 ms (wraps in 497 days) */
int doWrite_PLC_UPTIME_cs(u_int32_t value);
int addWrite_PLC_UPTIME_cs(u_int32_t value);
int getStatus_PLC_UPTIME_cs(void);

#define ID_PLC_WATCHDOGEN 5418
extern int PLC_WATCHDOGEN;	/* Enable Watchdog */
int doWrite_PLC_WATCHDOGEN(int value);
int addWrite_PLC_WATCHDOGEN(int value);
int getStatus_PLC_WATCHDOGEN(void);

#define ID_PLC_WATCHDOG_ms 5419
extern u_int32_t PLC_WATCHDOG_ms;	/* Reset Watchdog timer */
int doWrite_PLC_WATCHDOG_ms(u_int32_t value);
int addWrite_PLC_WATCHDOG_ms(u_int32_t value);
int getStatus_PLC_WATCHDOG_ms(void);

#define ID_PLC_PRODUCT_ID 5420
extern u_int32_t PLC_PRODUCT_ID;	/* TP/TPAC/TPLC Product ID (Hex) */
int doWrite_PLC_PRODUCT_ID(u_int32_t value);
int addWrite_PLC_PRODUCT_ID(u_int32_t value);
int getStatus_PLC_PRODUCT_ID(void);

#define ID_PLC_SERIAL_NUMBER 5421
extern u_int32_t PLC_SERIAL_NUMBER;	/* TP/TPAC/TPLC Serial Number */
int doWrite_PLC_SERIAL_NUMBER(u_int32_t value);
int addWrite_PLC_SERIAL_NUMBER(u_int32_t value);
int getStatus_PLC_SERIAL_NUMBER(void);

#define ID_PLC_HMI_PAGE 5422
extern int32_t PLC_HMI_PAGE;	/* HMI Page (page100=0x00000100) */
int doWrite_PLC_HMI_PAGE(int32_t value);
int addWrite_PLC_HMI_PAGE(int32_t value);
int getStatus_PLC_HMI_PAGE(void);

#define ID_PLC_BEEP_VOLUME 5435
extern u_int8_t PLC_BEEP_VOLUME;	/* Beep volume (when buzzerOn) */
int doWrite_PLC_BEEP_VOLUME(u_int8_t value);
int addWrite_PLC_BEEP_VOLUME(u_int8_t value);
int getStatus_PLC_BEEP_VOLUME(void);

#define ID_PLC_TOUCH_VOLUME 5436
extern u_int8_t PLC_TOUCH_VOLUME;	/* Touch volume */
int doWrite_PLC_TOUCH_VOLUME(u_int8_t value);
int addWrite_PLC_TOUCH_VOLUME(u_int8_t value);
int getStatus_PLC_TOUCH_VOLUME(void);

#define ID_PLC_ALARM_VOLUME 5437
extern u_int8_t PLC_ALARM_VOLUME;	/* Alarm volume (when alarm) */
int doWrite_PLC_ALARM_VOLUME(u_int8_t value);
int addWrite_PLC_ALARM_VOLUME(u_int8_t value);
int getStatus_PLC_ALARM_VOLUME(void);

#define ID_PLC_BUZZER 5438
extern u_int32_t PLC_BUZZER;	/* Enable dynamic buzzer sound (0x44332211 up=0x11(%) on=0x22(cs) off=0x33(cs) rep=0x44(times)) */
int doWrite_PLC_BUZZER(u_int32_t value);
int addWrite_PLC_BUZZER(u_int32_t value);
int getStatus_PLC_BUZZER(void);

#define ID_PLC_FastIO_Ena 5439
extern u_int32_t PLC_FastIO_Ena;	/* Fast IO Enable */
int doWrite_PLC_FastIO_Ena(u_int32_t value);
int addWrite_PLC_FastIO_Ena(u_int32_t value);
int getStatus_PLC_FastIO_Ena(void);

#define ID_PLC_FastIO_Dir 5440
extern u_int32_t PLC_FastIO_Dir;	/* Fast IO Configuration */
int doWrite_PLC_FastIO_Dir(u_int32_t value);
int addWrite_PLC_FastIO_Dir(u_int32_t value);
int getStatus_PLC_FastIO_Dir(void);

#define ID_PLC_FastIO_1 5441
extern int PLC_FastIO_1;	/* Fast Input 1 */
int doWrite_PLC_FastIO_1(int value);
int addWrite_PLC_FastIO_1(int value);
int getStatus_PLC_FastIO_1(void);

#define ID_PLC_FastIO_2 5442
extern int PLC_FastIO_2;	/* Fast Input 2 */
int doWrite_PLC_FastIO_2(int value);
int addWrite_PLC_FastIO_2(int value);
int getStatus_PLC_FastIO_2(void);

#define ID_PLC_FastIO_3 5443
extern int PLC_FastIO_3;	/* Fast Input 3 */
int doWrite_PLC_FastIO_3(int value);
int addWrite_PLC_FastIO_3(int value);
int getStatus_PLC_FastIO_3(void);

#define ID_PLC_FastIO_4 5444
extern int PLC_FastIO_4;	/* Fast Input 4 */
int doWrite_PLC_FastIO_4(int value);
int addWrite_PLC_FastIO_4(int value);
int getStatus_PLC_FastIO_4(void);

#define ID_PLC_FastIO_5 5445
extern int PLC_FastIO_5;	/* Fast Output 1 */
int doWrite_PLC_FastIO_5(int value);
int addWrite_PLC_FastIO_5(int value);
int getStatus_PLC_FastIO_5(void);

#define ID_PLC_FastIO_6 5446
extern int PLC_FastIO_6;	/* Fast Output 2 */
int doWrite_PLC_FastIO_6(int value);
int addWrite_PLC_FastIO_6(int value);
int getStatus_PLC_FastIO_6(void);

#define ID_PLC_FastIO_7 5447
extern int PLC_FastIO_7;	/* Fast Output 3 */
int doWrite_PLC_FastIO_7(int value);
int addWrite_PLC_FastIO_7(int value);
int getStatus_PLC_FastIO_7(void);

#define ID_PLC_FastIO_8 5448
extern int PLC_FastIO_8;	/* Fast Output 4 */
int doWrite_PLC_FastIO_8(int value);
int addWrite_PLC_FastIO_8(int value);
int getStatus_PLC_FastIO_8(void);

#ifdef __cplusplus
}
#endif
#endif
