/* File automatically generated by the Crosstable compiler */
/* from the Crosstable file Crosstable.csv. */

/* BIT        ->  int       */
/* BYTE_BIT   ->  int       */
/* WORD_BIT   ->  int       */
/* DWORD_BIT  ->  int       */
/* BYTE       ->  u_int8_t  */
/* UINT       ->  u_int16_t */
/* UINTBA     ->  UINTBA    */
/* INT        ->  int16_t   */
/* INTBA      ->  INTBA     */
/* UDINT      ->  u_int32_t */
/* UDINTBADC  ->  UDINTBADC */
/* UDINTCDAB  ->  UDINTCDAB */
/* UDINTDCBA  ->  UDINTDCBA */
/* DINT       ->  int32_t   */
/* DINTBADC   ->  DINTBADC  */
/* DINTCDAB   ->  DINTCDAB  */
/* DINTDCBA   ->  DINTDCBA  */
/* REAL       ->  float     */
/* REALBADC   ->  REALBADC  */
/* REALCDAB   ->  REALCDAB  */
/* REALDCBA   ->  REALDCBA  */

#ifndef CROSSTABLE_H__
#define CROSSTABLE_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <sys/types.h>
#include "cross_table_utility.h"


#define ID_RTU0_TYPE_PORT 5000
extern u_int32_t RTU0_TYPE_PORT;
int doWrite_RTU0_TYPE_PORT(u_int32_t value);
int addWrite_RTU0_TYPE_PORT(u_int32_t value);
int getStatus_RTU0_TYPE_PORT(void);

#define ID_RTU0_BAUDRATE 5001
extern u_int32_t RTU0_BAUDRATE;
int doWrite_RTU0_BAUDRATE(u_int32_t value);
int addWrite_RTU0_BAUDRATE(u_int32_t value);
int getStatus_RTU0_BAUDRATE(void);

#define ID_RTU0_STATUS 5002
extern u_int32_t RTU0_STATUS;
int doWrite_RTU0_STATUS(u_int32_t value);
int addWrite_RTU0_STATUS(u_int32_t value);
int getStatus_RTU0_STATUS(void);

#define ID_RTU0_READS 5003
extern u_int32_t RTU0_READS;
int doWrite_RTU0_READS(u_int32_t value);
int addWrite_RTU0_READS(u_int32_t value);
int getStatus_RTU0_READS(void);

#define ID_RTU0_WRITES 5004
extern u_int32_t RTU0_WRITES;
int doWrite_RTU0_WRITES(u_int32_t value);
int addWrite_RTU0_WRITES(u_int32_t value);
int getStatus_RTU0_WRITES(void);

#define ID_RTU0_TIMEOUTS 5005
extern u_int32_t RTU0_TIMEOUTS;
int doWrite_RTU0_TIMEOUTS(u_int32_t value);
int addWrite_RTU0_TIMEOUTS(u_int32_t value);
int getStatus_RTU0_TIMEOUTS(void);

#define ID_RTU0_COMM_ERRORS 5006
extern u_int32_t RTU0_COMM_ERRORS;
int doWrite_RTU0_COMM_ERRORS(u_int32_t value);
int addWrite_RTU0_COMM_ERRORS(u_int32_t value);
int getStatus_RTU0_COMM_ERRORS(void);

#define ID_RTU0_LAST_ERROR 5007
extern u_int32_t RTU0_LAST_ERROR;
int doWrite_RTU0_LAST_ERROR(u_int32_t value);
int addWrite_RTU0_LAST_ERROR(u_int32_t value);
int getStatus_RTU0_LAST_ERROR(void);

#define ID_RTU0_WRITE_QUEUE 5008
extern u_int32_t RTU0_WRITE_QUEUE;
int doWrite_RTU0_WRITE_QUEUE(u_int32_t value);
int addWrite_RTU0_WRITE_QUEUE(u_int32_t value);
int getStatus_RTU0_WRITE_QUEUE(void);

#define ID_RTU0_BUS_LOAD 5009
extern u_int32_t RTU0_BUS_LOAD;
int doWrite_RTU0_BUS_LOAD(u_int32_t value);
int addWrite_RTU0_BUS_LOAD(u_int32_t value);
int getStatus_RTU0_BUS_LOAD(void);

#define ID_RTU1_TYPE_PORT 5010
extern u_int32_t RTU1_TYPE_PORT;
int doWrite_RTU1_TYPE_PORT(u_int32_t value);
int addWrite_RTU1_TYPE_PORT(u_int32_t value);
int getStatus_RTU1_TYPE_PORT(void);

#define ID_RTU1_BAUDRATE 5011
extern u_int32_t RTU1_BAUDRATE;
int doWrite_RTU1_BAUDRATE(u_int32_t value);
int addWrite_RTU1_BAUDRATE(u_int32_t value);
int getStatus_RTU1_BAUDRATE(void);

#define ID_RTU1_STATUS 5012
extern u_int32_t RTU1_STATUS;
int doWrite_RTU1_STATUS(u_int32_t value);
int addWrite_RTU1_STATUS(u_int32_t value);
int getStatus_RTU1_STATUS(void);

#define ID_RTU1_READS 5013
extern u_int32_t RTU1_READS;
int doWrite_RTU1_READS(u_int32_t value);
int addWrite_RTU1_READS(u_int32_t value);
int getStatus_RTU1_READS(void);

#define ID_RTU1_WRITES 5014
extern u_int32_t RTU1_WRITES;
int doWrite_RTU1_WRITES(u_int32_t value);
int addWrite_RTU1_WRITES(u_int32_t value);
int getStatus_RTU1_WRITES(void);

#define ID_RTU1_TIMEOUTS 5015
extern u_int32_t RTU1_TIMEOUTS;
int doWrite_RTU1_TIMEOUTS(u_int32_t value);
int addWrite_RTU1_TIMEOUTS(u_int32_t value);
int getStatus_RTU1_TIMEOUTS(void);

#define ID_RTU1_COMM_ERRORS 5016
extern u_int32_t RTU1_COMM_ERRORS;
int doWrite_RTU1_COMM_ERRORS(u_int32_t value);
int addWrite_RTU1_COMM_ERRORS(u_int32_t value);
int getStatus_RTU1_COMM_ERRORS(void);

#define ID_RTU1_LAST_ERROR 5017
extern u_int32_t RTU1_LAST_ERROR;
int doWrite_RTU1_LAST_ERROR(u_int32_t value);
int addWrite_RTU1_LAST_ERROR(u_int32_t value);
int getStatus_RTU1_LAST_ERROR(void);

#define ID_RTU1_WRITE_QUEUE 5018
extern u_int32_t RTU1_WRITE_QUEUE;
int doWrite_RTU1_WRITE_QUEUE(u_int32_t value);
int addWrite_RTU1_WRITE_QUEUE(u_int32_t value);
int getStatus_RTU1_WRITE_QUEUE(void);

#define ID_RTU1_BUS_LOAD 5019
extern u_int32_t RTU1_BUS_LOAD;
int doWrite_RTU1_BUS_LOAD(u_int32_t value);
int addWrite_RTU1_BUS_LOAD(u_int32_t value);
int getStatus_RTU1_BUS_LOAD(void);

#define ID_RTU3_TYPE_PORT 5020
extern u_int32_t RTU3_TYPE_PORT;
int doWrite_RTU3_TYPE_PORT(u_int32_t value);
int addWrite_RTU3_TYPE_PORT(u_int32_t value);
int getStatus_RTU3_TYPE_PORT(void);

#define ID_RTU3_BAUDRATE 5021
extern u_int32_t RTU3_BAUDRATE;
int doWrite_RTU3_BAUDRATE(u_int32_t value);
int addWrite_RTU3_BAUDRATE(u_int32_t value);
int getStatus_RTU3_BAUDRATE(void);

#define ID_RTU3_STATUS 5022
extern u_int32_t RTU3_STATUS;
int doWrite_RTU3_STATUS(u_int32_t value);
int addWrite_RTU3_STATUS(u_int32_t value);
int getStatus_RTU3_STATUS(void);

#define ID_RTU3_READS 5023
extern u_int32_t RTU3_READS;
int doWrite_RTU3_READS(u_int32_t value);
int addWrite_RTU3_READS(u_int32_t value);
int getStatus_RTU3_READS(void);

#define ID_RTU3_WRITES 5024
extern u_int32_t RTU3_WRITES;
int doWrite_RTU3_WRITES(u_int32_t value);
int addWrite_RTU3_WRITES(u_int32_t value);
int getStatus_RTU3_WRITES(void);

#define ID_RTU3_TIMEOUTS 5025
extern u_int32_t RTU3_TIMEOUTS;
int doWrite_RTU3_TIMEOUTS(u_int32_t value);
int addWrite_RTU3_TIMEOUTS(u_int32_t value);
int getStatus_RTU3_TIMEOUTS(void);

#define ID_RTU3_COMM_ERRORS 5026
extern u_int32_t RTU3_COMM_ERRORS;
int doWrite_RTU3_COMM_ERRORS(u_int32_t value);
int addWrite_RTU3_COMM_ERRORS(u_int32_t value);
int getStatus_RTU3_COMM_ERRORS(void);

#define ID_RTU3_LAST_ERROR 5027
extern u_int32_t RTU3_LAST_ERROR;
int doWrite_RTU3_LAST_ERROR(u_int32_t value);
int addWrite_RTU3_LAST_ERROR(u_int32_t value);
int getStatus_RTU3_LAST_ERROR(void);

#define ID_RTU3_WRITE_QUEUE 5028
extern u_int32_t RTU3_WRITE_QUEUE;
int doWrite_RTU3_WRITE_QUEUE(u_int32_t value);
int addWrite_RTU3_WRITE_QUEUE(u_int32_t value);
int getStatus_RTU3_WRITE_QUEUE(void);

#define ID_RTU3_BUS_LOAD 5029
extern u_int32_t RTU3_BUS_LOAD;
int doWrite_RTU3_BUS_LOAD(u_int32_t value);
int addWrite_RTU3_BUS_LOAD(u_int32_t value);
int getStatus_RTU3_BUS_LOAD(void);

#define ID_CAN0_TYPE_PORT 5030
extern u_int32_t CAN0_TYPE_PORT;
int doWrite_CAN0_TYPE_PORT(u_int32_t value);
int addWrite_CAN0_TYPE_PORT(u_int32_t value);
int getStatus_CAN0_TYPE_PORT(void);

#define ID_CAN0_BAUDRATE 5031
extern u_int32_t CAN0_BAUDRATE;
int doWrite_CAN0_BAUDRATE(u_int32_t value);
int addWrite_CAN0_BAUDRATE(u_int32_t value);
int getStatus_CAN0_BAUDRATE(void);

#define ID_CAN0_STATUS 5032
extern u_int32_t CAN0_STATUS;
int doWrite_CAN0_STATUS(u_int32_t value);
int addWrite_CAN0_STATUS(u_int32_t value);
int getStatus_CAN0_STATUS(void);

#define ID_CAN0_READS 5033
extern u_int32_t CAN0_READS;
int doWrite_CAN0_READS(u_int32_t value);
int addWrite_CAN0_READS(u_int32_t value);
int getStatus_CAN0_READS(void);

#define ID_CAN0_WRITES 5034
extern u_int32_t CAN0_WRITES;
int doWrite_CAN0_WRITES(u_int32_t value);
int addWrite_CAN0_WRITES(u_int32_t value);
int getStatus_CAN0_WRITES(void);

#define ID_CAN0_TIMEOUTS 5035
extern u_int32_t CAN0_TIMEOUTS;
int doWrite_CAN0_TIMEOUTS(u_int32_t value);
int addWrite_CAN0_TIMEOUTS(u_int32_t value);
int getStatus_CAN0_TIMEOUTS(void);

#define ID_CAN0_COMM_ERRORS 5036
extern u_int32_t CAN0_COMM_ERRORS;
int doWrite_CAN0_COMM_ERRORS(u_int32_t value);
int addWrite_CAN0_COMM_ERRORS(u_int32_t value);
int getStatus_CAN0_COMM_ERRORS(void);

#define ID_CAN0_LAST_ERROR 5037
extern u_int32_t CAN0_LAST_ERROR;
int doWrite_CAN0_LAST_ERROR(u_int32_t value);
int addWrite_CAN0_LAST_ERROR(u_int32_t value);
int getStatus_CAN0_LAST_ERROR(void);

#define ID_CAN0_WRITE_QUEUE 5038
extern u_int32_t CAN0_WRITE_QUEUE;
int doWrite_CAN0_WRITE_QUEUE(u_int32_t value);
int addWrite_CAN0_WRITE_QUEUE(u_int32_t value);
int getStatus_CAN0_WRITE_QUEUE(void);

#define ID_CAN0_BUS_LOAD 5039
extern u_int32_t CAN0_BUS_LOAD;
int doWrite_CAN0_BUS_LOAD(u_int32_t value);
int addWrite_CAN0_BUS_LOAD(u_int32_t value);
int getStatus_CAN0_BUS_LOAD(void);

#define ID_CAN1_TYPE_PORT 5040
extern u_int32_t CAN1_TYPE_PORT;
int doWrite_CAN1_TYPE_PORT(u_int32_t value);
int addWrite_CAN1_TYPE_PORT(u_int32_t value);
int getStatus_CAN1_TYPE_PORT(void);

#define ID_CAN1_BAUDRATE 5041
extern u_int32_t CAN1_BAUDRATE;
int doWrite_CAN1_BAUDRATE(u_int32_t value);
int addWrite_CAN1_BAUDRATE(u_int32_t value);
int getStatus_CAN1_BAUDRATE(void);

#define ID_CAN1_STATUS 5042
extern u_int32_t CAN1_STATUS;
int doWrite_CAN1_STATUS(u_int32_t value);
int addWrite_CAN1_STATUS(u_int32_t value);
int getStatus_CAN1_STATUS(void);

#define ID_CAN1_READS 5043
extern u_int32_t CAN1_READS;
int doWrite_CAN1_READS(u_int32_t value);
int addWrite_CAN1_READS(u_int32_t value);
int getStatus_CAN1_READS(void);

#define ID_CAN1_WRITES 5044
extern u_int32_t CAN1_WRITES;
int doWrite_CAN1_WRITES(u_int32_t value);
int addWrite_CAN1_WRITES(u_int32_t value);
int getStatus_CAN1_WRITES(void);

#define ID_CAN1_TIMEOUTS 5045
extern u_int32_t CAN1_TIMEOUTS;
int doWrite_CAN1_TIMEOUTS(u_int32_t value);
int addWrite_CAN1_TIMEOUTS(u_int32_t value);
int getStatus_CAN1_TIMEOUTS(void);

#define ID_CAN1_COMM_ERRORS 5046
extern u_int32_t CAN1_COMM_ERRORS;
int doWrite_CAN1_COMM_ERRORS(u_int32_t value);
int addWrite_CAN1_COMM_ERRORS(u_int32_t value);
int getStatus_CAN1_COMM_ERRORS(void);

#define ID_CAN1_LAST_ERROR 5047
extern u_int32_t CAN1_LAST_ERROR;
int doWrite_CAN1_LAST_ERROR(u_int32_t value);
int addWrite_CAN1_LAST_ERROR(u_int32_t value);
int getStatus_CAN1_LAST_ERROR(void);

#define ID_CAN1_WRITE_QUEUE 5048
extern u_int32_t CAN1_WRITE_QUEUE;
int doWrite_CAN1_WRITE_QUEUE(u_int32_t value);
int addWrite_CAN1_WRITE_QUEUE(u_int32_t value);
int getStatus_CAN1_WRITE_QUEUE(void);

#define ID_CAN1_BUS_LOAD 5049
extern u_int32_t CAN1_BUS_LOAD;
int doWrite_CAN1_BUS_LOAD(u_int32_t value);
int addWrite_CAN1_BUS_LOAD(u_int32_t value);
int getStatus_CAN1_BUS_LOAD(void);

#define ID_TCPS_TYPE_PORT 5050
extern u_int32_t TCPS_TYPE_PORT;
int doWrite_TCPS_TYPE_PORT(u_int32_t value);
int addWrite_TCPS_TYPE_PORT(u_int32_t value);
int getStatus_TCPS_TYPE_PORT(void);

#define ID_TCPS_IP_ADDRESS 5051
extern u_int32_t TCPS_IP_ADDRESS;
int doWrite_TCPS_IP_ADDRESS(u_int32_t value);
int addWrite_TCPS_IP_ADDRESS(u_int32_t value);
int getStatus_TCPS_IP_ADDRESS(void);

#define ID_TCPS_STATUS 5052
extern u_int32_t TCPS_STATUS;
int doWrite_TCPS_STATUS(u_int32_t value);
int addWrite_TCPS_STATUS(u_int32_t value);
int getStatus_TCPS_STATUS(void);

#define ID_TCPS_READS 5053
extern u_int32_t TCPS_READS;
int doWrite_TCPS_READS(u_int32_t value);
int addWrite_TCPS_READS(u_int32_t value);
int getStatus_TCPS_READS(void);

#define ID_TCPS_WRITES 5054
extern u_int32_t TCPS_WRITES;
int doWrite_TCPS_WRITES(u_int32_t value);
int addWrite_TCPS_WRITES(u_int32_t value);
int getStatus_TCPS_WRITES(void);

#define ID_TCPS_TIMEOUTS 5055
extern u_int32_t TCPS_TIMEOUTS;
int doWrite_TCPS_TIMEOUTS(u_int32_t value);
int addWrite_TCPS_TIMEOUTS(u_int32_t value);
int getStatus_TCPS_TIMEOUTS(void);

#define ID_TCPS_COMM_ERRORS 5056
extern u_int32_t TCPS_COMM_ERRORS;
int doWrite_TCPS_COMM_ERRORS(u_int32_t value);
int addWrite_TCPS_COMM_ERRORS(u_int32_t value);
int getStatus_TCPS_COMM_ERRORS(void);

#define ID_TCPS_LAST_ERROR 5057
extern u_int32_t TCPS_LAST_ERROR;
int doWrite_TCPS_LAST_ERROR(u_int32_t value);
int addWrite_TCPS_LAST_ERROR(u_int32_t value);
int getStatus_TCPS_LAST_ERROR(void);

#define ID_TCPS_WRITE_QUEUE 5058
extern u_int32_t TCPS_WRITE_QUEUE;
int doWrite_TCPS_WRITE_QUEUE(u_int32_t value);
int addWrite_TCPS_WRITE_QUEUE(u_int32_t value);
int getStatus_TCPS_WRITE_QUEUE(void);

#define ID_TCPS_BUS_LOAD 5059
extern u_int32_t TCPS_BUS_LOAD;
int doWrite_TCPS_BUS_LOAD(u_int32_t value);
int addWrite_TCPS_BUS_LOAD(u_int32_t value);
int getStatus_TCPS_BUS_LOAD(void);

#define ID_TCP0_TYPE_PORT 5060
extern u_int32_t TCP0_TYPE_PORT;
int doWrite_TCP0_TYPE_PORT(u_int32_t value);
int addWrite_TCP0_TYPE_PORT(u_int32_t value);
int getStatus_TCP0_TYPE_PORT(void);

#define ID_TCP0_IP_ADDRESS 5061
extern u_int32_t TCP0_IP_ADDRESS;
int doWrite_TCP0_IP_ADDRESS(u_int32_t value);
int addWrite_TCP0_IP_ADDRESS(u_int32_t value);
int getStatus_TCP0_IP_ADDRESS(void);

#define ID_TCP0_STATUS 5062
extern u_int32_t TCP0_STATUS;
int doWrite_TCP0_STATUS(u_int32_t value);
int addWrite_TCP0_STATUS(u_int32_t value);
int getStatus_TCP0_STATUS(void);

#define ID_TCP0_READS 5063
extern u_int32_t TCP0_READS;
int doWrite_TCP0_READS(u_int32_t value);
int addWrite_TCP0_READS(u_int32_t value);
int getStatus_TCP0_READS(void);

#define ID_TCP0_WRITES 5064
extern u_int32_t TCP0_WRITES;
int doWrite_TCP0_WRITES(u_int32_t value);
int addWrite_TCP0_WRITES(u_int32_t value);
int getStatus_TCP0_WRITES(void);

#define ID_TCP0_TIMEOUTS 5065
extern u_int32_t TCP0_TIMEOUTS;
int doWrite_TCP0_TIMEOUTS(u_int32_t value);
int addWrite_TCP0_TIMEOUTS(u_int32_t value);
int getStatus_TCP0_TIMEOUTS(void);

#define ID_TCP0_COMM_ERRORS 5066
extern u_int32_t TCP0_COMM_ERRORS;
int doWrite_TCP0_COMM_ERRORS(u_int32_t value);
int addWrite_TCP0_COMM_ERRORS(u_int32_t value);
int getStatus_TCP0_COMM_ERRORS(void);

#define ID_TCP0_LAST_ERROR 5067
extern u_int32_t TCP0_LAST_ERROR;
int doWrite_TCP0_LAST_ERROR(u_int32_t value);
int addWrite_TCP0_LAST_ERROR(u_int32_t value);
int getStatus_TCP0_LAST_ERROR(void);

#define ID_TCP0_WRITE_QUEUE 5068
extern u_int32_t TCP0_WRITE_QUEUE;
int doWrite_TCP0_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP0_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP0_WRITE_QUEUE(void);

#define ID_TCP0_BUS_LOAD 5069
extern u_int32_t TCP0_BUS_LOAD;
int doWrite_TCP0_BUS_LOAD(u_int32_t value);
int addWrite_TCP0_BUS_LOAD(u_int32_t value);
int getStatus_TCP0_BUS_LOAD(void);

#define ID_TCP1_TYPE_PORT 5070
extern u_int32_t TCP1_TYPE_PORT;
int doWrite_TCP1_TYPE_PORT(u_int32_t value);
int addWrite_TCP1_TYPE_PORT(u_int32_t value);
int getStatus_TCP1_TYPE_PORT(void);

#define ID_TCP1_IP_ADDRESS 5071
extern u_int32_t TCP1_IP_ADDRESS;
int doWrite_TCP1_IP_ADDRESS(u_int32_t value);
int addWrite_TCP1_IP_ADDRESS(u_int32_t value);
int getStatus_TCP1_IP_ADDRESS(void);

#define ID_TCP1_STATUS 5072
extern u_int32_t TCP1_STATUS;
int doWrite_TCP1_STATUS(u_int32_t value);
int addWrite_TCP1_STATUS(u_int32_t value);
int getStatus_TCP1_STATUS(void);

#define ID_TCP1_READS 5073
extern u_int32_t TCP1_READS;
int doWrite_TCP1_READS(u_int32_t value);
int addWrite_TCP1_READS(u_int32_t value);
int getStatus_TCP1_READS(void);

#define ID_TCP1_WRITES 5074
extern u_int32_t TCP1_WRITES;
int doWrite_TCP1_WRITES(u_int32_t value);
int addWrite_TCP1_WRITES(u_int32_t value);
int getStatus_TCP1_WRITES(void);

#define ID_TCP1_TIMEOUTS 5075
extern u_int32_t TCP1_TIMEOUTS;
int doWrite_TCP1_TIMEOUTS(u_int32_t value);
int addWrite_TCP1_TIMEOUTS(u_int32_t value);
int getStatus_TCP1_TIMEOUTS(void);

#define ID_TCP1_COMM_ERRORS 5076
extern u_int32_t TCP1_COMM_ERRORS;
int doWrite_TCP1_COMM_ERRORS(u_int32_t value);
int addWrite_TCP1_COMM_ERRORS(u_int32_t value);
int getStatus_TCP1_COMM_ERRORS(void);

#define ID_TCP1_LAST_ERROR 5077
extern u_int32_t TCP1_LAST_ERROR;
int doWrite_TCP1_LAST_ERROR(u_int32_t value);
int addWrite_TCP1_LAST_ERROR(u_int32_t value);
int getStatus_TCP1_LAST_ERROR(void);

#define ID_TCP1_WRITE_QUEUE 5078
extern u_int32_t TCP1_WRITE_QUEUE;
int doWrite_TCP1_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP1_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP1_WRITE_QUEUE(void);

#define ID_TCP1_BUS_LOAD 5079
extern u_int32_t TCP1_BUS_LOAD;
int doWrite_TCP1_BUS_LOAD(u_int32_t value);
int addWrite_TCP1_BUS_LOAD(u_int32_t value);
int getStatus_TCP1_BUS_LOAD(void);

#define ID_TCP2_TYPE_PORT 5080
extern u_int32_t TCP2_TYPE_PORT;
int doWrite_TCP2_TYPE_PORT(u_int32_t value);
int addWrite_TCP2_TYPE_PORT(u_int32_t value);
int getStatus_TCP2_TYPE_PORT(void);

#define ID_TCP2_IP_ADDRESS 5081
extern u_int32_t TCP2_IP_ADDRESS;
int doWrite_TCP2_IP_ADDRESS(u_int32_t value);
int addWrite_TCP2_IP_ADDRESS(u_int32_t value);
int getStatus_TCP2_IP_ADDRESS(void);

#define ID_TCP2_STATUS 5082
extern u_int32_t TCP2_STATUS;
int doWrite_TCP2_STATUS(u_int32_t value);
int addWrite_TCP2_STATUS(u_int32_t value);
int getStatus_TCP2_STATUS(void);

#define ID_TCP2_READS 5083
extern u_int32_t TCP2_READS;
int doWrite_TCP2_READS(u_int32_t value);
int addWrite_TCP2_READS(u_int32_t value);
int getStatus_TCP2_READS(void);

#define ID_TCP2_WRITES 5084
extern u_int32_t TCP2_WRITES;
int doWrite_TCP2_WRITES(u_int32_t value);
int addWrite_TCP2_WRITES(u_int32_t value);
int getStatus_TCP2_WRITES(void);

#define ID_TCP2_TIMEOUTS 5085
extern u_int32_t TCP2_TIMEOUTS;
int doWrite_TCP2_TIMEOUTS(u_int32_t value);
int addWrite_TCP2_TIMEOUTS(u_int32_t value);
int getStatus_TCP2_TIMEOUTS(void);

#define ID_TCP2_COMM_ERRORS 5086
extern u_int32_t TCP2_COMM_ERRORS;
int doWrite_TCP2_COMM_ERRORS(u_int32_t value);
int addWrite_TCP2_COMM_ERRORS(u_int32_t value);
int getStatus_TCP2_COMM_ERRORS(void);

#define ID_TCP2_LAST_ERROR 5087
extern u_int32_t TCP2_LAST_ERROR;
int doWrite_TCP2_LAST_ERROR(u_int32_t value);
int addWrite_TCP2_LAST_ERROR(u_int32_t value);
int getStatus_TCP2_LAST_ERROR(void);

#define ID_TCP2_WRITE_QUEUE 5088
extern u_int32_t TCP2_WRITE_QUEUE;
int doWrite_TCP2_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP2_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP2_WRITE_QUEUE(void);

#define ID_TCP2_BUS_LOAD 5089
extern u_int32_t TCP2_BUS_LOAD;
int doWrite_TCP2_BUS_LOAD(u_int32_t value);
int addWrite_TCP2_BUS_LOAD(u_int32_t value);
int getStatus_TCP2_BUS_LOAD(void);

#define ID_TCP3_TYPE_PORT 5090
extern u_int32_t TCP3_TYPE_PORT;
int doWrite_TCP3_TYPE_PORT(u_int32_t value);
int addWrite_TCP3_TYPE_PORT(u_int32_t value);
int getStatus_TCP3_TYPE_PORT(void);

#define ID_TCP3_IP_ADDRESS 5091
extern u_int32_t TCP3_IP_ADDRESS;
int doWrite_TCP3_IP_ADDRESS(u_int32_t value);
int addWrite_TCP3_IP_ADDRESS(u_int32_t value);
int getStatus_TCP3_IP_ADDRESS(void);

#define ID_TCP3_STATUS 5092
extern u_int32_t TCP3_STATUS;
int doWrite_TCP3_STATUS(u_int32_t value);
int addWrite_TCP3_STATUS(u_int32_t value);
int getStatus_TCP3_STATUS(void);

#define ID_TCP3_READS 5093
extern u_int32_t TCP3_READS;
int doWrite_TCP3_READS(u_int32_t value);
int addWrite_TCP3_READS(u_int32_t value);
int getStatus_TCP3_READS(void);

#define ID_TCP3_WRITES 5094
extern u_int32_t TCP3_WRITES;
int doWrite_TCP3_WRITES(u_int32_t value);
int addWrite_TCP3_WRITES(u_int32_t value);
int getStatus_TCP3_WRITES(void);

#define ID_TCP3_TIMEOUTS 5095
extern u_int32_t TCP3_TIMEOUTS;
int doWrite_TCP3_TIMEOUTS(u_int32_t value);
int addWrite_TCP3_TIMEOUTS(u_int32_t value);
int getStatus_TCP3_TIMEOUTS(void);

#define ID_TCP3_COMM_ERRORS 5096
extern u_int32_t TCP3_COMM_ERRORS;
int doWrite_TCP3_COMM_ERRORS(u_int32_t value);
int addWrite_TCP3_COMM_ERRORS(u_int32_t value);
int getStatus_TCP3_COMM_ERRORS(void);

#define ID_TCP3_LAST_ERROR 5097
extern u_int32_t TCP3_LAST_ERROR;
int doWrite_TCP3_LAST_ERROR(u_int32_t value);
int addWrite_TCP3_LAST_ERROR(u_int32_t value);
int getStatus_TCP3_LAST_ERROR(void);

#define ID_TCP3_WRITE_QUEUE 5098
extern u_int32_t TCP3_WRITE_QUEUE;
int doWrite_TCP3_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP3_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP3_WRITE_QUEUE(void);

#define ID_TCP3_BUS_LOAD 5099
extern u_int32_t TCP3_BUS_LOAD;
int doWrite_TCP3_BUS_LOAD(u_int32_t value);
int addWrite_TCP3_BUS_LOAD(u_int32_t value);
int getStatus_TCP3_BUS_LOAD(void);

#define ID_TCP4_TYPE_PORT 5100
extern u_int32_t TCP4_TYPE_PORT;
int doWrite_TCP4_TYPE_PORT(u_int32_t value);
int addWrite_TCP4_TYPE_PORT(u_int32_t value);
int getStatus_TCP4_TYPE_PORT(void);

#define ID_TCP4_IP_ADDRESS 5101
extern u_int32_t TCP4_IP_ADDRESS;
int doWrite_TCP4_IP_ADDRESS(u_int32_t value);
int addWrite_TCP4_IP_ADDRESS(u_int32_t value);
int getStatus_TCP4_IP_ADDRESS(void);

#define ID_TCP4_STATUS 5102
extern u_int32_t TCP4_STATUS;
int doWrite_TCP4_STATUS(u_int32_t value);
int addWrite_TCP4_STATUS(u_int32_t value);
int getStatus_TCP4_STATUS(void);

#define ID_TCP4_READS 5103
extern u_int32_t TCP4_READS;
int doWrite_TCP4_READS(u_int32_t value);
int addWrite_TCP4_READS(u_int32_t value);
int getStatus_TCP4_READS(void);

#define ID_TCP4_WRITES 5104
extern u_int32_t TCP4_WRITES;
int doWrite_TCP4_WRITES(u_int32_t value);
int addWrite_TCP4_WRITES(u_int32_t value);
int getStatus_TCP4_WRITES(void);

#define ID_TCP4_TIMEOUTS 5105
extern u_int32_t TCP4_TIMEOUTS;
int doWrite_TCP4_TIMEOUTS(u_int32_t value);
int addWrite_TCP4_TIMEOUTS(u_int32_t value);
int getStatus_TCP4_TIMEOUTS(void);

#define ID_TCP4_COMM_ERRORS 5106
extern u_int32_t TCP4_COMM_ERRORS;
int doWrite_TCP4_COMM_ERRORS(u_int32_t value);
int addWrite_TCP4_COMM_ERRORS(u_int32_t value);
int getStatus_TCP4_COMM_ERRORS(void);

#define ID_TCP4_LAST_ERROR 5107
extern u_int32_t TCP4_LAST_ERROR;
int doWrite_TCP4_LAST_ERROR(u_int32_t value);
int addWrite_TCP4_LAST_ERROR(u_int32_t value);
int getStatus_TCP4_LAST_ERROR(void);

#define ID_TCP4_WRITE_QUEUE 5108
extern u_int32_t TCP4_WRITE_QUEUE;
int doWrite_TCP4_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP4_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP4_WRITE_QUEUE(void);

#define ID_TCP4_BUS_LOAD 5109
extern u_int32_t TCP4_BUS_LOAD;
int doWrite_TCP4_BUS_LOAD(u_int32_t value);
int addWrite_TCP4_BUS_LOAD(u_int32_t value);
int getStatus_TCP4_BUS_LOAD(void);

#define ID_TCP5_TYPE_PORT 5110
extern u_int32_t TCP5_TYPE_PORT;
int doWrite_TCP5_TYPE_PORT(u_int32_t value);
int addWrite_TCP5_TYPE_PORT(u_int32_t value);
int getStatus_TCP5_TYPE_PORT(void);

#define ID_TCP5_IP_ADDRESS 5111
extern u_int32_t TCP5_IP_ADDRESS;
int doWrite_TCP5_IP_ADDRESS(u_int32_t value);
int addWrite_TCP5_IP_ADDRESS(u_int32_t value);
int getStatus_TCP5_IP_ADDRESS(void);

#define ID_TCP5_STATUS 5112
extern u_int32_t TCP5_STATUS;
int doWrite_TCP5_STATUS(u_int32_t value);
int addWrite_TCP5_STATUS(u_int32_t value);
int getStatus_TCP5_STATUS(void);

#define ID_TCP5_READS 5113
extern u_int32_t TCP5_READS;
int doWrite_TCP5_READS(u_int32_t value);
int addWrite_TCP5_READS(u_int32_t value);
int getStatus_TCP5_READS(void);

#define ID_TCP5_WRITES 5114
extern u_int32_t TCP5_WRITES;
int doWrite_TCP5_WRITES(u_int32_t value);
int addWrite_TCP5_WRITES(u_int32_t value);
int getStatus_TCP5_WRITES(void);

#define ID_TCP5_TIMEOUTS 5115
extern u_int32_t TCP5_TIMEOUTS;
int doWrite_TCP5_TIMEOUTS(u_int32_t value);
int addWrite_TCP5_TIMEOUTS(u_int32_t value);
int getStatus_TCP5_TIMEOUTS(void);

#define ID_TCP5_COMM_ERRORS 5116
extern u_int32_t TCP5_COMM_ERRORS;
int doWrite_TCP5_COMM_ERRORS(u_int32_t value);
int addWrite_TCP5_COMM_ERRORS(u_int32_t value);
int getStatus_TCP5_COMM_ERRORS(void);

#define ID_TCP5_LAST_ERROR 5117
extern u_int32_t TCP5_LAST_ERROR;
int doWrite_TCP5_LAST_ERROR(u_int32_t value);
int addWrite_TCP5_LAST_ERROR(u_int32_t value);
int getStatus_TCP5_LAST_ERROR(void);

#define ID_TCP5_WRITE_QUEUE 5118
extern u_int32_t TCP5_WRITE_QUEUE;
int doWrite_TCP5_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP5_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP5_WRITE_QUEUE(void);

#define ID_TCP5_BUS_LOAD 5119
extern u_int32_t TCP5_BUS_LOAD;
int doWrite_TCP5_BUS_LOAD(u_int32_t value);
int addWrite_TCP5_BUS_LOAD(u_int32_t value);
int getStatus_TCP5_BUS_LOAD(void);

#define ID_TCP6_TYPE_PORT 5120
extern u_int32_t TCP6_TYPE_PORT;
int doWrite_TCP6_TYPE_PORT(u_int32_t value);
int addWrite_TCP6_TYPE_PORT(u_int32_t value);
int getStatus_TCP6_TYPE_PORT(void);

#define ID_TCP6_IP_ADDRESS 5121
extern u_int32_t TCP6_IP_ADDRESS;
int doWrite_TCP6_IP_ADDRESS(u_int32_t value);
int addWrite_TCP6_IP_ADDRESS(u_int32_t value);
int getStatus_TCP6_IP_ADDRESS(void);

#define ID_TCP6_STATUS 5122
extern u_int32_t TCP6_STATUS;
int doWrite_TCP6_STATUS(u_int32_t value);
int addWrite_TCP6_STATUS(u_int32_t value);
int getStatus_TCP6_STATUS(void);

#define ID_TCP6_READS 5123
extern u_int32_t TCP6_READS;
int doWrite_TCP6_READS(u_int32_t value);
int addWrite_TCP6_READS(u_int32_t value);
int getStatus_TCP6_READS(void);

#define ID_TCP6_WRITES 5124
extern u_int32_t TCP6_WRITES;
int doWrite_TCP6_WRITES(u_int32_t value);
int addWrite_TCP6_WRITES(u_int32_t value);
int getStatus_TCP6_WRITES(void);

#define ID_TCP6_TIMEOUTS 5125
extern u_int32_t TCP6_TIMEOUTS;
int doWrite_TCP6_TIMEOUTS(u_int32_t value);
int addWrite_TCP6_TIMEOUTS(u_int32_t value);
int getStatus_TCP6_TIMEOUTS(void);

#define ID_TCP6_COMM_ERRORS 5126
extern u_int32_t TCP6_COMM_ERRORS;
int doWrite_TCP6_COMM_ERRORS(u_int32_t value);
int addWrite_TCP6_COMM_ERRORS(u_int32_t value);
int getStatus_TCP6_COMM_ERRORS(void);

#define ID_TCP6_LAST_ERROR 5127
extern u_int32_t TCP6_LAST_ERROR;
int doWrite_TCP6_LAST_ERROR(u_int32_t value);
int addWrite_TCP6_LAST_ERROR(u_int32_t value);
int getStatus_TCP6_LAST_ERROR(void);

#define ID_TCP6_WRITE_QUEUE 5128
extern u_int32_t TCP6_WRITE_QUEUE;
int doWrite_TCP6_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP6_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP6_WRITE_QUEUE(void);

#define ID_TCP6_BUS_LOAD 5129
extern u_int32_t TCP6_BUS_LOAD;
int doWrite_TCP6_BUS_LOAD(u_int32_t value);
int addWrite_TCP6_BUS_LOAD(u_int32_t value);
int getStatus_TCP6_BUS_LOAD(void);

#define ID_TCP7_TYPE_PORT 5130
extern u_int32_t TCP7_TYPE_PORT;
int doWrite_TCP7_TYPE_PORT(u_int32_t value);
int addWrite_TCP7_TYPE_PORT(u_int32_t value);
int getStatus_TCP7_TYPE_PORT(void);

#define ID_TCP7_IP_ADDRESS 5131
extern u_int32_t TCP7_IP_ADDRESS;
int doWrite_TCP7_IP_ADDRESS(u_int32_t value);
int addWrite_TCP7_IP_ADDRESS(u_int32_t value);
int getStatus_TCP7_IP_ADDRESS(void);

#define ID_TCP7_STATUS 5132
extern u_int32_t TCP7_STATUS;
int doWrite_TCP7_STATUS(u_int32_t value);
int addWrite_TCP7_STATUS(u_int32_t value);
int getStatus_TCP7_STATUS(void);

#define ID_TCP7_READS 5133
extern u_int32_t TCP7_READS;
int doWrite_TCP7_READS(u_int32_t value);
int addWrite_TCP7_READS(u_int32_t value);
int getStatus_TCP7_READS(void);

#define ID_TCP7_WRITES 5134
extern u_int32_t TCP7_WRITES;
int doWrite_TCP7_WRITES(u_int32_t value);
int addWrite_TCP7_WRITES(u_int32_t value);
int getStatus_TCP7_WRITES(void);

#define ID_TCP7_TIMEOUTS 5135
extern u_int32_t TCP7_TIMEOUTS;
int doWrite_TCP7_TIMEOUTS(u_int32_t value);
int addWrite_TCP7_TIMEOUTS(u_int32_t value);
int getStatus_TCP7_TIMEOUTS(void);

#define ID_TCP7_COMM_ERRORS 5136
extern u_int32_t TCP7_COMM_ERRORS;
int doWrite_TCP7_COMM_ERRORS(u_int32_t value);
int addWrite_TCP7_COMM_ERRORS(u_int32_t value);
int getStatus_TCP7_COMM_ERRORS(void);

#define ID_TCP7_LAST_ERROR 5137
extern u_int32_t TCP7_LAST_ERROR;
int doWrite_TCP7_LAST_ERROR(u_int32_t value);
int addWrite_TCP7_LAST_ERROR(u_int32_t value);
int getStatus_TCP7_LAST_ERROR(void);

#define ID_TCP7_WRITE_QUEUE 5138
extern u_int32_t TCP7_WRITE_QUEUE;
int doWrite_TCP7_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP7_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP7_WRITE_QUEUE(void);

#define ID_TCP7_BUS_LOAD 5139
extern u_int32_t TCP7_BUS_LOAD;
int doWrite_TCP7_BUS_LOAD(u_int32_t value);
int addWrite_TCP7_BUS_LOAD(u_int32_t value);
int getStatus_TCP7_BUS_LOAD(void);

#define ID_TCP8_TYPE_PORT 5140
extern u_int32_t TCP8_TYPE_PORT;
int doWrite_TCP8_TYPE_PORT(u_int32_t value);
int addWrite_TCP8_TYPE_PORT(u_int32_t value);
int getStatus_TCP8_TYPE_PORT(void);

#define ID_TCP8_IP_ADDRESS 5141
extern u_int32_t TCP8_IP_ADDRESS;
int doWrite_TCP8_IP_ADDRESS(u_int32_t value);
int addWrite_TCP8_IP_ADDRESS(u_int32_t value);
int getStatus_TCP8_IP_ADDRESS(void);

#define ID_TCP8_STATUS 5142
extern u_int32_t TCP8_STATUS;
int doWrite_TCP8_STATUS(u_int32_t value);
int addWrite_TCP8_STATUS(u_int32_t value);
int getStatus_TCP8_STATUS(void);

#define ID_TCP8_READS 5143
extern u_int32_t TCP8_READS;
int doWrite_TCP8_READS(u_int32_t value);
int addWrite_TCP8_READS(u_int32_t value);
int getStatus_TCP8_READS(void);

#define ID_TCP8_WRITES 5144
extern u_int32_t TCP8_WRITES;
int doWrite_TCP8_WRITES(u_int32_t value);
int addWrite_TCP8_WRITES(u_int32_t value);
int getStatus_TCP8_WRITES(void);

#define ID_TCP8_TIMEOUTS 5145
extern u_int32_t TCP8_TIMEOUTS;
int doWrite_TCP8_TIMEOUTS(u_int32_t value);
int addWrite_TCP8_TIMEOUTS(u_int32_t value);
int getStatus_TCP8_TIMEOUTS(void);

#define ID_TCP8_COMM_ERRORS 5146
extern u_int32_t TCP8_COMM_ERRORS;
int doWrite_TCP8_COMM_ERRORS(u_int32_t value);
int addWrite_TCP8_COMM_ERRORS(u_int32_t value);
int getStatus_TCP8_COMM_ERRORS(void);

#define ID_TCP8_LAST_ERROR 5147
extern u_int32_t TCP8_LAST_ERROR;
int doWrite_TCP8_LAST_ERROR(u_int32_t value);
int addWrite_TCP8_LAST_ERROR(u_int32_t value);
int getStatus_TCP8_LAST_ERROR(void);

#define ID_TCP8_WRITE_QUEUE 5148
extern u_int32_t TCP8_WRITE_QUEUE;
int doWrite_TCP8_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP8_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP8_WRITE_QUEUE(void);

#define ID_TCP8_BUS_LOAD 5149
extern u_int32_t TCP8_BUS_LOAD;
int doWrite_TCP8_BUS_LOAD(u_int32_t value);
int addWrite_TCP8_BUS_LOAD(u_int32_t value);
int getStatus_TCP8_BUS_LOAD(void);

#define ID_TCP9_TYPE_PORT 5150
extern u_int32_t TCP9_TYPE_PORT;
int doWrite_TCP9_TYPE_PORT(u_int32_t value);
int addWrite_TCP9_TYPE_PORT(u_int32_t value);
int getStatus_TCP9_TYPE_PORT(void);

#define ID_TCP9_IP_ADDRESS 5151
extern u_int32_t TCP9_IP_ADDRESS;
int doWrite_TCP9_IP_ADDRESS(u_int32_t value);
int addWrite_TCP9_IP_ADDRESS(u_int32_t value);
int getStatus_TCP9_IP_ADDRESS(void);

#define ID_TCP9_STATUS 5152
extern u_int32_t TCP9_STATUS;
int doWrite_TCP9_STATUS(u_int32_t value);
int addWrite_TCP9_STATUS(u_int32_t value);
int getStatus_TCP9_STATUS(void);

#define ID_TCP9_READS 5153
extern u_int32_t TCP9_READS;
int doWrite_TCP9_READS(u_int32_t value);
int addWrite_TCP9_READS(u_int32_t value);
int getStatus_TCP9_READS(void);

#define ID_TCP9_WRITES 5154
extern u_int32_t TCP9_WRITES;
int doWrite_TCP9_WRITES(u_int32_t value);
int addWrite_TCP9_WRITES(u_int32_t value);
int getStatus_TCP9_WRITES(void);

#define ID_TCP9_TIMEOUTS 5155
extern u_int32_t TCP9_TIMEOUTS;
int doWrite_TCP9_TIMEOUTS(u_int32_t value);
int addWrite_TCP9_TIMEOUTS(u_int32_t value);
int getStatus_TCP9_TIMEOUTS(void);

#define ID_TCP9_COMM_ERRORS 5156
extern u_int32_t TCP9_COMM_ERRORS;
int doWrite_TCP9_COMM_ERRORS(u_int32_t value);
int addWrite_TCP9_COMM_ERRORS(u_int32_t value);
int getStatus_TCP9_COMM_ERRORS(void);

#define ID_TCP9_LAST_ERROR 5157
extern u_int32_t TCP9_LAST_ERROR;
int doWrite_TCP9_LAST_ERROR(u_int32_t value);
int addWrite_TCP9_LAST_ERROR(u_int32_t value);
int getStatus_TCP9_LAST_ERROR(void);

#define ID_TCP9_WRITE_QUEUE 5158
extern u_int32_t TCP9_WRITE_QUEUE;
int doWrite_TCP9_WRITE_QUEUE(u_int32_t value);
int addWrite_TCP9_WRITE_QUEUE(u_int32_t value);
int getStatus_TCP9_WRITE_QUEUE(void);

#define ID_TCP9_BUS_LOAD 5159
extern u_int32_t TCP9_BUS_LOAD;
int doWrite_TCP9_BUS_LOAD(u_int32_t value);
int addWrite_TCP9_BUS_LOAD(u_int32_t value);
int getStatus_TCP9_BUS_LOAD(void);

#define ID_NODE_01_DEV_NODE 5172
extern u_int32_t NODE_01_DEV_NODE;
int doWrite_NODE_01_DEV_NODE(u_int32_t value);
int addWrite_NODE_01_DEV_NODE(u_int32_t value);
int getStatus_NODE_01_DEV_NODE(void);

#define ID_NODE_01_STATUS 5173
extern u_int32_t NODE_01_STATUS;
int doWrite_NODE_01_STATUS(u_int32_t value);
int addWrite_NODE_01_STATUS(u_int32_t value);
int getStatus_NODE_01_STATUS(void);

#define ID_NODE_02_DEV_NODE 5174
extern u_int32_t NODE_02_DEV_NODE;
int doWrite_NODE_02_DEV_NODE(u_int32_t value);
int addWrite_NODE_02_DEV_NODE(u_int32_t value);
int getStatus_NODE_02_DEV_NODE(void);

#define ID_NODE_02_STATUS 5175
extern u_int32_t NODE_02_STATUS;
int doWrite_NODE_02_STATUS(u_int32_t value);
int addWrite_NODE_02_STATUS(u_int32_t value);
int getStatus_NODE_02_STATUS(void);

#define ID_NODE_03_DEV_NODE 5176
extern u_int32_t NODE_03_DEV_NODE;
int doWrite_NODE_03_DEV_NODE(u_int32_t value);
int addWrite_NODE_03_DEV_NODE(u_int32_t value);
int getStatus_NODE_03_DEV_NODE(void);

#define ID_NODE_03_STATUS 5177
extern u_int32_t NODE_03_STATUS;
int doWrite_NODE_03_STATUS(u_int32_t value);
int addWrite_NODE_03_STATUS(u_int32_t value);
int getStatus_NODE_03_STATUS(void);

#define ID_NODE_04_DEV_NODE 5178
extern u_int32_t NODE_04_DEV_NODE;
int doWrite_NODE_04_DEV_NODE(u_int32_t value);
int addWrite_NODE_04_DEV_NODE(u_int32_t value);
int getStatus_NODE_04_DEV_NODE(void);

#define ID_NODE_04_STATUS 5179
extern u_int32_t NODE_04_STATUS;
int doWrite_NODE_04_STATUS(u_int32_t value);
int addWrite_NODE_04_STATUS(u_int32_t value);
int getStatus_NODE_04_STATUS(void);

#define ID_NODE_05_DEV_NODE 5180
extern u_int32_t NODE_05_DEV_NODE;
int doWrite_NODE_05_DEV_NODE(u_int32_t value);
int addWrite_NODE_05_DEV_NODE(u_int32_t value);
int getStatus_NODE_05_DEV_NODE(void);

#define ID_NODE_05_STATUS 5181
extern u_int32_t NODE_05_STATUS;
int doWrite_NODE_05_STATUS(u_int32_t value);
int addWrite_NODE_05_STATUS(u_int32_t value);
int getStatus_NODE_05_STATUS(void);

#define ID_NODE_06_DEV_NODE 5182
extern u_int32_t NODE_06_DEV_NODE;
int doWrite_NODE_06_DEV_NODE(u_int32_t value);
int addWrite_NODE_06_DEV_NODE(u_int32_t value);
int getStatus_NODE_06_DEV_NODE(void);

#define ID_NODE_06_STATUS 5183
extern u_int32_t NODE_06_STATUS;
int doWrite_NODE_06_STATUS(u_int32_t value);
int addWrite_NODE_06_STATUS(u_int32_t value);
int getStatus_NODE_06_STATUS(void);

#define ID_NODE_07_DEV_NODE 5184
extern u_int32_t NODE_07_DEV_NODE;
int doWrite_NODE_07_DEV_NODE(u_int32_t value);
int addWrite_NODE_07_DEV_NODE(u_int32_t value);
int getStatus_NODE_07_DEV_NODE(void);

#define ID_NODE_07_STATUS 5185
extern u_int32_t NODE_07_STATUS;
int doWrite_NODE_07_STATUS(u_int32_t value);
int addWrite_NODE_07_STATUS(u_int32_t value);
int getStatus_NODE_07_STATUS(void);

#define ID_NODE_08_DEV_NODE 5186
extern u_int32_t NODE_08_DEV_NODE;
int doWrite_NODE_08_DEV_NODE(u_int32_t value);
int addWrite_NODE_08_DEV_NODE(u_int32_t value);
int getStatus_NODE_08_DEV_NODE(void);

#define ID_NODE_08_STATUS 5187
extern u_int32_t NODE_08_STATUS;
int doWrite_NODE_08_STATUS(u_int32_t value);
int addWrite_NODE_08_STATUS(u_int32_t value);
int getStatus_NODE_08_STATUS(void);

#define ID_NODE_09_DEV_NODE 5188
extern u_int32_t NODE_09_DEV_NODE;
int doWrite_NODE_09_DEV_NODE(u_int32_t value);
int addWrite_NODE_09_DEV_NODE(u_int32_t value);
int getStatus_NODE_09_DEV_NODE(void);

#define ID_NODE_09_STATUS 5189
extern u_int32_t NODE_09_STATUS;
int doWrite_NODE_09_STATUS(u_int32_t value);
int addWrite_NODE_09_STATUS(u_int32_t value);
int getStatus_NODE_09_STATUS(void);

#define ID_NODE_10_DEV_NODE 5190
extern u_int32_t NODE_10_DEV_NODE;
int doWrite_NODE_10_DEV_NODE(u_int32_t value);
int addWrite_NODE_10_DEV_NODE(u_int32_t value);
int getStatus_NODE_10_DEV_NODE(void);

#define ID_NODE_10_STATUS 5191
extern u_int32_t NODE_10_STATUS;
int doWrite_NODE_10_STATUS(u_int32_t value);
int addWrite_NODE_10_STATUS(u_int32_t value);
int getStatus_NODE_10_STATUS(void);

#define ID_NODE_11_DEV_NODE 5192
extern u_int32_t NODE_11_DEV_NODE;
int doWrite_NODE_11_DEV_NODE(u_int32_t value);
int addWrite_NODE_11_DEV_NODE(u_int32_t value);
int getStatus_NODE_11_DEV_NODE(void);

#define ID_NODE_11_STATUS 5193
extern u_int32_t NODE_11_STATUS;
int doWrite_NODE_11_STATUS(u_int32_t value);
int addWrite_NODE_11_STATUS(u_int32_t value);
int getStatus_NODE_11_STATUS(void);

#define ID_NODE_12_DEV_NODE 5194
extern u_int32_t NODE_12_DEV_NODE;
int doWrite_NODE_12_DEV_NODE(u_int32_t value);
int addWrite_NODE_12_DEV_NODE(u_int32_t value);
int getStatus_NODE_12_DEV_NODE(void);

#define ID_NODE_12_STATUS 5195
extern u_int32_t NODE_12_STATUS;
int doWrite_NODE_12_STATUS(u_int32_t value);
int addWrite_NODE_12_STATUS(u_int32_t value);
int getStatus_NODE_12_STATUS(void);

#define ID_NODE_13_DEV_NODE 5196
extern u_int32_t NODE_13_DEV_NODE;
int doWrite_NODE_13_DEV_NODE(u_int32_t value);
int addWrite_NODE_13_DEV_NODE(u_int32_t value);
int getStatus_NODE_13_DEV_NODE(void);

#define ID_NODE_13_STATUS 5197
extern u_int32_t NODE_13_STATUS;
int doWrite_NODE_13_STATUS(u_int32_t value);
int addWrite_NODE_13_STATUS(u_int32_t value);
int getStatus_NODE_13_STATUS(void);

#define ID_NODE_14_DEV_NODE 5198
extern u_int32_t NODE_14_DEV_NODE;
int doWrite_NODE_14_DEV_NODE(u_int32_t value);
int addWrite_NODE_14_DEV_NODE(u_int32_t value);
int getStatus_NODE_14_DEV_NODE(void);

#define ID_NODE_14_STATUS 5199
extern u_int32_t NODE_14_STATUS;
int doWrite_NODE_14_STATUS(u_int32_t value);
int addWrite_NODE_14_STATUS(u_int32_t value);
int getStatus_NODE_14_STATUS(void);

#define ID_NODE_15_DEV_NODE 5200
extern u_int32_t NODE_15_DEV_NODE;
int doWrite_NODE_15_DEV_NODE(u_int32_t value);
int addWrite_NODE_15_DEV_NODE(u_int32_t value);
int getStatus_NODE_15_DEV_NODE(void);

#define ID_NODE_15_STATUS 5201
extern u_int32_t NODE_15_STATUS;
int doWrite_NODE_15_STATUS(u_int32_t value);
int addWrite_NODE_15_STATUS(u_int32_t value);
int getStatus_NODE_15_STATUS(void);

#define ID_NODE_16_DEV_NODE 5202
extern u_int32_t NODE_16_DEV_NODE;
int doWrite_NODE_16_DEV_NODE(u_int32_t value);
int addWrite_NODE_16_DEV_NODE(u_int32_t value);
int getStatus_NODE_16_DEV_NODE(void);

#define ID_NODE_16_STATUS 5203
extern u_int32_t NODE_16_STATUS;
int doWrite_NODE_16_STATUS(u_int32_t value);
int addWrite_NODE_16_STATUS(u_int32_t value);
int getStatus_NODE_16_STATUS(void);

#define ID_PLC_DigIn_1 5300
extern int PLC_DigIn_1;	/* Digital input 1 value */
int doWrite_PLC_DigIn_1(int value);
int addWrite_PLC_DigIn_1(int value);
int getStatus_PLC_DigIn_1(void);

#define ID_PLC_DigIn_2 5301
extern int PLC_DigIn_2;	/* Digital input 2 value */
int doWrite_PLC_DigIn_2(int value);
int addWrite_PLC_DigIn_2(int value);
int getStatus_PLC_DigIn_2(void);

#define ID_PLC_DigIn_3 5302
extern int PLC_DigIn_3;	/* Digital input 3 value */
int doWrite_PLC_DigIn_3(int value);
int addWrite_PLC_DigIn_3(int value);
int getStatus_PLC_DigIn_3(void);

#define ID_PLC_DigIn_4 5303
extern int PLC_DigIn_4;	/* Digital input 4 value */
int doWrite_PLC_DigIn_4(int value);
int addWrite_PLC_DigIn_4(int value);
int getStatus_PLC_DigIn_4(void);

#define ID_PLC_DigIn_5 5304
extern int PLC_DigIn_5;	/* Digital input 5 value */
int doWrite_PLC_DigIn_5(int value);
int addWrite_PLC_DigIn_5(int value);
int getStatus_PLC_DigIn_5(void);

#define ID_PLC_DigIn_6 5305
extern int PLC_DigIn_6;	/* Digital input 6 value */
int doWrite_PLC_DigIn_6(int value);
int addWrite_PLC_DigIn_6(int value);
int getStatus_PLC_DigIn_6(void);

#define ID_PLC_DigIn_7 5306
extern int PLC_DigIn_7;	/* Digital input 7 value */
int doWrite_PLC_DigIn_7(int value);
int addWrite_PLC_DigIn_7(int value);
int getStatus_PLC_DigIn_7(void);

#define ID_PLC_DigIn_8 5307
extern int PLC_DigIn_8;	/* Digital input 8 value */
int doWrite_PLC_DigIn_8(int value);
int addWrite_PLC_DigIn_8(int value);
int getStatus_PLC_DigIn_8(void);

#define ID_PLC_Reserved_1 5308
extern int PLC_Reserved_1;	/* Reserved */
int doWrite_PLC_Reserved_1(int value);
int addWrite_PLC_Reserved_1(int value);
int getStatus_PLC_Reserved_1(void);

#define ID_PLC_DigOut_1 5309
extern int PLC_DigOut_1;	/* Digital output 1 value */
int doWrite_PLC_DigOut_1(int value);
int addWrite_PLC_DigOut_1(int value);
int getStatus_PLC_DigOut_1(void);

#define ID_PLC_DigOut_2 5310
extern int PLC_DigOut_2;	/* Digital output 2 value */
int doWrite_PLC_DigOut_2(int value);
int addWrite_PLC_DigOut_2(int value);
int getStatus_PLC_DigOut_2(void);

#define ID_PLC_DigOut_3 5311
extern int PLC_DigOut_3;	/* Digital output 3 value */
int doWrite_PLC_DigOut_3(int value);
int addWrite_PLC_DigOut_3(int value);
int getStatus_PLC_DigOut_3(void);

#define ID_PLC_DigOut_4 5312
extern int PLC_DigOut_4;	/* Digital output 4 value */
int doWrite_PLC_DigOut_4(int value);
int addWrite_PLC_DigOut_4(int value);
int getStatus_PLC_DigOut_4(void);

#define ID_PLC_DigOut_5 5313
extern int PLC_DigOut_5;	/* Digital output 5 value */
int doWrite_PLC_DigOut_5(int value);
int addWrite_PLC_DigOut_5(int value);
int getStatus_PLC_DigOut_5(void);

#define ID_PLC_DigOut_6 5314
extern int PLC_DigOut_6;	/* Digital output 6 value */
int doWrite_PLC_DigOut_6(int value);
int addWrite_PLC_DigOut_6(int value);
int getStatus_PLC_DigOut_6(void);

#define ID_PLC_DigOut_7 5315
extern int PLC_DigOut_7;	/* Digital output 7 value */
int doWrite_PLC_DigOut_7(int value);
int addWrite_PLC_DigOut_7(int value);
int getStatus_PLC_DigOut_7(void);

#define ID_PLC_DigOut_8 5316
extern int PLC_DigOut_8;	/* Digital output 8 value */
int doWrite_PLC_DigOut_8(int value);
int addWrite_PLC_DigOut_8(int value);
int getStatus_PLC_DigOut_8(void);

#define ID_PLC_DigOut_9 5317
extern int PLC_DigOut_9;	/* Digital output 9 value */
int doWrite_PLC_DigOut_9(int value);
int addWrite_PLC_DigOut_9(int value);
int getStatus_PLC_DigOut_9(void);

#define ID_PLC_DigOut_10 5318
extern int PLC_DigOut_10;	/* Digital output 10 value */
int doWrite_PLC_DigOut_10(int value);
int addWrite_PLC_DigOut_10(int value);
int getStatus_PLC_DigOut_10(void);

#define ID_PLC_DigOut_11 5319
extern int PLC_DigOut_11;	/* Digital output 11 value */
int doWrite_PLC_DigOut_11(int value);
int addWrite_PLC_DigOut_11(int value);
int getStatus_PLC_DigOut_11(void);

#define ID_PLC_DigOut_12 5320
extern int PLC_DigOut_12;	/* Digital output 12 value */
int doWrite_PLC_DigOut_12(int value);
int addWrite_PLC_DigOut_12(int value);
int getStatus_PLC_DigOut_12(void);

#define ID_PLC_Hwconf 5321
extern u_int16_t PLC_Hwconf;	/* Hardware configuration */
int doWrite_PLC_Hwconf(u_int16_t value);
int addWrite_PLC_Hwconf(u_int16_t value);
int getStatus_PLC_Hwconf(void);

#define ID_PLC_Revisione 5322
extern u_int16_t PLC_Revisione;	/* Firmware version */
int doWrite_PLC_Revisione(u_int16_t value);
int addWrite_PLC_Revisione(u_int16_t value);
int getStatus_PLC_Revisione(void);

#define ID_PLC_StatusReg 5323
extern u_int16_t PLC_StatusReg;	/* In - Out board status */
int doWrite_PLC_StatusReg(u_int16_t value);
int addWrite_PLC_StatusReg(u_int16_t value);
int getStatus_PLC_StatusReg(void);

#define ID_PLC_Heartbeat 5324
extern u_int16_t PLC_Heartbeat;	/* In - Out board function check */
int doWrite_PLC_Heartbeat(u_int16_t value);
int addWrite_PLC_Heartbeat(u_int16_t value);
int getStatus_PLC_Heartbeat(void);

#define ID_PLC_AnIn_1 5325
extern int16_t PLC_AnIn_1;	/* Analog input 1 value */
int doWrite_PLC_AnIn_1(int16_t value);
int addWrite_PLC_AnIn_1(int16_t value);
int getStatus_PLC_AnIn_1(void);

#define ID_PLC_AnIn_2 5326
extern int16_t PLC_AnIn_2;	/* Analog input 2 value */
int doWrite_PLC_AnIn_2(int16_t value);
int addWrite_PLC_AnIn_2(int16_t value);
int getStatus_PLC_AnIn_2(void);

#define ID_PLC_AnIn_3 5327
extern int16_t PLC_AnIn_3;	/* Analog input 3 value */
int doWrite_PLC_AnIn_3(int16_t value);
int addWrite_PLC_AnIn_3(int16_t value);
int getStatus_PLC_AnIn_3(void);

#define ID_PLC_AnIn_4 5328
extern int16_t PLC_AnIn_4;	/* Analog input 4 value */
int doWrite_PLC_AnIn_4(int16_t value);
int addWrite_PLC_AnIn_4(int16_t value);
int getStatus_PLC_AnIn_4(void);

#define ID_PLC_EncoderCo_Lo 5329
extern u_int16_t PLC_EncoderCo_Lo;	/* Encoder reading (LOW) */
int doWrite_PLC_EncoderCo_Lo(u_int16_t value);
int addWrite_PLC_EncoderCo_Lo(u_int16_t value);
int getStatus_PLC_EncoderCo_Lo(void);

#define ID_PLC_EncoderCo_Hi 5330
extern u_int16_t PLC_EncoderCo_Hi;	/* Encoder reading (HIGH) */
int doWrite_PLC_EncoderCo_Hi(u_int16_t value);
int addWrite_PLC_EncoderCo_Hi(u_int16_t value);
int getStatus_PLC_EncoderCo_Hi(void);

#define ID_PLC_CaptureT1_Lo 5331
extern u_int16_t PLC_CaptureT1_Lo;	/* Time between 2 input edges (LOW) */
int doWrite_PLC_CaptureT1_Lo(u_int16_t value);
int addWrite_PLC_CaptureT1_Lo(u_int16_t value);
int getStatus_PLC_CaptureT1_Lo(void);

#define ID_PLC_CaptureT1_Hi 5332
extern u_int16_t PLC_CaptureT1_Hi;	/* Time between 2 input edges (HIGH) */
int doWrite_PLC_CaptureT1_Hi(u_int16_t value);
int addWrite_PLC_CaptureT1_Hi(u_int16_t value);
int getStatus_PLC_CaptureT1_Hi(void);

#define ID_PLC_CaptureT2_Lo 5333
extern u_int16_t PLC_CaptureT2_Lo;	/* Time between 2 input edges (LOW) */
int doWrite_PLC_CaptureT2_Lo(u_int16_t value);
int addWrite_PLC_CaptureT2_Lo(u_int16_t value);
int getStatus_PLC_CaptureT2_Lo(void);

#define ID_PLC_CaptureT2_Hi 5334
extern u_int16_t PLC_CaptureT2_Hi;	/* Time between 2 input edges (HIGH) */
int doWrite_PLC_CaptureT2_Hi(u_int16_t value);
int addWrite_PLC_CaptureT2_Hi(u_int16_t value);
int getStatus_PLC_CaptureT2_Hi(void);

#define ID_PLC_RPM 5335
extern u_int16_t PLC_RPM;	/* RPM input */
int doWrite_PLC_RPM(u_int16_t value);
int addWrite_PLC_RPM(u_int16_t value);
int getStatus_PLC_RPM(void);

#define ID_PLC_Tamb 5336
extern int16_t PLC_Tamb;	/* Cold junction compensation value */
int doWrite_PLC_Tamb(int16_t value);
int addWrite_PLC_Tamb(int16_t value);
int getStatus_PLC_Tamb(void);

#define ID_PLC_EnableEnc 5337
extern u_int16_t PLC_EnableEnc;	/* Encoder - counter enable */
int doWrite_PLC_EnableEnc(u_int16_t value);
int addWrite_PLC_EnableEnc(u_int16_t value);
int getStatus_PLC_EnableEnc(void);

#define ID_PLC_ResetCount 5338
extern u_int16_t PLC_ResetCount;	/* Encoder reset */
int doWrite_PLC_ResetCount(u_int16_t value);
int addWrite_PLC_ResetCount(u_int16_t value);
int getStatus_PLC_ResetCount(void);

#define ID_PLC_AnInConf_1 5339
extern u_int16_t PLC_AnInConf_1;	/* Analog input 1 configuration */
int doWrite_PLC_AnInConf_1(u_int16_t value);
int addWrite_PLC_AnInConf_1(u_int16_t value);
int getStatus_PLC_AnInConf_1(void);

#define ID_PLC_AnInConf_2 5340
extern u_int16_t PLC_AnInConf_2;	/* Analog input 2 configuration */
int doWrite_PLC_AnInConf_2(u_int16_t value);
int addWrite_PLC_AnInConf_2(u_int16_t value);
int getStatus_PLC_AnInConf_2(void);

#define ID_PLC_AnInConf_3 5341
extern u_int16_t PLC_AnInConf_3;	/* Analog input 3 configuration */
int doWrite_PLC_AnInConf_3(u_int16_t value);
int addWrite_PLC_AnInConf_3(u_int16_t value);
int getStatus_PLC_AnInConf_3(void);

#define ID_PLC_AnInConf_4 5342
extern u_int16_t PLC_AnInConf_4;	/* Analog input 4 configuration */
int doWrite_PLC_AnInConf_4(u_int16_t value);
int addWrite_PLC_AnInConf_4(u_int16_t value);
int getStatus_PLC_AnInConf_4(void);

#define ID_PLC_AnOutConf_1 5343
extern u_int16_t PLC_AnOutConf_1;	/* Analog output 1 configuration */
int doWrite_PLC_AnOutConf_1(u_int16_t value);
int addWrite_PLC_AnOutConf_1(u_int16_t value);
int getStatus_PLC_AnOutConf_1(void);

#define ID_PLC_AnOutConf_2 5344
extern u_int16_t PLC_AnOutConf_2;	/* Analog output 2 configuration */
int doWrite_PLC_AnOutConf_2(u_int16_t value);
int addWrite_PLC_AnOutConf_2(u_int16_t value);
int getStatus_PLC_AnOutConf_2(void);

#define ID_PLC_Reserved_2 5345
extern u_int16_t PLC_Reserved_2;	/* Reserved */
int doWrite_PLC_Reserved_2(u_int16_t value);
int addWrite_PLC_Reserved_2(u_int16_t value);
int getStatus_PLC_Reserved_2(void);

#define ID_PLC_Reserved_3 5346
extern u_int16_t PLC_Reserved_3;	/* Reserved */
int doWrite_PLC_Reserved_3(u_int16_t value);
int addWrite_PLC_Reserved_3(u_int16_t value);
int getStatus_PLC_Reserved_3(void);

#define ID_PLC_AnOut_1 5347
extern int16_t PLC_AnOut_1;	/* Analog output 1 value */
int doWrite_PLC_AnOut_1(int16_t value);
int addWrite_PLC_AnOut_1(int16_t value);
int getStatus_PLC_AnOut_1(void);

#define ID_PLC_AnOut_2 5348
extern int16_t PLC_AnOut_2;	/* Analog output 2 value */
int doWrite_PLC_AnOut_2(int16_t value);
int addWrite_PLC_AnOut_2(int16_t value);
int getStatus_PLC_AnOut_2(void);

#define ID_PLC_Reserved_4 5349
extern int16_t PLC_Reserved_4;	/* Reserved */
int doWrite_PLC_Reserved_4(int16_t value);
int addWrite_PLC_Reserved_4(int16_t value);
int getStatus_PLC_Reserved_4(void);

#define ID_PLC_Reserved_5 5350
extern int16_t PLC_Reserved_5;	/* Reserved */
int doWrite_PLC_Reserved_5(int16_t value);
int addWrite_PLC_Reserved_5(int16_t value);
int getStatus_PLC_Reserved_5(void);

#define ID_PLC_FiltAnIn_1 5351
extern u_int16_t PLC_FiltAnIn_1;	/* Analog input 1 filter */
int doWrite_PLC_FiltAnIn_1(u_int16_t value);
int addWrite_PLC_FiltAnIn_1(u_int16_t value);
int getStatus_PLC_FiltAnIn_1(void);

#define ID_PLC_FiltAnIn_2 5352
extern u_int16_t PLC_FiltAnIn_2;	/* Analog input 2 filter */
int doWrite_PLC_FiltAnIn_2(u_int16_t value);
int addWrite_PLC_FiltAnIn_2(u_int16_t value);
int getStatus_PLC_FiltAnIn_2(void);

#define ID_PLC_FiltAnIn_3 5353
extern u_int16_t PLC_FiltAnIn_3;	/* Analog input 3 filter */
int doWrite_PLC_FiltAnIn_3(u_int16_t value);
int addWrite_PLC_FiltAnIn_3(u_int16_t value);
int getStatus_PLC_FiltAnIn_3(void);

#define ID_PLC_FiltAnIn_4 5354
extern u_int16_t PLC_FiltAnIn_4;	/* Analog input 4 filter */
int doWrite_PLC_FiltAnIn_4(u_int16_t value);
int addWrite_PLC_FiltAnIn_4(u_int16_t value);
int getStatus_PLC_FiltAnIn_4(void);

#define ID_CH0_NETRUN 5357
extern int CH0_NETRUN;	/* Active channel */
int doWrite_CH0_NETRUN(int value);
int addWrite_CH0_NETRUN(int value);
int getStatus_CH0_NETRUN(void);

#define ID_CH0_NETGOOD 5358
extern int CH0_NETGOOD;	/* Channel configuration */
int doWrite_CH0_NETGOOD(int value);
int addWrite_CH0_NETGOOD(int value);
int getStatus_CH0_NETGOOD(void);

#define ID_CH0_NETERR 5359
extern u_int32_t CH0_NETERR;	/* Bus status */
int doWrite_CH0_NETERR(u_int32_t value);
int addWrite_CH0_NETERR(u_int32_t value);
int getStatus_CH0_NETERR(void);

#define ID_CH0_NETRST 5360
extern int CH0_NETRST;	/* Bus reset */
int doWrite_CH0_NETRST(int value);
int addWrite_CH0_NETRST(int value);
int getStatus_CH0_NETRST(void);

#define ID_CH0_NETDIS 5361
extern int CH0_NETDIS;	/* Disable the bus */
int doWrite_CH0_NETDIS(int value);
int addWrite_CH0_NETDIS(int value);
int getStatus_CH0_NETDIS(void);

#define ID_CH0_01_NODERUN 5362
extern int CH0_01_NODERUN;	/* In Out board - active channel */
int doWrite_CH0_01_NODERUN(int value);
int addWrite_CH0_01_NODERUN(int value);
int getStatus_CH0_01_NODERUN(void);

#define ID_CH0_01_NODEGOOD 5363
extern int CH0_01_NODEGOOD;	/* In Out board - channel configuration */
int doWrite_CH0_01_NODEGOOD(int value);
int addWrite_CH0_01_NODEGOOD(int value);
int getStatus_CH0_01_NODEGOOD(void);

#define ID_CH0_01_NODEERR 5364
extern u_int32_t CH0_01_NODEERR;	/* In Out board - bus status */
int doWrite_CH0_01_NODEERR(u_int32_t value);
int addWrite_CH0_01_NODEERR(u_int32_t value);
int getStatus_CH0_01_NODEERR(void);

#define ID_CH0_01_NODERST 5365
extern int CH0_01_NODERST;	/* In Out board - bus reset */
int doWrite_CH0_01_NODERST(int value);
int addWrite_CH0_01_NODERST(int value);
int getStatus_CH0_01_NODERST(void);

#define ID_CH0_01_NODEDIS 5366
extern int CH0_01_NODEDIS;	/* In Out board - disable the bus */
int doWrite_CH0_01_NODEDIS(int value);
int addWrite_CH0_01_NODEDIS(int value);
int getStatus_CH0_01_NODEDIS(void);

#define ID_PLC_time 5390
extern float PLC_time;	/* Seconds since boot (reset each 24h) */
int doWrite_PLC_time(float value);
int addWrite_PLC_time(float value);
int getStatus_PLC_time(void);

#define ID_PLC_timeMin 5391
extern float PLC_timeMin;	/* 10 seconds window start */
int doWrite_PLC_timeMin(float value);
int addWrite_PLC_timeMin(float value);
int getStatus_PLC_timeMin(void);

#define ID_PLC_timeMax 5392
extern float PLC_timeMax;	/* 10 seconds window stop */
int doWrite_PLC_timeMax(float value);
int addWrite_PLC_timeMax(float value);
int getStatus_PLC_timeMax(void);

#define ID_PLC_timeWin 5393
extern float PLC_timeWin;	/* Graph display window */
int doWrite_PLC_timeWin(float value);
int addWrite_PLC_timeWin(float value);
int getStatus_PLC_timeWin(void);

#define ID_PLC_Version 5394
extern u_int16_t PLC_Version;	/* Run Time version */
int doWrite_PLC_Version(u_int16_t value);
int addWrite_PLC_Version(u_int16_t value);
int getStatus_PLC_Version(void);

#define ID_PLC_EngineStatus 5395
extern u_int16_t PLC_EngineStatus;	/* PLC status */
int doWrite_PLC_EngineStatus(u_int16_t value);
int addWrite_PLC_EngineStatus(u_int16_t value);
int getStatus_PLC_EngineStatus(void);

#define ID_PLC_ResetValues 5396
extern int PLC_ResetValues;	/* Diagnostic variables reset */
int doWrite_PLC_ResetValues(int value);
int addWrite_PLC_ResetValues(int value);
int getStatus_PLC_ResetValues(void);

#define ID_PLC_buzzerOn 5397
extern int PLC_buzzerOn;	/* Buzzer sound (enable = 1 disable = 0) */
int doWrite_PLC_buzzerOn(int value);
int addWrite_PLC_buzzerOn(int value);
int getStatus_PLC_buzzerOn(void);

#define ID_PLC_PLC_Version 5398
extern u_int16_t PLC_PLC_Version;	/* PLC application version */
int doWrite_PLC_PLC_Version(u_int16_t value);
int addWrite_PLC_PLC_Version(u_int16_t value);
int getStatus_PLC_PLC_Version(void);

#define ID_PLC_HMI_Version 5399
extern u_int16_t PLC_HMI_Version;	/* HMI application version */
int doWrite_PLC_HMI_Version(u_int16_t value);
int addWrite_PLC_HMI_Version(u_int16_t value);
int getStatus_PLC_HMI_Version(void);

#define ID_PLC_Year 5410
extern u_int16_t PLC_Year;	/* Currently year */
int doWrite_PLC_Year(u_int16_t value);
int addWrite_PLC_Year(u_int16_t value);
int getStatus_PLC_Year(void);

#define ID_PLC_Month 5411
extern u_int16_t PLC_Month;	/* Currently month */
int doWrite_PLC_Month(u_int16_t value);
int addWrite_PLC_Month(u_int16_t value);
int getStatus_PLC_Month(void);

#define ID_PLC_Day 5412
extern u_int16_t PLC_Day;	/* Currently day */
int doWrite_PLC_Day(u_int16_t value);
int addWrite_PLC_Day(u_int16_t value);
int getStatus_PLC_Day(void);

#define ID_PLC_Hours 5413
extern u_int16_t PLC_Hours;	/* Currently hour */
int doWrite_PLC_Hours(u_int16_t value);
int addWrite_PLC_Hours(u_int16_t value);
int getStatus_PLC_Hours(void);

#define ID_PLC_Minutes 5414
extern u_int16_t PLC_Minutes;	/* Currently minutes */
int doWrite_PLC_Minutes(u_int16_t value);
int addWrite_PLC_Minutes(u_int16_t value);
int getStatus_PLC_Minutes(void);

#define ID_PLC_Seconds 5415
extern u_int16_t PLC_Seconds;	/* Currently seconds */
int doWrite_PLC_Seconds(u_int16_t value);
int addWrite_PLC_Seconds(u_int16_t value);
int getStatus_PLC_Seconds(void);

#define ID_PLC_UPTIME_s 5416
extern u_int32_t PLC_UPTIME_s;	/* Uptime in seconds (wraps in 136 years) */
int doWrite_PLC_UPTIME_s(u_int32_t value);
int addWrite_PLC_UPTIME_s(u_int32_t value);
int getStatus_PLC_UPTIME_s(void);

#define ID_PLC_UPTIME_cs 5417
extern u_int32_t PLC_UPTIME_cs;	/* Uptime in centiseconds = 10 ms (wraps in 497 days) */
int doWrite_PLC_UPTIME_cs(u_int32_t value);
int addWrite_PLC_UPTIME_cs(u_int32_t value);
int getStatus_PLC_UPTIME_cs(void);

#define ID_PLC_WATCHDOGEN 5418
extern int PLC_WATCHDOGEN;	/* Enable Watchdog */
int doWrite_PLC_WATCHDOGEN(int value);
int addWrite_PLC_WATCHDOGEN(int value);
int getStatus_PLC_WATCHDOGEN(void);

#define ID_PLC_WATCHDOG_ms 5419
extern u_int32_t PLC_WATCHDOG_ms;	/* Reset Watchdog timer */
int doWrite_PLC_WATCHDOG_ms(u_int32_t value);
int addWrite_PLC_WATCHDOG_ms(u_int32_t value);
int getStatus_PLC_WATCHDOG_ms(void);

#define ID_PLC_PRODUCT_ID 5420
extern u_int32_t PLC_PRODUCT_ID;	/* TP/TPAC/TPLC Product ID (Hex) */
int doWrite_PLC_PRODUCT_ID(u_int32_t value);
int addWrite_PLC_PRODUCT_ID(u_int32_t value);
int getStatus_PLC_PRODUCT_ID(void);

#define ID_PLC_SERIAL_NUMBER 5421
extern u_int32_t PLC_SERIAL_NUMBER;	/* TP/TPAC/TPLC Serial Number */
int doWrite_PLC_SERIAL_NUMBER(u_int32_t value);
int addWrite_PLC_SERIAL_NUMBER(u_int32_t value);
int getStatus_PLC_SERIAL_NUMBER(void);

#define ID_PLC_HMI_PAGE 5422
extern int32_t PLC_HMI_PAGE;	/* HMI Page (page100=0x00000100) */
int doWrite_PLC_HMI_PAGE(int32_t value);
int addWrite_PLC_HMI_PAGE(int32_t value);
int getStatus_PLC_HMI_PAGE(void);

#define ID_PLC_MS_VERSION 5423
extern u_int32_t PLC_MS_VERSION;	/* Mect Suite Version installed on Target (0 if before 3.4.0) */
int doWrite_PLC_MS_VERSION(u_int32_t value);
int addWrite_PLC_MS_VERSION(u_int32_t value);
int getStatus_PLC_MS_VERSION(void);

#define ID_PLC_BEEP_VOLUME 5435
extern u_int8_t PLC_BEEP_VOLUME;	/* Beep volume (when buzzerOn) */
int doWrite_PLC_BEEP_VOLUME(u_int8_t value);
int addWrite_PLC_BEEP_VOLUME(u_int8_t value);
int getStatus_PLC_BEEP_VOLUME(void);

#define ID_PLC_TOUCH_VOLUME 5436
extern u_int8_t PLC_TOUCH_VOLUME;	/* Touch volume */
int doWrite_PLC_TOUCH_VOLUME(u_int8_t value);
int addWrite_PLC_TOUCH_VOLUME(u_int8_t value);
int getStatus_PLC_TOUCH_VOLUME(void);

#define ID_PLC_ALARM_VOLUME 5437
extern u_int8_t PLC_ALARM_VOLUME;	/* Alarm volume (when alarm) */
int doWrite_PLC_ALARM_VOLUME(u_int8_t value);
int addWrite_PLC_ALARM_VOLUME(u_int8_t value);
int getStatus_PLC_ALARM_VOLUME(void);

#define ID_PLC_BUZZER 5438
extern u_int32_t PLC_BUZZER;	/* Enable dynamic buzzer sound (0x44332211 up=0x11(%) on=0x22(cs) off=0x33(cs) rep=0x44(times)) */
int doWrite_PLC_BUZZER(u_int32_t value);
int addWrite_PLC_BUZZER(u_int32_t value);
int getStatus_PLC_BUZZER(void);

#ifdef __cplusplus
}
#endif
#endif
