(*[[
]]*)
FUNCTION SetDefaultValues
#import "Crosstable.gvl"
#import "Resource1.gvl"

    test_level_01 := TEST_UNKNOWN;
    test_level_02 := TEST_UNKNOWN;
    test_level_03 := TEST_UNKNOWN;
    test_level_04 := TEST_UNKNOWN;
    test_level_05 := TEST_UNKNOWN;
    test_level_06 := TEST_UNKNOWN;
    test_level_07 := TEST_UNKNOWN;
    test_level_08 := TEST_UNKNOWN;
    test_level_09 := TEST_UNKNOWN;
    test_level_10 := TEST_UNKNOWN;
    test_level_11 := TEST_UNKNOWN;
    test_level_12 := TEST_UNKNOWN;
    test_level_13 := TEST_UNKNOWN;
    test_level_14 := TEST_UNKNOWN;
    test_level_15 := TEST_UNKNOWN;
    test_level_16 := TEST_UNKNOWN;
    test_level_17 := TEST_UNKNOWN;
    test_level_18 := TEST_UNKNOWN;
    test_level_19 := TEST_UNKNOWN;
    test_level_20 := TEST_UNKNOWN;
    test_level_21 := TEST_UNKNOWN;
    test_level_22 := TEST_UNKNOWN;
    test_level_23 := TEST_UNKNOWN;
    test_level_24 := TEST_UNKNOWN;
    test_level_25 := TEST_UNKNOWN;
    test_level_26 := TEST_UNKNOWN;
    test_level_27 := TEST_UNKNOWN;
    test_level_28 := TEST_UNKNOWN;
    test_level_29 := TEST_UNKNOWN;
    test_level_30 := TEST_UNKNOWN;
    test_level_31 := TEST_UNKNOWN;
    test_level_32 := TEST_UNKNOWN;
    test_level_33 := TEST_UNKNOWN;
    test_level_34 := TEST_UNKNOWN;
    test_level_35 := TEST_UNKNOWN;
    test_level_36 := TEST_UNKNOWN;
    test_level_37 := TEST_UNKNOWN;
    test_level_38 := TEST_UNKNOWN;
    test_level_39 := TEST_UNKNOWN;
    test_level_40 := TEST_UNKNOWN;
    test_level_41 := TEST_UNKNOWN;
    test_level_42 := TEST_UNKNOWN;
    test_level_43 := TEST_UNKNOWN;
    test_level_44 := TEST_UNKNOWN;
    test_level_45 := TEST_UNKNOWN;
    test_level_46 := TEST_UNKNOWN;
    test_level_47 := TEST_UNKNOWN;
    test_level_48 := TEST_UNKNOWN;
    test_level_49 := TEST_UNKNOWN;
    test_level_50 := TEST_UNKNOWN;
    test_level_51 := TEST_UNKNOWN;
    test_level_52 := TEST_UNKNOWN;
    test_level_53 := TEST_UNKNOWN;
    test_level_54 := TEST_UNKNOWN;
    test_level_55 := TEST_UNKNOWN;
    test_level_56 := TEST_UNKNOWN;
    test_level_57 := TEST_UNKNOWN;
    test_level_58 := TEST_UNKNOWN;
    test_level_59 := TEST_UNKNOWN;
    test_level_60 := TEST_DISABLED;

END_FUNCTION
