(*[[
]]*)
FUNCTION UpdateCounters
#import "Crosstable.gvl"
#import "Resource1.gvl"

	DisabledTests := 0;
	TestingTests := 0;
	PassedTests := 0;
	FailedTests := 0;

    UpdateCountersN(test_level_01);
    UpdateCountersN(test_level_02);
    UpdateCountersN(test_level_03);
    UpdateCountersN(test_level_04);
    UpdateCountersN(test_level_05);
    UpdateCountersN(test_level_06);
    UpdateCountersN(test_level_07);
    UpdateCountersN(test_level_08);
    UpdateCountersN(test_level_09);
    UpdateCountersN(test_level_10);
    UpdateCountersN(test_level_11);
    UpdateCountersN(test_level_12);
    UpdateCountersN(test_level_13);
    UpdateCountersN(test_level_14);
    UpdateCountersN(test_level_15);
    UpdateCountersN(test_level_16);
    UpdateCountersN(test_level_17);
    UpdateCountersN(test_level_18);
    UpdateCountersN(test_level_19);
    UpdateCountersN(test_level_20);
    UpdateCountersN(test_level_21);
    UpdateCountersN(test_level_22);
    UpdateCountersN(test_level_23);
    UpdateCountersN(test_level_24);
    UpdateCountersN(test_level_25);
    UpdateCountersN(test_level_26);
    UpdateCountersN(test_level_27);
    UpdateCountersN(test_level_28);
    UpdateCountersN(test_level_29);
    UpdateCountersN(test_level_30);
    UpdateCountersN(test_level_31);
    UpdateCountersN(test_level_32);
    UpdateCountersN(test_level_33);
    UpdateCountersN(test_level_34);
    UpdateCountersN(test_level_35);
    UpdateCountersN(test_level_36);
    UpdateCountersN(test_level_37);
    UpdateCountersN(test_level_38);
    UpdateCountersN(test_level_39);
    UpdateCountersN(test_level_40);
    UpdateCountersN(test_level_41);
    UpdateCountersN(test_level_42);
    UpdateCountersN(test_level_43);
    UpdateCountersN(test_level_44);
    UpdateCountersN(test_level_45);
    UpdateCountersN(test_level_46);
    UpdateCountersN(test_level_47);
    UpdateCountersN(test_level_48);
    UpdateCountersN(test_level_49);
    UpdateCountersN(test_level_50);
    UpdateCountersN(test_level_51);
    UpdateCountersN(test_level_52);
    UpdateCountersN(test_level_53);
    UpdateCountersN(test_level_54);
    UpdateCountersN(test_level_55);
    UpdateCountersN(test_level_56);
    UpdateCountersN(test_level_57);
    UpdateCountersN(test_level_58);
    UpdateCountersN(test_level_59);
    UpdateCountersN(test_level_60);

END_FUNCTION
